/* Bridges — native shell.
 *
 * Five destinations: Learn, Study, Practice, Immerse, Search. The learning data, the
 * scheduler, the question generators, the icons and the avatars all come from core/
 * and native/assets/data.json — both generated by the same Python pipeline — so the
 * two platforms cannot drift apart on content or rules.
 */

import React, { useEffect, useRef, useState } from "react";
import { View, Text, Animated, Pressable, useColorScheme } from "react-native";
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { NavigationContainer, DefaultTheme, DarkTheme } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import Svg, { Path } from "react-native-svg";

import { SessionProvider, useSession } from "./src/session";
import { light, dark } from "./src/theme";
import { Loading, Avatar, HeaderTitle } from "./src/ui";
import { DRILL_TYPES } from "./src/questions";
import Talk from "./src/screens/Talk";
import { unitById, chapterOf, L, resolveWord } from "./src/data";
import Learn from "./src/screens/Learn";
import Search from "./src/screens/Search";
import Study from "./src/screens/Study";
import You from "./src/screens/You";
import { UnitScreen, LessonScreen } from "./src/screens/Unit";
import { Immerse, Video, Gate } from "./src/screens/Misc";
import WordScreen from "./src/screens/Word";
import SttLab from "./src/screens/SttLab";
import TourScreen from "./src/screens/Intro";
import Sounds from "./src/screens/Sounds";
import { ChapterTask } from "./src/screens/Task";
import { Read } from "./src/screens/Read";
import { WordsProvider, navRef } from "./src/words";
import { configureAudio } from "./src/audio";
import {
  VocabFlow, QuizFlow, DrillList, DrillFlow, PlacementFlow, SectionFlow,
  QuizSetup, CustomQuizFlow, ListeningFlow, ListeningList, PassageFlow, SoundDrillFlow,
  ShadowFlow,
} from "./src/screens/Flows";

const Tabs = createBottomTabNavigator();
const Stack = createNativeStackNavigator();

const icon = (d) => ({ color, size }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color}
       strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round">
    <Path d={d} />
  </Svg>
);

const LearnIcon = icon("M4 19V6a2 2 0 0 1 2-2h5v15H6a2 2 0 0 0-2 2zM20 19V6a2 2 0 0 0-2-2h-5v15h5a2 2 0 0 1 2 2z");
const StudyIcon = icon("M3 6h14v12H3zM7 3h14v13");
const PracticeIcon = icon("M6 9v6M18 9v6M4 11v2M20 11v2M8 7v10M16 7v10M8 12h8");
const ImmerseIcon = icon("M3 5h18v14H3zm8 4.5 4 2.5-4 2.5z");
const SearchIcon = icon("M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14zm9 16-3.5-3.5");

/* The profile avatar sits in the header, as it does on the web, rather than
   spending a tab on it. Beside it, on every screen but the path itself, a way
   home: back to the path in one press from anywhere (the owner, 2026-09-07). */
function HomeButton() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  return (
    <Pressable onPress={() => navRef.navigate("Tabs", { screen: "Learn", params: { screen: "Path" } })}
               hitSlop={8} accessibilityRole="button" accessibilityLabel="Home, the path"
               testID="home-button"
               style={{ marginRight: 12, width: 30, height: 30, alignItems: "center",
                        justifyContent: "center" }}>
      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke={p.ink2}
           strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round">
        <Path d="M4 11 12 4l8 7M6 10v9h12v-9M10 19v-5h4v5" />
      </Svg>
    </Pressable>
  );
}

function MeButton({ navigation }) {
  const { account } = useSession();
  if (!account) return null;
  return (
    <Pressable onPress={() => navigation.navigate("You")} hitSlop={8}
               accessibilityRole="button" accessibilityLabel={`${account.name}, your profile`}
               style={{ marginRight: 4 }}>
      <Avatar id={account.avatar} size={30} />
    </Pressable>
  );
}

function HeaderRight({ navigation, route }) {
  const home = !route || route.name !== "Path";
  return (
    <View style={{ flexDirection: "row", alignItems: "center" }}>
      {home ? <HomeButton /> : null}
      <MeButton navigation={navigation} />
    </View>
  );
}

const withMe = ({ navigation, route }) => ({
  headerRight: () => <HeaderRight navigation={navigation} route={route} />,
  headerBackButtonDisplayMode: "minimal",
});

/* A screen's header names the screen and what it belongs to, both read from the
   route rather than hardcoded — "Vocabulary / Around Town", not "Vocabulary". */
const titled = (what) => ({ navigation, route }) => {
  const p = (route && route.params) || {};
  const unit = p.unitId ? unitById(p.unitId) : null;
  const chapter = unit ? chapterOf(unit.id) : null;
  const label = typeof what === "function" ? what(p, unit) : what;
  const sub = unit ? unit.name
            : chapter ? chapter.title
            : null;
  return {
    headerRight: () => <HeaderRight navigation={navigation} route={route} />,
    headerBackButtonDisplayMode: "minimal",
    headerTitleAlign: "center",
    headerTitle: () => <HeaderTitle title={label} sub={sub} />,
  };
};

/* The unit screen is the one place the chapter, not the unit, is the parent. */
const unitTitled = ({ navigation, route }) => {
  const unit = unitById((route.params || {}).unitId);
  const chapter = unit ? chapterOf(unit.id) : null;
  return {
    headerRight: () => <HeaderRight navigation={navigation} route={route} />,
    headerBackButtonDisplayMode: "minimal",
    headerTitleAlign: "center",
    headerTitle: () => (
      <HeaderTitle
        title={unit ? unit.name : "Unit"}
        sub={chapter ? `Chapter ${chapter.n} · ${chapter.title}` : null}
      />
    ),
  };
};

function LearnStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Path" component={Learn} options={{ title: "Learn" }} />
      <Stack.Screen name="Unit" component={UnitScreen} options={unitTitled} />
      <Stack.Screen name="Lesson" component={LessonScreen}
                    options={titled((p) => `Lesson ${(p.index || 0) + 1}`)} />
      <Stack.Screen name="Vocab" component={VocabFlow} options={titled("Vocabulary")} />
      <Stack.Screen name="Quiz" component={QuizFlow} options={titled("Quiz")} />
      <Stack.Screen name="Video" component={Video} options={titled("Episode")} />
      <Stack.Screen name="TestOut" component={SectionFlow} options={titled("Test out")} />
      {/* The task at the end of a chapter (ROADMAP P10.5). On the Learn stack
          because that is where it is offered: it belongs to the chapter. */}
      <Stack.Screen name="ChapterTask" component={ChapterTask}
                    options={{ title: "Chapter task" }} />
      <Stack.Screen name="Placement" component={PlacementFlow}
                    options={{ title: "Placement" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function PracticeStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Drills" component={DrillList} options={{ title: "Practice" }} />
      <Stack.Screen name="Talk" component={Talk} options={{ title: "Talk" }} />
      <Stack.Screen name="QuizSetup" component={QuizSetup} options={{ title: "Quiz" }} />
      <Stack.Screen name="CustomQuiz" component={CustomQuizFlow} options={{ title: "Quiz" }} />
      {/* The route names are historical: "Scenes" is the lesson-level listening
          the learner meets first, "Listening" the native-speed passages behind
          it. The titles say which is which; renaming the routes would break
          every deep link and saved navigation state for nothing. */}
      <Stack.Screen name="Listening" component={ListeningList} options={{ title: "Native speed" }} />
      <Stack.Screen name="Passage" component={PassageFlow} options={{ title: "Listening" }} />
      <Stack.Screen name="Scenes" component={ListeningFlow} options={{ title: "Listening" }} />
      <Stack.Screen name="Sounds" component={Sounds} options={{ title: "Sounds" }} />
      {/* The pronunciation drill, reached from Sounds (ROADMAP P10.8). */}
      <Stack.Screen name="SoundDrill" component={SoundDrillFlow}
                    options={{ title: "Practise sounds" }} />
      {/* Hear a sentence and say it back (ROADMAP P10.6). */}
      <Stack.Screen name="Shadow" component={ShadowFlow} options={{ title: "Shadowing" }} />
      <Stack.Screen name="Drill" component={DrillFlow}
                    options={({ navigation, route }) => ({
                      headerRight: () => <HeaderRight navigation={navigation} route={route} />,
                      headerBackButtonDisplayMode: "minimal",
                      headerTitleAlign: "center",
                      headerTitle: () => (
                        <HeaderTitle
                          title={(DRILL_TYPES.find((d) => d.id === route.params.type) || {}).name
                                 || route.params.type}
                          sub="Drill" />
                      ),
                    })} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function ImmerseStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Episodes" component={Immerse} options={{ title: "Immerse" }} />
      {/* Russian from outside the library (ROADMAP P10.7). */}
      <Stack.Screen name="Read" component={Read} options={{ title: "Read" }} />
      <Stack.Screen name="Video" component={Video} options={titled("Episode")} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function StudyStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Cards" component={Study} options={{ title: "Study" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function SearchStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Words" component={Search} options={{ title: "Search" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

/* Three bars settle in, then the wordmark. Short enough that it never stands
   between the user and studying. */
function Splash({ onDone }) {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const bars = [useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current];
  const word = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.stagger(80, bars.map((b) =>
      Animated.timing(b, { toValue: 1, duration: 380, useNativeDriver: true }))).start();
    Animated.timing(word, { toValue: 1, duration: 420, delay: 260,
                            useNativeDriver: true }).start();
    const timer = setTimeout(onDone, 1500);
    return () => clearTimeout(timer);
  }, []);

  const widths = [52, 80, 108];
  return (
    <Pressable onPress={onDone}
               style={{ flex: 1, backgroundColor: p.bg, alignItems: "center",
                        justifyContent: "center" }}>
      <View style={{ gap: 7, marginBottom: 22, alignItems: "center" }}>
        {bars.map((b, i) => (
          <Animated.View
            key={i}
            style={{ width: widths[i], height: 13, borderRadius: 7,
                     backgroundColor: i === 2 ? p.ink : p.brand,
                     opacity: b,
                     transform: [{ scaleX: b.interpolate({
                       inputRange: [0, 1], outputRange: [0.2, 1] }) }] }}
          />
        ))}
      </View>
      <Animated.Text style={{ color: p.ink, fontSize: 30, fontWeight: "700",
                              opacity: word }}>
        Bridges
      </Animated.Text>
      <Animated.Text style={{ color: p.ink3, fontSize: 13, marginTop: 4, opacity: word }}>
        Russian, from your own words
      </Animated.Text>
    </Pressable>
  );
}

/* The word entry lives above the tabs rather than inside each stack: it is reachable
   from every screen — a tapped word in a lesson, a search result, an example
   sentence — and one screen with one back stack beats five copies of it. */
const Root = createNativeStackNavigator();

const wordTitled = ({ route }) => {
  const p = route.params || {};
  const w = p.word !== undefined ? resolveWord(p.word) : L[p.i];
  return {
    headerTitleAlign: "center",
    headerBackButtonDisplayMode: "minimal",
    headerRight: () => <HomeButton />,
    headerTitle: () => (
      <HeaderTitle title={w ? w.w : "Word"} sub={w && w.p ? w.p : "Dictionary"} />
    ),
  };
};

/* What the save layer has to say, over whatever is on screen: the row could not
   be read, or could not be written. One line, one dismissal; nothing here is
   swallowed (session.js). */
function StateBanner() {
  const { error, clearError } = useSession();
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  if (!error) return null;
  return (
    <View testID="state-banner"
          style={{ backgroundColor: p.badBg, borderBottomWidth: 1, borderBottomColor: p.bad,
                   paddingHorizontal: 16, paddingVertical: 10, flexDirection: "row",
                   alignItems: "center", gap: 12 }}>
      <Text style={{ color: p.ink, fontSize: 13, flex: 1 }}>{error.text}</Text>
      <Pressable onPress={clearError} hitSlop={8} accessibilityRole="button"
                 accessibilityLabel="Dismiss">
        <Text style={{ color: p.bad, fontSize: 13, fontWeight: "700" }}>
          {error.kind === "unreadable" ? "Keep going" : "OK"}
        </Text>
      </Pressable>
    </View>
  );
}

function Shell() {
  const { ready, account, st } = useSession();
  const [splashDone, setSplashDone] = useState(false);
  const [placement, setPlacement] = useState(null);

  /* Playback reads its two settings from here rather than from state. */
  useEffect(() => { configureAudio({ speed: st.speed, cue: st.cue }); }, [st.speed, st.cue]);

  /* Acting on the gate's answer. The navigator only exists once there is an
     account, so this runs on the render after the profile is created: effects fire
     child-first, so the stack below is mounted and the ref is live by now. */
  useEffect(() => {
    if (placement !== true) return;
    if (navRef.isReady()) {
      navRef.navigate("Tabs", { screen: "Learn", params: { screen: "Placement" } });
    }
    setPlacement(null);
  }, [placement]);

  if (!splashDone) return <Splash onDone={() => setSplashDone(true)} />;
  if (!ready) return <Loading />;
  if (!account) return <Gate onPlacement={setPlacement} />;

  return (
    <View style={{ flex: 1 }}>
    <StateBanner />
    <Root.Navigator>
      <Root.Screen name="Tabs" component={TabShell} options={{ headerShown: false }} />
      <Root.Screen name="Word" component={WordScreen} options={wordTitled} />
      {/* The player above the tabs too, so an entry's "Heard in" row opens the
          video over the entry and Back returns to the word, not to the library. */}
      <Root.Screen name="Video" component={Video} options={titled("Episode")} />
      {/* Developer-mode only; the screen itself refuses to render otherwise. */}
      <Root.Screen name="SttLab" component={SttLab} options={{ title: "STT Lab" }} />
      <Root.Screen name="Tour" component={TourScreen} options={{ title: "Tour" }} />
    </Root.Navigator>
    </View>
  );
}

function TabShell() {
  return (
    <Tabs.Navigator screenOptions={{ headerShown: false }}>
      <Tabs.Screen name="Learn" component={LearnStack}
                   options={{ tabBarIcon: LearnIcon }} />
      <Tabs.Screen name="Study" component={StudyStack}
                   options={{ tabBarIcon: StudyIcon }} />
      <Tabs.Screen name="Practice" component={PracticeStack}
                   options={{ tabBarIcon: PracticeIcon }} />
      <Tabs.Screen name="Immerse" component={ImmerseStack}
                   options={{ tabBarIcon: ImmerseIcon }} />
      <Tabs.Screen name="Search" component={SearchStack}
                   options={{ tabBarIcon: SearchIcon }} />
    </Tabs.Navigator>
  );
}

export default function App() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const base = scheme === "light" ? DefaultTheme : DarkTheme;
  const navTheme = {
    ...base,
    colors: { ...base.colors, background: p.bg, card: p.surface, text: p.ink,
              border: p.line, primary: p.brand },
  };

  return (
    <SafeAreaProvider>
      <SessionProvider>
        <NavigationContainer ref={navRef} theme={navTheme}>
          <WordsProvider>
            <Shell />
            <StatusBar style={scheme === "light" ? "dark" : "light"} />
          </WordsProvider>
        </NavigationContainer>
      </SessionProvider>
    </SafeAreaProvider>
  );
}
