/* Bridges — native shell.
 *
 * Five destinations: Learn, Study, Practice, Immerse, Search. The learning data, the
 * scheduler, the question generators, the icons and the avatars all come from core/
 * and native/assets/data.json — both generated by the same Python pipeline — so the
 * two platforms cannot drift apart on content or rules.
 */

import React, { useEffect, useMemo, useRef, useState } from "react";
import { View, Animated, Pressable, useColorScheme } from "react-native";
import { StatusBar } from "expo-status-bar";
import { useFonts } from "expo-font";
import { Nunito_400Regular, Nunito_600SemiBold, Nunito_700Bold,
         Nunito_800ExtraBold } from "@expo-google-fonts/nunito";
import { SafeAreaProvider, useSafeAreaInsets } from "react-native-safe-area-context";
import { NavigationContainer, DefaultTheme, DarkTheme,
         getFocusedRouteNameFromRoute } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import Svg, { Path } from "react-native-svg";

import { SessionProvider, useSession } from "./src/session";
import { light, dark } from "./src/theme";
import { hidesTabBar } from "./src/fullscreen";
import { Loading, Avatar, HeaderTitle, Text } from "./src/ui";
import { DRILL_TYPES } from "./src/questions";
import Talk from "./src/screens/Talk";
import Tutor from "./src/screens/Tutor";
import Translate from "./src/screens/Translate";
import { unitById, chapterOf, L, resolveWord, dueCount } from "./src/data";
import Learn from "./src/screens/Learn";
import Search from "./src/screens/Search";
import Study from "./src/screens/Study";
import You from "./src/screens/You";
import Stats from "./src/screens/Stats";
import Credits from "./src/screens/Credits";
import { UnitScreen, LessonScreen } from "./src/screens/Unit";
import { Immerse, Video } from "./src/screens/Misc";
import { Gate } from "./src/screens/Gate";
import WordScreen from "./src/screens/Word";
import SttLab from "./src/screens/SttLab";
import TourScreen from "./src/screens/Intro";
import Sounds from "./src/screens/Sounds";
import Grammar from "./src/screens/Grammar";
import { ChapterTask } from "./src/screens/Task";
import { WordsProvider, navRef } from "./src/words";
import { configureAudio } from "./src/audio";
import { setHaptics } from "./src/haptics";
import { arm as armReminders } from "./src/notify";
import { workedOn } from "@core/scheduler";
import { setDayStart, today } from "@core/util";
import { ErrorBoundary } from "./src/boundary";
import { installCrashHandler } from "./src/crash";
import { warmToken } from "./src/lib/feedback";
import { tabIcon } from "./src/tabicons";
import { flushState } from "./src/store";
import {
  VocabFlow, QuizFlow, DrillList, DrillFlow, PlacementFlow, SectionFlow,
  QuizSetup, CustomQuizFlow, ListeningFlow, ScenesList, SoundDrillFlow,
  ShadowFlow, BuildDrillFlow, FinalFlow,
} from "./src/screens/Flows";

/* Where the day starts, from this device's own clock (ROADMAP 13.24).
 *
 * At module scope rather than in an effect: the session loader stamps the
 * streak and rolls the daily ration the moment state is read, which is before
 * any component of ours has mounted. Configured late, the first read of the
 * app's life would use UTC days and the rest would not.
 *
 * Not a setting. The device knows its own offset, and a learner who moves is
 * corrected by the next launch. */
setDayStart({ offsetMinutes: new Date().getTimezoneOffset() });

/* …and the same for errors that never reach a React boundary: a rejected
   promise, a callback from a native module. At module scope so it is in place
   before the first screen renders (src/crash.js). */
installCrashHandler();

/* …and this install's Worker token, read from the device or asked for once
   (ROADMAP 13.39), so the first Say does not wait for two round trips. Nothing
   happens in a build with no Worker address, and nothing is reported: the first
   request that needs a token tries again. */
warmToken();

const Tabs = createBottomTabNavigator();
const Stack = createNativeStackNavigator();

/* The tab icons live in src/tabicons.js, where the tour's last card reads the
   same five. */
const LearnIcon = tabIcon("Learn");
const StudyIcon = tabIcon("Study");
const PracticeIcon = tabIcon("Practice");
const ImmerseIcon = tabIcon("Immerse");
const SearchIcon = tabIcon("Search");

/* The profile avatar sits in the header, as it does on the web, rather than
   spending a tab on it. Beside it, on every screen but the path itself, a way
   home: back to the path in one press from anywhere (the owner, 2026-09-07). */
function HomeButton() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  return (
    <Pressable onPress={() => navRef.navigate("Tabs", { screen: "Learn", params: { screen: "Path" } })}
               hitSlop={8} accessibilityRole="button" accessibilityLabel="Home, the path"
               testID="home-button"
               style={{ marginRight: 12, width: 30, height: 30, alignItems: "center",
                        justifyContent: "center" }}>
      <Svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke={p.ink2}
           strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round">
        <Path d="M4 11 12 4l8 7M6 10v9h12v-9M10 19v-5h4v5" />
      </Svg>
    </Pressable>
  );
}

function MeButton({ navigation }) {
  const { account } = useSession();
  if (!account) return null;
  return (
    <Pressable onPress={() => navigation.navigate("You")} hitSlop={8}
               accessibilityRole="button" accessibilityLabel={`${account.name}, your profile`}
               style={{ marginRight: 4 }}>
      <Avatar id={account.avatar} size={30} />
    </Pressable>
  );
}

function HeaderRight({ navigation, route }) {
  const home = !route || route.name !== "Path";
  return (
    <View style={{ flexDirection: "row", alignItems: "center" }}>
      {home ? <HomeButton /> : null}
      <MeButton navigation={navigation} />
    </View>
  );
}

/* Every stack shares one transition, set here rather than left to whatever each
   platform defaults to. It was unset, so a lesson, a drill and a dictionary
   entry each arrived slightly differently depending on what Android felt like
   doing, which is one of the ways an app reads as assembled rather than made
   (the owner on making it feel professional, 2026-09-10).

   `slide_from_right` on both because the whole app is a stack you go *into* and
   come back out of: a lesson from the path, a word from a sentence, a drill
   from Practice. `fade` would be flatter and cheaper to run, and would also
   lose the only cue that says which direction you just went. */
const withMe = ({ navigation, route }) => ({
  headerRight: () => <HeaderRight navigation={navigation} route={route} />,
  headerBackButtonDisplayMode: "minimal",
  animation: "slide_from_right",
  animationDuration: 260,
});

/* A screen's header names the screen and what it belongs to, both read from the
   route rather than hardcoded — "Vocabulary / Around Town", not "Vocabulary". */
const titled = (what) => ({ navigation, route }) => {
  const p = (route && route.params) || {};
  const unit = p.unitId ? unitById(p.unitId) : null;
  const chapter = unit ? chapterOf(unit.id) : null;
  const label = typeof what === "function" ? what(p, unit) : what;
  const sub = unit ? unit.name
            : chapter ? chapter.title
            : null;
  return {
    headerRight: () => <HeaderRight navigation={navigation} route={route} />,
    headerBackButtonDisplayMode: "minimal",
    headerTitleAlign: "center",
    headerTitle: () => <HeaderTitle title={label} sub={sub} />,
  };
};

/* The unit screen is the one place the chapter, not the unit, is the parent. */
const unitTitled = ({ navigation, route }) => {
  const unit = unitById((route.params || {}).unitId);
  const chapter = unit ? chapterOf(unit.id) : null;
  return {
    headerRight: () => <HeaderRight navigation={navigation} route={route} />,
    headerBackButtonDisplayMode: "minimal",
    headerTitleAlign: "center",
    headerTitle: () => (
      <HeaderTitle
        title={unit ? unit.name : "Unit"}
        sub={chapter ? `Chapter ${chapter.n} · ${chapter.title}` : null}
      />
    ),
  };
};

function LearnStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Path" component={Learn} options={{ title: "Learn" }} />
      <Stack.Screen name="Unit" component={UnitScreen} options={unitTitled} />
      <Stack.Screen name="Lesson" component={LessonScreen}
                    options={titled((p) => `Lesson ${(p.index || 0) + 1}`)} />
      <Stack.Screen name="Vocab" component={VocabFlow} options={titled("Vocabulary")} />
      <Stack.Screen name="Quiz" component={QuizFlow} options={titled("Quiz")} />
      <Stack.Screen name="Video" component={Video} options={titled("Episode")} />
      {/* The lesson's own conversation, opened from its Listening step. Here as
          well as on the Practice stack for the reason `Video` is in two stacks:
          **a route is only reachable from the stack it is registered in**, and a
          `navigate` to one that is not there fails silently — no error, no
          screen, a dead button. That is what shipped on 2026-09-17. */}
      <Stack.Screen name="Scenes" component={ListeningFlow} options={{ title: "Listening" }} />
      <Stack.Screen name="TestOut" component={SectionFlow} options={titled("Test out")} />
      {/* The final test, offered at the foot of the path once the spine is
          walked; on this stack because that is where it is offered. */}
      <Stack.Screen name="Final" component={FinalFlow} options={{ title: "Final test" }} />
      {/* The task at the end of a chapter (ROADMAP P10.5). On the Learn stack
          because that is where it is offered: it belongs to the chapter. */}
      <Stack.Screen name="ChapterTask" component={ChapterTask}
                    options={{ title: "Chapter task" }} />
      <Stack.Screen name="Placement" component={PlacementFlow}
                    options={{ title: "Placement" }} />
      {/* The grammar reference. On this stack as well as Practice because the
          bulb inside a quiz opens it, and a quiz runs here — §23's rule: a
          route is only reachable from the stack it is registered in. */}
      <Stack.Screen name="Grammar" component={Grammar} options={{ title: "Grammar" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
      <Stack.Screen name="Stats" component={Stats} options={{ title: "Statistics" }} />
      <Stack.Screen name="Credits" component={Credits} options={{ title: "Credits" }} />
    </Stack.Navigator>
  );
}

function PracticeStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Drills" component={DrillList} options={{ title: "Practice" }} />
      <Stack.Screen name="Talk" component={Talk} options={{ title: "Talk" }} />
      {/* The free conversation with a tutor who knows the learner (2026-09-26). */}
      <Stack.Screen name="Tutor" component={Tutor} options={{ title: "Tutor" }} />
      {/* Speak Russian, read it back in English (2026-09-22). */}
      <Stack.Screen name="Translate" component={Translate} options={{ title: "Translate" }} />
      <Stack.Screen name="QuizSetup" component={QuizSetup} options={{ title: "Quiz" }} />
      <Stack.Screen name="CustomQuiz" component={CustomQuizFlow} options={{ title: "Quiz" }} />
      {/* "Scenes" is the historical name for the lesson-level listening;
          renaming the route would break every saved navigation state for
          nothing. The native-speed passages that once sat beside it were
          removed 2026-09-23 — Immerse is the native-speed listening. */}
      {/* The listening pieces to choose from, and one of them being listened to.
          **Not "Conversations"** — that is Talk, the spoken exchange with the
          tutor (§30f), and the owner found the two competing for the word:
          *"what happened to the conversation with AI module??? That was
          conversation. This one should just be called listening."* */}
      <Stack.Screen name="SceneList" component={ScenesList} options={{ title: "Listening" }} />
      <Stack.Screen name="Scenes" component={ListeningFlow} options={{ title: "Listening" }} />
      <Stack.Screen name="Sounds" component={Sounds} options={{ title: "Alphabet" }} />
      {/* Beside Alphabet, and the same kind of thing: a reference that is open
          from the first screen and never scored (2026-09-27). */}
      <Stack.Screen name="Grammar" component={Grammar} options={{ title: "Grammar" }} />
      {/* The pronunciation drill, reached from Sounds (ROADMAP P10.8). */}
      <Stack.Screen name="SoundDrill" component={SoundDrillFlow}
                    options={{ title: "Practice sounds" }} />
      {/* A long word a syllable at a time, front to back (core/buildup.js). */}
      <Stack.Screen name="BuildDrill" component={BuildDrillFlow}
                    options={{ title: "Word building" }} />
      {/* Hear a sentence and say it back (ROADMAP P10.6). */}
      <Stack.Screen name="Shadow" component={ShadowFlow} options={{ title: "Shadowing" }} />
      {/* What a drill asks about is on its own cog (Flows.js DrillOptions);
          the setup screen that stood here went on 2026-09-26. */}
      <Stack.Screen name="Drill" component={DrillFlow}
                    options={({ navigation, route }) => ({
                      headerRight: () => <HeaderRight navigation={navigation} route={route} />,
                      headerBackButtonDisplayMode: "minimal",
                      headerTitleAlign: "center",
                      headerTitle: () => (
                        <HeaderTitle
                          title={(DRILL_TYPES.find((d) => d.id === route.params.type) || {}).name
                                 || route.params.type}
                          sub="Drill" />
                      ),
                    })} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
      <Stack.Screen name="Stats" component={Stats} options={{ title: "Statistics" }} />
      <Stack.Screen name="Credits" component={Credits} options={{ title: "Credits" }} />
    </Stack.Navigator>
  );
}

function ImmerseStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Episodes" component={Immerse} options={{ title: "Immerse" }} />
      {/* Russian from outside the library (ROADMAP P10.7). */}
      <Stack.Screen name="Video" component={Video} options={titled("Episode")} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
      <Stack.Screen name="Stats" component={Stats} options={{ title: "Statistics" }} />
      <Stack.Screen name="Credits" component={Credits} options={{ title: "Credits" }} />
    </Stack.Navigator>
  );
}

function StudyStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Cards" component={Study} options={{ title: "Study" }} />
      {/* A card whose word was mined from a video offers "from video" on its
          back, and that control was dead on this tab — the route was on Learn
          and Immerse but not here. Found by routes.test.js, not by anybody
          pressing it; it had been dead since the mined-word link was added. */}
      <Stack.Screen name="Video" component={Video} options={titled("Episode")} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
      <Stack.Screen name="Stats" component={Stats} options={{ title: "Statistics" }} />
      <Stack.Screen name="Credits" component={Credits} options={{ title: "Credits" }} />
    </Stack.Navigator>
  );
}

function SearchStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Words" component={Search} options={{ title: "Search" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
      <Stack.Screen name="Stats" component={Stats} options={{ title: "Statistics" }} />
      <Stack.Screen name="Credits" component={Credits} options={{ title: "Credits" }} />
    </Stack.Navigator>
  );
}

/* Three bars settle in, then the wordmark, and it is gone inside a second — it
   never stands between the learner and studying, and a tap ends it early.
   No tagline: the mark and the name are the whole of it (the owner,
   2026-09-19, on "Russian, from your own words"). */
const SPLASH_MS = 900;
function Splash({ onDone }) {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const bars = [useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current];
  const word = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.stagger(60, bars.map((b) =>
      Animated.timing(b, { toValue: 1, duration: 260, useNativeDriver: true }))).start();
    Animated.timing(word, { toValue: 1, duration: 300, delay: 180,
                            useNativeDriver: true }).start();
    const timer = setTimeout(onDone, SPLASH_MS);
    return () => clearTimeout(timer);
  }, []);

  const widths = [52, 80, 108];
  return (
    <Pressable onPress={onDone}
               style={{ flex: 1, backgroundColor: p.bg, alignItems: "center",
                        justifyContent: "center" }}>
      <View style={{ gap: 7, marginBottom: 22, alignItems: "center" }}>
        {bars.map((b, i) => (
          <Animated.View
            key={i}
            style={{ width: widths[i], height: 13, borderRadius: 7,
                     backgroundColor: i === 2 ? p.ink : p.brand,
                     opacity: b,
                     transform: [{ scaleX: b.interpolate({
                       inputRange: [0, 1], outputRange: [0.2, 1] }) }] }}
          />
        ))}
      </View>
      <Animated.Text style={{ color: p.ink, fontSize: 30, fontWeight: "700",
                              opacity: word }}>
        Bridges
      </Animated.Text>
    </Pressable>
  );
}

/* The word entry lives above the tabs rather than inside each stack: it is reachable
   from every screen — a tapped word in a lesson, a search result, an example
   sentence — and one screen with one back stack beats five copies of it. */
const Root = createNativeStackNavigator();

const wordTitled = ({ route }) => {
  const p = route.params || {};
  const w = p.word !== undefined ? resolveWord(p.word) : L[p.i];
  return {
    headerTitleAlign: "center",
    headerBackButtonDisplayMode: "minimal",
    headerRight: () => <HomeButton />,
    headerTitle: () => (
      <HeaderTitle title={w ? w.w : "Word"} sub={w && w.p ? w.p : "Dictionary"} />
    ),
  };
};

/* What the save layer has to say, over whatever is on screen: the row could not
   be read, or could not be written. One line, one dismissal; nothing here is
   swallowed (session.js). */
function StateBanner() {
  const { error, clearError } = useSession();
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  if (!error) return null;
  return (
    <View testID="state-banner"
          style={{ backgroundColor: p.badBg, borderBottomWidth: 1, borderBottomColor: p.bad,
                   paddingHorizontal: 16, paddingVertical: 10, flexDirection: "row",
                   alignItems: "center", gap: 12 }}>
      <Text style={{ color: p.ink, fontSize: 13, flex: 1 }}>{error.text}</Text>
      <Pressable onPress={clearError} hitSlop={8} accessibilityRole="button"
                 accessibilityLabel="Dismiss">
        <Text style={{ color: p.bad, fontSize: 13, fontWeight: "700" }}>
          {error.kind === "unreadable" ? "Keep going" : "OK"}
        </Text>
      </Pressable>
    </View>
  );
}

function Shell() {
  const { ready, account, st } = useSession();
  const [splashDone, setSplashDone] = useState(false);
  const [placement, setPlacement] = useState(null);

  /* Playback reads its two settings from here rather than from state. */
  useEffect(() => { configureAudio({ speed: st.speed, cue: st.cue }); }, [st.speed, st.cue]);
  /* …and so does the vibration motor, for the same reason: a call site that
     had to read state to decide whether to buzz would be a call site that
     could get it wrong. */
  useEffect(() => { setHaptics(st.haptics !== false); }, [st.haptics]);

  /* The reminder window is re-laid whenever the setting moves **or the day
     becomes worked** — those are the only two things that change what should be
     scheduled. Keying the effect on `st.seen` instead would re-arm on every
     single grade, which is fourteen native calls for nothing; `workedToday`
     flips once a day, so this runs at most twice. `workedOn` scans the cards in
     under a millisecond (§30u measured it), so it costs nothing to derive. */
  const workedToday = useMemo(() => workedOn(st, today()), [st.seen]);
  useEffect(() => { armReminders(st, st.remind); }, [st.remind, workedToday]);

  /* Acting on the gate's answer. The navigator only exists once there is an
     account, so this runs on the render after the profile is created: effects fire
     child-first, so the stack below is mounted and the ref is live by now. */
  useEffect(() => {
    if (placement !== true) return;
    if (navRef.isReady()) {
      navRef.navigate("Tabs", { screen: "Learn", params: { screen: "Placement" } });
    }
    setPlacement(null);
  }, [placement]);

  if (!splashDone) return <Splash onDone={() => setSplashDone(true)} />;
  if (!ready) return <Loading />;
  if (!account) return <Gate onPlacement={setPlacement} />;

  return (
    <View style={{ flex: 1 }}>
    <StateBanner />
    <Root.Navigator>
      <Root.Screen name="Tabs" component={TabShell} options={{ headerShown: false }} />
      <Root.Screen name="Word" component={WordScreen} options={wordTitled} />
      {/* The player above the tabs too, so an entry's "Heard in" row opens the
          video over the entry and Back returns to the word, not to the library. */}
      <Root.Screen name="Video" component={Video} options={titled("Episode")} />
      {/* Developer-mode only; the screen itself refuses to render otherwise. */}
      <Root.Screen name="SttLab" component={SttLab} options={{ title: "STT Lab" }} />
      <Root.Screen name="Tour" component={TourScreen} options={{ title: "Tour" }} />
    </Root.Navigator>
    </View>
  );
}

/* The five tabs.
 *
 * These were swipeable for a day — the top-tab navigator pinned to the bottom,
 * which is a pager and carries the page under the finger. The owner asked for
 * it and then asked for it back out on 2026-09-12: *"remove the swipe side by
 * side thing, it animates poorly"*. He is right, and the reason is structural
 * rather than a setting that was set wrong: every tab is a whole screen of its
 * own — a path drawn in SVG, a video library with thumbnails, a dictionary —
 * and a pager keeps the neighbouring page mounted and moves it under the
 * finger. On a phone that is a lot of work per frame for a gesture that saves
 * one tap, and it showed.
 *
 * So: the ordinary bottom tab navigator, which renders the tab you are on and
 * cross-fades. `react-native-pager-view` and `@react-navigation/material-top-tabs`
 * went with it, and so did `src/tabs.js`, which existed only to decide when a
 * sideways drag belonged to the tabs rather than to the screen. Three fewer
 * moving parts and one fewer native module for EAS to build.
 *
 * The blue line above the active tab went too; it was the pager's indicator.
 * The icon and label turning brand is what says where you are — which is what
 * it already said, alongside it. */
function TabShell() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const insets = useSafeAreaInsets();
  // What is waiting, on the tab itself (docs/PLAYBOOK.md 2.2): the count
  // Anki shows beside a deck, so the pile is known before it is opened.
  const { st } = useSession();
  const due = dueCount(st);
  return (
    <Tabs.Navigator
      screenOptions={({ route }) => ({
        headerShown: false,
        tabBarActiveTintColor: p.brand,
        tabBarInactiveTintColor: p.ink3,
        tabBarHideOnKeyboard: true,
        // Inside a run the tabs are an escape hatch across the bottom of the
        // work; the header's back arrow is the way out that keeps your place.
        tabBarStyle: hidesTabBar(getFocusedRouteNameFromRoute(route))
          ? { display: "none" }
          : {
            backgroundColor: p.surface,
            borderTopWidth: 1, borderTopColor: p.line,
            height: 58 + insets.bottom,
            paddingBottom: insets.bottom + 6,
            paddingTop: 6,
            elevation: 0, shadowOpacity: 0,
          },
        tabBarItemStyle: { gap: 2 },
        tabBarLabelStyle: { fontSize: 11, fontWeight: "600", margin: 0 },
      })}
    >
      <Tabs.Screen name="Learn" component={LearnStack}
                   options={{ tabBarIcon: LearnIcon }} />
      <Tabs.Screen name="Study" component={StudyStack}
                   options={{ tabBarIcon: StudyIcon, tabBarBadge: due > 0 ? (due > 999 ? "999+" : due) : undefined,
                              tabBarBadgeStyle: { backgroundColor: p.brand, color: p.brandOn, fontSize: 11 } }} />
      <Tabs.Screen name="Practice" component={PracticeStack}
                   options={{ tabBarIcon: PracticeIcon }} />
      <Tabs.Screen name="Immerse" component={ImmerseStack}
                   options={{ tabBarIcon: ImmerseIcon }} />
      <Tabs.Screen name="Search" component={SearchStack}
                   options={{ tabBarIcon: SearchIcon }} />
    </Tabs.Navigator>
  );
}

export default function App() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const base = scheme === "light" ? DefaultTheme : DarkTheme;
  const navTheme = {
    ...base,
    colors: { ...base.colors, background: p.bg, card: p.surface, text: p.ink,
              border: p.line, primary: p.brand },
  };

  /* The typeface, before anything is drawn in it. Text rendered while the font
     is still loading comes out in the system one and then jumps, which is the
     flash every app with a webfont gets wrong; the app already waits behind a
     splash, so this waits there too and nothing is ever drawn twice.
     A font that fails to load is not worth refusing to start over: `loaded`
     turns true either way, and Text falls back to the system face. */
  const [loaded, fontError] = useFonts({
    Nunito_400Regular, Nunito_600SemiBold, Nunito_700Bold, Nunito_800ExtraBold,
  });
  if (!loaded && !fontError) return null;

  /* The boundary sits **inside** SafeAreaProvider and outside everything else
   * (src/boundary.js).
   *
   * Inside, because its fallback is a real screen that needs the insets — a
   * "Something broke" title under the status bar is the second thing going
   * wrong. Outside SessionProvider and the navigator, because those are among
   * the things that can throw, and a boundary a crash can take with it is not
   * a boundary.
   *
   * The cost of being this high up is that "Try again" remounts the session,
   * so the way out is the *other* button: back to the path, which is a
   * different screen reading different data. A crash inside one lesson does
   * not need the whole tree rebuilt, but a boundary per screen is a second
   * mechanism to keep in step and the path is one tap from anywhere anyway.
   */
  return (
    <SafeAreaProvider>
      <ErrorBoundary
        onCrash={() => { flushState(); }}
        onHome={() => { if (navRef.isReady()) navRef.navigate("Learn", { screen: "Path" }); }}
      >
        <SessionProvider>
          <NavigationContainer ref={navRef} theme={navTheme}>
            <WordsProvider>
              <Shell />
              <StatusBar style={scheme === "light" ? "dark" : "light"} />
            </WordsProvider>
          </NavigationContainer>
        </SessionProvider>
      </ErrorBoundary>
    </SafeAreaProvider>
  );
}
