/* Bridges — native shell.
 *
 * Five destinations: Learn, Study, Practice, Immerse, Search. The learning data, the
 * scheduler, the question generators, the icons and the avatars all come from core/
 * and native/assets/data.json — both generated by the same Python pipeline — so the
 * two platforms cannot drift apart on content or rules.
 */

import React, { useEffect, useRef, useState } from "react";
import { View, Text, Animated, Pressable, useColorScheme } from "react-native";
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { NavigationContainer, DefaultTheme, DarkTheme } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import Svg, { Path } from "react-native-svg";

import { SessionProvider, useSession } from "./src/session";
import { light, dark } from "./src/theme";
import { Loading, Avatar } from "./src/ui";
import Learn from "./src/screens/Learn";
import Search from "./src/screens/Search";
import Study from "./src/screens/Study";
import You from "./src/screens/You";
import { UnitScreen, LessonScreen } from "./src/screens/Unit";
import { Immerse, Video, Gate } from "./src/screens/Misc";
import {
  VocabFlow, QuizFlow, DrillList, DrillFlow, PlacementFlow, SectionFlow,
} from "./src/screens/Flows";

const Tabs = createBottomTabNavigator();
const Stack = createNativeStackNavigator();

const icon = (d) => ({ color, size }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color}
       strokeWidth={1.9} strokeLinecap="round" strokeLinejoin="round">
    <Path d={d} />
  </Svg>
);

const LearnIcon = icon("M4 19V6a2 2 0 0 1 2-2h5v15H6a2 2 0 0 0-2 2zM20 19V6a2 2 0 0 0-2-2h-5v15h5a2 2 0 0 1 2 2z");
const StudyIcon = icon("M3 6h14v12H3zM7 3h14v13");
const PracticeIcon = icon("M6 9v6M18 9v6M4 11v2M20 11v2M8 7v10M16 7v10M8 12h8");
const ImmerseIcon = icon("M3 5h18v14H3zm8 4.5 4 2.5-4 2.5z");
const SearchIcon = icon("M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14zm9 16-3.5-3.5");

/* The profile avatar sits in the header, as it does on the web, rather than
   spending a tab on it. */
function MeButton({ navigation }) {
  const { account } = useSession();
  if (!account) return null;
  return (
    <Pressable onPress={() => navigation.navigate("You")} hitSlop={8}
               style={{ marginRight: 4 }}>
      <Avatar id={account.avatar} size={30} />
    </Pressable>
  );
}

const withMe = ({ navigation }) => ({
  headerRight: () => <MeButton navigation={navigation} />,
});

function LearnStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Path" component={Learn} options={{ title: "Learn" }} />
      <Stack.Screen name="Unit" component={UnitScreen} options={{ title: "Unit" }} />
      <Stack.Screen name="Lesson" component={LessonScreen} options={{ title: "Lesson" }} />
      <Stack.Screen name="Vocab" component={VocabFlow} options={{ title: "Vocabulary" }} />
      <Stack.Screen name="Quiz" component={QuizFlow} options={{ title: "Quiz" }} />
      <Stack.Screen name="Video" component={Video} options={{ title: "Video" }} />
      <Stack.Screen name="TestOut" component={SectionFlow} options={{ title: "Test out" }} />
      <Stack.Screen name="Placement" component={PlacementFlow}
                    options={{ title: "Placement" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function PracticeStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Drills" component={DrillList} options={{ title: "Practice" }} />
      <Stack.Screen name="Drill" component={DrillFlow}
                    options={({ route }) => ({ title: route.params.type })} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function ImmerseStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Episodes" component={Immerse} options={{ title: "Immerse" }} />
      <Stack.Screen name="Video" component={Video} options={{ title: "Video" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function StudyStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Cards" component={Study} options={{ title: "Study" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

function SearchStack() {
  return (
    <Stack.Navigator screenOptions={withMe}>
      <Stack.Screen name="Words" component={Search} options={{ title: "Search" }} />
      <Stack.Screen name="You" component={You} options={{ title: "You" }} />
    </Stack.Navigator>
  );
}

/* Three bars settle in, then the wordmark. Short enough that it never stands
   between the user and studying. */
function Splash({ onDone }) {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const bars = [useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current,
                useRef(new Animated.Value(0)).current];
  const word = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.stagger(80, bars.map((b) =>
      Animated.timing(b, { toValue: 1, duration: 380, useNativeDriver: true }))).start();
    Animated.timing(word, { toValue: 1, duration: 420, delay: 260,
                            useNativeDriver: true }).start();
    const timer = setTimeout(onDone, 1500);
    return () => clearTimeout(timer);
  }, []);

  const widths = [52, 80, 108];
  return (
    <Pressable onPress={onDone}
               style={{ flex: 1, backgroundColor: p.bg, alignItems: "center",
                        justifyContent: "center" }}>
      <View style={{ gap: 7, marginBottom: 22, alignItems: "center" }}>
        {bars.map((b, i) => (
          <Animated.View
            key={i}
            style={{ width: widths[i], height: 13, borderRadius: 7,
                     backgroundColor: i === 2 ? p.ink : p.brand,
                     opacity: b,
                     transform: [{ scaleX: b.interpolate({
                       inputRange: [0, 1], outputRange: [0.2, 1] }) }] }}
          />
        ))}
      </View>
      <Animated.Text style={{ color: p.ink, fontSize: 30, fontWeight: "700",
                              opacity: word }}>
        Bridges
      </Animated.Text>
      <Animated.Text style={{ color: p.ink3, fontSize: 13, marginTop: 4, opacity: word }}>
        Russian, from your own words
      </Animated.Text>
    </Pressable>
  );
}

function Shell() {
  const { ready, account } = useSession();
  const [splashDone, setSplashDone] = useState(false);
  const [placement, setPlacement] = useState(null);

  if (!splashDone) return <Splash onDone={() => setSplashDone(true)} />;
  if (!ready) return <Loading />;
  if (!account) return <Gate onPlacement={(wanted) => setPlacement(wanted)} />;

  return (
    <Tabs.Navigator
      screenOptions={{ headerShown: false }}
      initialRouteName={placement ? "Learn" : "Learn"}
    >
      <Tabs.Screen name="Learn" component={LearnStack}
                   options={{ tabBarIcon: LearnIcon }} />
      <Tabs.Screen name="Study" component={StudyStack}
                   options={{ tabBarIcon: StudyIcon }} />
      <Tabs.Screen name="Practice" component={PracticeStack}
                   options={{ tabBarIcon: PracticeIcon }} />
      <Tabs.Screen name="Immerse" component={ImmerseStack}
                   options={{ tabBarIcon: ImmerseIcon }} />
      <Tabs.Screen name="Search" component={SearchStack}
                   options={{ tabBarIcon: SearchIcon }} />
    </Tabs.Navigator>
  );
}

export default function App() {
  const scheme = useColorScheme();
  const p = scheme === "light" ? light : dark;
  const base = scheme === "light" ? DefaultTheme : DarkTheme;
  const navTheme = {
    ...base,
    colors: { ...base.colors, background: p.bg, card: p.surface, text: p.ink,
              border: p.line, primary: p.brand },
  };

  return (
    <SafeAreaProvider>
      <SessionProvider>
        <NavigationContainer theme={navTheme}>
          <Shell />
          <StatusBar style={scheme === "light" ? "dark" : "light"} />
        </NavigationContainer>
      </SessionProvider>
    </SafeAreaProvider>
  );
}
