/* Playback: the collection's own recordings first, the device voice only for gaps.
 *
 * Same rule as the web app. expo-audio replaces the Audio element, expo-speech
 * replaces SpeechSynthesis; the decision of what to play is unchanged.
 */

import { createAudioPlayer, setAudioModeAsync } from "expo-audio";
import * as Speech from "expo-speech";
import { audioUrl } from "./data";
import { bare } from "@core/util";

let player = null;
let ready = false;

async function prepare() {
  if (ready) return;
  try {
    // Study out loud with the ringer silenced — the usual case on a phone.
    await setAudioModeAsync({ playsInSilentMode: true, shouldPlayInBackground: false });
  } catch (e) { /* not fatal; playback still works with default routing */ }
  ready = true;
}

/* Whether this device can actually say Russian.
 *
 * Asking the platform to speak ru-RU when no Russian voice is installed does not
 * fail — Android quietly substitutes the default voice, which reads Cyrillic as
 * nonsense in English. That is worse than silence: it is wrong audio presented as
 * the language being learned, which rule 27 forbids. The web app has always found a
 * voice first and disabled the button without one (app.js pickVoice); this is that
 * rule, ported.
 *
 * Probed once, asynchronously. Until it resolves there is no voice, so a recording
 * still plays and TTS stays quiet — the safe way round. */
let ruVoice = null;
let probe = null;
const voiceListeners = new Set();

export function hasRussianVoice() {
  return !!ruVoice;
}

export function probeVoices() {
  if (!probe) {
    probe = (async () => {
      try {
        const voices = await Speech.getAvailableVoicesAsync();
        ruVoice = (voices || []).find((v) => v.language && /^ru/i.test(v.language)) || null;
      } catch (e) {
        ruVoice = null;                 // no enumeration: treat as no voice
      }
      voiceListeners.forEach((fn) => fn());
      return ruVoice;
    })();
  }
  return probe;
}

/* Re-render a speaker once the probe lands. */
export function onVoicesChanged(fn) {
  voiceListeners.add(fn);
  return () => voiceListeners.delete(fn);
}

/* Ask again. The set of installed voices is not fixed for the life of the process —
   someone can install a Russian language pack and come back — so the answer has to
   be refreshable rather than decided once at launch. */
export function refreshVoices() {
  probe = null;
  ruVoice = null;
  return probeVoices();
}

probeVoices();

/* What is playing right now, as a promise that settles when it ends — by
   finishing, by being replaced, by being stopped, or (a stalled stream) by the
   guard below. Anything that must not talk over the language audio awaits
   whenIdle() first; the runner's autoplay does. */
let current = Promise.resolve();
let settle = null;
// A stream that never reports finishing would hold the next question forever.
// Fifteen seconds is longer than any recording in the collection (the longest
// pooled sentence is under ten), so this only ever fires on a stall.
const STALL_MS = 15000;

function begin() {
  if (settle) settle();
  let done;
  current = new Promise((res) => { done = res; });
  const timer = setTimeout(() => done(), STALL_MS);
  settle = () => { clearTimeout(timer); done(); settle = null; };
  return settle;
}

export const whenIdle = () => current;

export function speakTTS(text) {
  if (!ruVoice) return false;
  try {
    Speech.stop();
    const end = begin();
    // Pin the voice, not just the language tag: the tag alone still lets the
    // platform fall back to whatever it has.
    Speech.speak(bare(text), {
      language: ruVoice.language, voice: ruVoice.identifier, rate: 0.9,
      onDone: end, onStopped: end, onError: end,
    });
    return true;
  } catch (e) {
    if (settle) settle();
    return false;
  }
}

/* Plays the real recording when the collection has one, otherwise the device voice.
   A failed load falls back rather than leaving the learner in silence. Resolves
   with true/false for whether anything started; the playback itself is tracked
   by whenIdle(). */
export async function say(text) {
  const url = audioUrl(text);
  if (!url) return speakTTS(text);
  await prepare();
  try {
    Speech.stop();
    if (player) { player.remove(); player = null; }
    const end = begin();
    player = createAudioPlayer({ uri: url });
    if (player.addListener) {
      player.addListener("playbackStatusUpdate", (s) => {
        if (s && (s.didJustFinish || s.error)) end();
      });
    }
    player.play();
    return true;
  } catch (e) {
    if (settle) settle();
    return speakTTS(text);
  }
}

export function stop() {
  try { Speech.stop(); } catch (e) {}
  try { if (player) player.pause(); } catch (e) {}
  if (settle) settle();
}

export const hasRealAudio = (text) => !!audioUrl(text);

/* ------------------------------------------------------------------- cues */

/* Generated by tools/make_sounds.py. Kept on their own players so a cue never
   interrupts, or gets interrupted by, the word being spoken. */
const CUES = {
  right: require("../assets/sfx/correct.wav"),
  wrong: require("../assets/sfx/wrong.wav"),
};
const cuePlayers = {};

export function cue(kind) {
  const src = CUES[kind];
  if (!src) return false;
  try {
    if (!cuePlayers[kind]) {
      cuePlayers[kind] = createAudioPlayer(src);
      // Under the language audio, not over it.
      cuePlayers[kind].volume = kind === "wrong" ? 0.55 : 0.7;
    }
    const p = cuePlayers[kind];
    p.seekTo(0);
    p.play();
    return true;
  } catch (e) {
    return false;
  }
}

const CYRILLIC = /[Ѐ-ӿ]/;

/* What is worth hearing is the Russian, whichever part of the question holds it.
   Reading an English gloss aloud teaches nothing, so a question whose correct
   option is English falls back to the Russian on the prompt. */
export function answerAudioText(q, correctOption) {
  const label = correctOption && correctOption.label;
  if (label && CYRILLIC.test(label)) return label;
  if (q.say && CYRILLIC.test(q.say)) return q.say;
  if (q.target && CYRILLIC.test(q.target)) return q.target;
  if (q.prompt && CYRILLIC.test(q.prompt)) return q.prompt;
  return null;
}
