/* Generated by tools/build_cast_art.mjs --ship. Do not edit. The cast's
   avatars, keyed by avatar id, drawn instead of the flat SVG face. */
export const CAST_FACES = {
  "teddy": require("../assets/faces/teddy.png"),
  "nezha": require("../assets/faces/nezha.png"),
  "yarik": require("../assets/faces/yarik.png"),
  "yuri": require("../assets/faces/yuri.png"),
  "belka": require("../assets/faces/belka.png"),
};
