/* Generated by tools/build_images.py — do not edit. Photographs from
   Wikipedia's articles and Wikimedia Commons, free to reuse with credit
   (CC0, public domain, CC BY, CC BY-SA), for the words the units teach,
   keyed on the bare word. CREDITS carries each file's title, author,
   licence and page, shown on the word's entry. */

export const IMAGES = {
  "Москва": require("../assets/img/1013.jpg"),
  "автобус": require("../assets/img/1018.jpg"),
  "автомобиль": require("../assets/img/1020.jpg"),
  "армия": require("../assets/img/1038.jpg"),
  "базар": require("../assets/img/1049.jpg"),
  "банк": require("../assets/img/1054.jpg"),
  "банкомат": require("../assets/img/1055.jpg"),
  "билет": require("../assets/img/1074.jpg"),
  "блин": require("../assets/img/1078.jpg"),
  "блюдо": require("../assets/img/1080.jpg"),
  "болото": require("../assets/img/1089.jpg"),
  "больница": require("../assets/img/1091.jpg"),
  "больной": require("../assets/img/1092.jpg"),
  "бомба": require("../assets/img/1095.jpg"),
  "борщ": require("../assets/img/1098.jpg"),
  "борьба": require("../assets/img/1099.jpg"),
  "ботинок": require("../assets/img/1100.jpg"),
  "брат": require("../assets/img/1102.jpg"),
  "бумага": require("../assets/img/1111.jpg"),
  "бык": require("../assets/img/1117.jpg"),
  "ветер": require("../assets/img/1136.jpg"),
  "ветеран": require("../assets/img/1137.jpg"),
  "вечер": require("../assets/img/1138.jpg"),
  "вирус": require("../assets/img/1152.jpg"),
  "военный": require("../assets/img/1167.jpg"),
  "волк": require("../assets/img/1177.jpg"),
  "волос": require("../assets/img/1180.jpg"),
  "встреча": require("../assets/img/1196.jpg"),
  "выставка": require("../assets/img/1219.jpg"),
  "газета": require("../assets/img/1225.jpg"),
  "галстук": require("../assets/img/1227.jpg"),
  "гора": require("../assets/img/1241.jpg"),
  "город": require("../assets/img/1246.jpg"),
  "гражданин": require("../assets/img/1260.jpg"),
  "гриб": require("../assets/img/1263.jpg"),
  "дача": require("../assets/img/1279.jpg"),
  "дверь": require("../assets/img/1280.jpg"),
  "дворец": require("../assets/img/1284.jpg"),
  "дед": require("../assets/img/1288.jpg"),
  "декабрь": require("../assets/img/1290.jpg"),
  "деревня": require("../assets/img/1301.jpg"),
  "дерево": require("../assets/img/1302.jpg"),
  "деталь": require("../assets/img/1305.jpg"),
  "диплом": require("../assets/img/1314.jpg"),
  "дом": require("../assets/img/1332.jpg"),
  "дорога": require("../assets/img/1335.jpg"),
  "друг": require("../assets/img/1344.jpg"),
  "душ": require("../assets/img/1348.jpg"),
  "женщина": require("../assets/img/1363.jpg"),
  "журнал": require("../assets/img/1369.jpg"),
  "завод": require("../assets/img/1376.jpg"),
  "звезда": require("../assets/img/1403.jpg"),
  "здоровье": require("../assets/img/1410.jpg"),
  "зелёный": require("../assets/img/1412.jpg"),
  "знание": require("../assets/img/1417.jpg"),
  "игрушка": require("../assets/img/1426.jpg"),
  "искусство": require("../assets/img/1449.jpg"),
  "календарь": require("../assets/img/1468.jpg"),
  "камень": require("../assets/img/1469.jpg"),
  "канал": require("../assets/img/1471.jpg"),
  "капитан": require("../assets/img/1473.jpg"),
  "карандаш": require("../assets/img/1474.jpg"),
  "карман": require("../assets/img/1475.jpg"),
  "картошка": require("../assets/img/1479.jpg"),
  "квартира": require("../assets/img/1488.jpg"),
  "китай": require("../assets/img/1491.jpg"),
  "класс": require("../assets/img/1492.jpg"),
  "клетка": require("../assets/img/1496.jpg"),
  "клуб": require("../assets/img/1499.jpg"),
  "книга": require("../assets/img/1501.jpg"),
  "кожа": require("../assets/img/1505.jpg"),
  "коза": require("../assets/img/1506.jpg"),
  "колбаса": require("../assets/img/1508.jpg"),
  "команда": require("../assets/img/1513.jpg"),
  "комната": require("../assets/img/1519.jpg"),
  "компьютер": require("../assets/img/1522.jpg"),
  "концерт": require("../assets/img/1527.jpg"),
  "конь": require("../assets/img/1528.jpg"),
  "корова": require("../assets/img/1531.jpg"),
  "кот": require("../assets/img/1538.jpg"),
  "кофе": require("../assets/img/1540.jpg"),
  "кошелёк": require("../assets/img/1541.jpg"),
  "крыша": require("../assets/img/1560.jpg"),
  "культура": require("../assets/img/1561.jpg"),
  "курица": require("../assets/img/1564.jpg"),
  "куртка": require("../assets/img/1567.jpg"),
  "кухня": require("../assets/img/1568.jpg"),
  "лекарство": require("../assets/img/1574.jpg"),
  "лекция": require("../assets/img/1575.jpg"),
  "лес": require("../assets/img/1576.jpg"),
  "лето": require("../assets/img/1581.jpg"),
  "литература": require("../assets/img/1586.jpg"),
  "лицо": require("../assets/img/1587.jpg"),
  "ложка": require("../assets/img/1593.jpg"),
  "любовь": require("../assets/img/1600.jpg"),
  "медицина": require("../assets/img/1624.jpg"),
  "метро": require("../assets/img/1632.jpg"),
  "мешок": require("../assets/img/1635.jpg"),
  "минута": require("../assets/img/1639.jpg"),
  "мода": require("../assets/img/1646.jpg"),
  "море": require("../assets/img/1661.jpg"),
  "мужчина": require("../assets/img/1670.jpg"),
  "музыка": require("../assets/img/1672.jpg"),
  "музыкант": require("../assets/img/1673.jpg"),
  "мышь": require("../assets/img/1678.jpg"),
  "мясо": require("../assets/img/1680.jpg"),
  "надежда": require("../assets/img/1686.jpg"),
  "наркотик": require("../assets/img/1705.jpg"),
  "насекомое": require("../assets/img/1708.jpg"),
  "ночь": require("../assets/img/1748.jpg"),
  "обед": require("../assets/img/1754.jpg"),
  "обувь": require("../assets/img/1768.jpg"),
  "общество": require("../assets/img/1772.jpg"),
  "окно": require("../assets/img/1788.jpg"),
  "отель": require("../assets/img/1805.jpg"),
  "офис": require("../assets/img/1820.jpg"),
  "офицер": require("../assets/img/1821.jpg"),
  "очередь": require("../assets/img/1827.jpg"),
  "пальто": require("../assets/img/1831.jpg"),
  "папа": require("../assets/img/1836.jpg"),
  "пасха": require("../assets/img/1842.jpg"),
  "пистолет": require("../assets/img/1865.jpg"),
  "пицца": require("../assets/img/1868.jpg"),
  "повреждение": require("../assets/img/1890.jpg"),
  "погода": require("../assets/img/1893.jpg"),
  "подарок": require("../assets/img/1894.jpg"),
  "поезд": require("../assets/img/1906.jpg"),
  "полиция": require("../assets/img/1927.jpg"),
  "полковник": require("../assets/img/1930.jpg"),
  "почта": require("../assets/img/1969.jpg"),
  "пробка": require("../assets/img/2012.jpg"),
  "профессор": require("../assets/img/2039.jpg"),
  "птица": require("../assets/img/2048.jpg"),
  "пуля": require("../assets/img/2050.jpg"),
  "разговор": require("../assets/img/2065.jpg"),
  "ребята": require("../assets/img/2077.jpg"),
  "река": require("../assets/img/2084.jpg"),
  "реклама": require("../assets/img/2085.jpg"),
  "ресторан": require("../assets/img/2091.jpg"),
  "рот": require("../assets/img/2108.jpg"),
  "рубашка": require("../assets/img/2109.jpg"),
  "рука": require("../assets/img/2112.jpg"),
  "ручка": require("../assets/img/2115.jpg"),
  "сад": require("../assets/img/2119.jpg"),
  "салат": require("../assets/img/2121.jpg"),
  "самолёт": require("../assets/img/2123.jpg"),
  "свадьба": require("../assets/img/2128.jpg"),
  "свет": require("../assets/img/2130.jpg"),
  "свинья": require("../assets/img/2136.jpg"),
  "свитер": require("../assets/img/2137.jpg"),
  "сентябрь": require("../assets/img/2156.jpg"),
  "сестра": require("../assets/img/2159.jpg"),
  "скидка": require("../assets/img/2170.jpg"),
  "слон": require("../assets/img/2177.jpg"),
  "смех": require("../assets/img/2184.jpg"),
  "снег": require("../assets/img/2188.jpg"),
  "собака": require("../assets/img/2191.jpg"),
  "солдат": require("../assets/img/2203.jpg"),
  "солнце": require("../assets/img/2205.jpg"),
  "соль": require("../assets/img/2206.jpg"),
  "спорт": require("../assets/img/2227.jpg"),
  "спортсмен": require("../assets/img/2230.jpg"),
  "стол": require("../assets/img/2258.jpg"),
  "столица": require("../assets/img/2261.jpg"),
  "студия": require("../assets/img/2277.jpg"),
  "суд": require("../assets/img/2279.jpg"),
  "суп": require("../assets/img/2284.jpg"),
  "такси": require("../assets/img/2302.jpg"),
  "тарелка": require("../assets/img/2303.jpg"),
  "театр": require("../assets/img/2307.jpg"),
  "телевизор": require("../assets/img/2309.jpg"),
  "телефон": require("../assets/img/2310.jpg"),
  "теннис": require("../assets/img/2315.jpg"),
  "тетрадь": require("../assets/img/2317.jpg"),
  "товар": require("../assets/img/2321.jpg"),
  "тюрьма": require("../assets/img/2345.jpg"),
  "уж": require("../assets/img/2365.jpg"),
  "улица": require("../assets/img/2370.jpg"),
  "университет": require("../assets/img/2374.jpg"),
  "упражнение": require("../assets/img/2377.jpg"),
  "урок": require("../assets/img/2379.jpg"),
  "учёба": require("../assets/img/2399.jpg"),
  "учёный": require("../assets/img/2400.jpg"),
  "фотография": require("../assets/img/2415.jpg"),
  "футбол": require("../assets/img/2419.jpg"),
  "холод": require("../assets/img/2424.jpg"),
  "храм": require("../assets/img/2430.jpg"),
  "чай": require("../assets/img/2441.jpg"),
  "чайник": require("../assets/img/2442.jpg"),
  "чёрный": require("../assets/img/2460.jpg"),
  "школа": require("../assets/img/2467.jpg"),
  "экзамен": require("../assets/img/2475.jpg"),
  "экскурсия": require("../assets/img/2480.jpg"),
  "ягода": require("../assets/img/2496.jpg"),
  "яйцо": require("../assets/img/2499.jpg"),
};

export const FILES = {
 "Москва": "1013.jpg",
 "автобус": "1018.jpg",
 "автомобиль": "1020.jpg",
 "армия": "1038.jpg",
 "базар": "1049.jpg",
 "банк": "1054.jpg",
 "банкомат": "1055.jpg",
 "билет": "1074.jpg",
 "блин": "1078.jpg",
 "блюдо": "1080.jpg",
 "болото": "1089.jpg",
 "больница": "1091.jpg",
 "больной": "1092.jpg",
 "бомба": "1095.jpg",
 "борщ": "1098.jpg",
 "борьба": "1099.jpg",
 "ботинок": "1100.jpg",
 "брат": "1102.jpg",
 "бумага": "1111.jpg",
 "бык": "1117.jpg",
 "ветер": "1136.jpg",
 "ветеран": "1137.jpg",
 "вечер": "1138.jpg",
 "вирус": "1152.jpg",
 "военный": "1167.jpg",
 "волк": "1177.jpg",
 "волос": "1180.jpg",
 "встреча": "1196.jpg",
 "выставка": "1219.jpg",
 "газета": "1225.jpg",
 "галстук": "1227.jpg",
 "гора": "1241.jpg",
 "город": "1246.jpg",
 "гражданин": "1260.jpg",
 "гриб": "1263.jpg",
 "дача": "1279.jpg",
 "дверь": "1280.jpg",
 "дворец": "1284.jpg",
 "дед": "1288.jpg",
 "декабрь": "1290.jpg",
 "деревня": "1301.jpg",
 "дерево": "1302.jpg",
 "деталь": "1305.jpg",
 "диплом": "1314.jpg",
 "дом": "1332.jpg",
 "дорога": "1335.jpg",
 "друг": "1344.jpg",
 "душ": "1348.jpg",
 "женщина": "1363.jpg",
 "журнал": "1369.jpg",
 "завод": "1376.jpg",
 "звезда": "1403.jpg",
 "здоровье": "1410.jpg",
 "зелёный": "1412.jpg",
 "знание": "1417.jpg",
 "игрушка": "1426.jpg",
 "искусство": "1449.jpg",
 "календарь": "1468.jpg",
 "камень": "1469.jpg",
 "канал": "1471.jpg",
 "капитан": "1473.jpg",
 "карандаш": "1474.jpg",
 "карман": "1475.jpg",
 "картошка": "1479.jpg",
 "квартира": "1488.jpg",
 "китай": "1491.jpg",
 "класс": "1492.jpg",
 "клетка": "1496.jpg",
 "клуб": "1499.jpg",
 "книга": "1501.jpg",
 "кожа": "1505.jpg",
 "коза": "1506.jpg",
 "колбаса": "1508.jpg",
 "команда": "1513.jpg",
 "комната": "1519.jpg",
 "компьютер": "1522.jpg",
 "концерт": "1527.jpg",
 "конь": "1528.jpg",
 "корова": "1531.jpg",
 "кот": "1538.jpg",
 "кофе": "1540.jpg",
 "кошелёк": "1541.jpg",
 "крыша": "1560.jpg",
 "культура": "1561.jpg",
 "курица": "1564.jpg",
 "куртка": "1567.jpg",
 "кухня": "1568.jpg",
 "лекарство": "1574.jpg",
 "лекция": "1575.jpg",
 "лес": "1576.jpg",
 "лето": "1581.jpg",
 "литература": "1586.jpg",
 "лицо": "1587.jpg",
 "ложка": "1593.jpg",
 "любовь": "1600.jpg",
 "медицина": "1624.jpg",
 "метро": "1632.jpg",
 "мешок": "1635.jpg",
 "минута": "1639.jpg",
 "мода": "1646.jpg",
 "море": "1661.jpg",
 "мужчина": "1670.jpg",
 "музыка": "1672.jpg",
 "музыкант": "1673.jpg",
 "мышь": "1678.jpg",
 "мясо": "1680.jpg",
 "надежда": "1686.jpg",
 "наркотик": "1705.jpg",
 "насекомое": "1708.jpg",
 "ночь": "1748.jpg",
 "обед": "1754.jpg",
 "обувь": "1768.jpg",
 "общество": "1772.jpg",
 "окно": "1788.jpg",
 "отель": "1805.jpg",
 "офис": "1820.jpg",
 "офицер": "1821.jpg",
 "очередь": "1827.jpg",
 "пальто": "1831.jpg",
 "папа": "1836.jpg",
 "пасха": "1842.jpg",
 "пистолет": "1865.jpg",
 "пицца": "1868.jpg",
 "повреждение": "1890.jpg",
 "погода": "1893.jpg",
 "подарок": "1894.jpg",
 "поезд": "1906.jpg",
 "полиция": "1927.jpg",
 "полковник": "1930.jpg",
 "почта": "1969.jpg",
 "пробка": "2012.jpg",
 "профессор": "2039.jpg",
 "птица": "2048.jpg",
 "пуля": "2050.jpg",
 "разговор": "2065.jpg",
 "ребята": "2077.jpg",
 "река": "2084.jpg",
 "реклама": "2085.jpg",
 "ресторан": "2091.jpg",
 "рот": "2108.jpg",
 "рубашка": "2109.jpg",
 "рука": "2112.jpg",
 "ручка": "2115.jpg",
 "сад": "2119.jpg",
 "салат": "2121.jpg",
 "самолёт": "2123.jpg",
 "свадьба": "2128.jpg",
 "свет": "2130.jpg",
 "свинья": "2136.jpg",
 "свитер": "2137.jpg",
 "сентябрь": "2156.jpg",
 "сестра": "2159.jpg",
 "скидка": "2170.jpg",
 "слон": "2177.jpg",
 "смех": "2184.jpg",
 "снег": "2188.jpg",
 "собака": "2191.jpg",
 "солдат": "2203.jpg",
 "солнце": "2205.jpg",
 "соль": "2206.jpg",
 "спорт": "2227.jpg",
 "спортсмен": "2230.jpg",
 "стол": "2258.jpg",
 "столица": "2261.jpg",
 "студия": "2277.jpg",
 "суд": "2279.jpg",
 "суп": "2284.jpg",
 "такси": "2302.jpg",
 "тарелка": "2303.jpg",
 "театр": "2307.jpg",
 "телевизор": "2309.jpg",
 "телефон": "2310.jpg",
 "теннис": "2315.jpg",
 "тетрадь": "2317.jpg",
 "товар": "2321.jpg",
 "тюрьма": "2345.jpg",
 "уж": "2365.jpg",
 "улица": "2370.jpg",
 "университет": "2374.jpg",
 "упражнение": "2377.jpg",
 "урок": "2379.jpg",
 "учёба": "2399.jpg",
 "учёный": "2400.jpg",
 "фотография": "2415.jpg",
 "футбол": "2419.jpg",
 "холод": "2424.jpg",
 "храм": "2430.jpg",
 "чай": "2441.jpg",
 "чайник": "2442.jpg",
 "чёрный": "2460.jpg",
 "школа": "2467.jpg",
 "экзамен": "2475.jpg",
 "экскурсия": "2480.jpg",
 "ягода": "2496.jpg",
 "яйцо": "2499.jpg"
};

export const CREDITS = {
 "Москва": {
  "t": "Moscow City landscape july 2008.jpg",
  "a": "Dmitry A. Mottl",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Moscow_City_landscape_july_2008.jpg"
 },
 "автобус": {
  "t": "MAZ-103 in Minsk 01.jpg",
  "a": "Redline",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:MAZ-103_in_Minsk_01.jpg"
 },
 "автомобиль": {
  "t": "2005 Toyota Corolla 1.4 T3.jpg",
  "a": "Jayme Kimball",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2005_Toyota_Corolla_1.4_T3.jpg"
 },
 "армия": {
  "t": "Combined Arms Training.jpg",
  "a": "Sgt. Anthony Jones",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Combined_Arms_Training.jpg"
 },
 "базар": {
  "t": "Turkey (68742801).jpeg",
  "a": "Antonio Cristofaro",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Turkey_(68742801).jpeg"
 },
 "банк": {
  "t": "Barclays Bank, West Kirby.jpg",
  "a": "Rodhullandemu",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Barclays_Bank,_West_Kirby.jpg"
 },
 "банкомат": {
  "t": "ATMs in Kashirskaya Plaza (12.10.2024).jpg",
  "a": "Brateevsky",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:ATMs_in_Kashirskaya_Plaza_(12.10.2024).jpg"
 },
 "билет": {
  "t": "Ticket (unseparated) Kurkino-Berchtesgaden.JPG",
  "a": "Andreas -horn- Hornig",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Ticket_(unseparated)_Kurkino-Berchtesgaden.JPG"
 },
 "блин": {
  "t": "Blini Tanya.jpg",
  "a": "Изначально этот файл был загружен участником Hugo.arg из литовский Википедия",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Blini_Tanya.jpg"
 },
 "блюдо": {
  "t": "Lunch dish (pumpkin sauce, potatoes and chicken steak).jpg",
  "a": "Petar Milošević",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lunch_dish_(pumpkin_sauce,_potatoes_and_chicken_steak).jpg"
 },
 "болото": {
  "t": "Болото Селигер.JPG",
  "a": "Cartwheel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%BE%D0%BB%D0%BE%D1%82%D0%BE_%D0%A1%D0%B5%D0%BB%D0%B8%D0%B3%D0%B5%D1%80.JPG"
 },
 "больница": {
  "t": "Лечебно-диагностический комплекс ИКБ № 1 (Москва) 20.jpg",
  "a": "М. Мишина. Пресс-служба Мэра и Правительства Москвы",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B5%D1%87%D0%B5%D0%B1%D0%BD%D0%BE-%D0%B4%D0%B8%D0%B0%D0%B3%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81_%D0%98%D0%9A%D0%91_%E2%84%96_1_(%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0)_20.jpg"
 },
 "больной": {
  "t": "Hallways filled with patients.jpg",
  "a": "meg and rahul",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hallways_filled_with_patients.jpg"
 },
 "бомба": {
  "t": "MOAB bomb.jpg",
  "a": "U.S. Department of Defense photograph",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:MOAB_bomb.jpg"
 },
 "борщ": {
  "t": "Borscht with bread.jpg",
  "a": "Juerg Vollmer from Zürich, Schweiz",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Borscht_with_bread.jpg"
 },
 "борьба": {
  "t": "0432-DremielLiftsRulon.jpg",
  "a": "Tim Hipps",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:0432-DremielLiftsRulon.jpg"
 },
 "ботинок": {
  "t": "Bergschuhe hg.jpg",
  "a": "Hgrobe",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Bergschuhe_hg.jpg"
 },
 "брат": {
  "t": "Two brothers together in Bihar, India.jpg",
  "a": "Saddam19",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Two_brothers_together_in_Bihar,_India.jpg"
 },
 "бумага": {
  "t": "FileStack retouched.jpg",
  "a": "Niklas Bildhauer  (who also is User gerolsteiner91.",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:FileStack_retouched.jpg"
 },
 "бык": {
  "t": "A Friesian Bull, Llandeilo Graban - geograph.org.uk - 579885.jpg",
  "a": "Philip Halling",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:A_Friesian_Bull,_Llandeilo_Graban_-_geograph.org.uk_-_579885.jpg"
 },
 "ветер": {
  "t": "2017-08-26-Windraeder Fehmarn-4301.jpg",
  "a": "Superbass",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2017-08-26-Windraeder_Fehmarn-4301.jpg"
 },
 "ветеран": {
  "t": "Sydney 2015 Anzac Day march (17119683648).jpg",
  "a": "Yupeng Wu from sydney, Australia",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sydney_2015_Anzac_Day_march_(17119683648).jpg"
 },
 "вечер": {
  "t": "Evening in Parambikkulam, Kerala, India.jpg",
  "a": "Augustus Binu/ www.dreamsparrow.net/ facebook",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Evening_in_Parambikkulam,_Kerala,_India.jpg"
 },
 "вирус": {
  "t": "Rotavirus Reconstruction.jpg",
  "a": "",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Rotavirus_Reconstruction.jpg"
 },
 "военный": {
  "t": "4thTankDivisionOpenDay17p2-06.jpg",
  "a": "Vitaly V. Kuzmin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:4thTankDivisionOpenDay17p2-06.jpg"
 },
 "волк": {
  "t": "Eurasian wolf 2.jpg",
  "a": "User:Mas3cf",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Eurasian_wolf_2.jpg"
 },
 "волос": {
  "t": "Blond hair going gray 01.jpg",
  "a": "Kritzolina",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Blond_hair_going_gray_01.jpg"
 },
 "встреча": {
  "t": "Sitzung von Wiki Loves Broadcast im Kontor Hamburg.jpg",
  "a": "Wikiolo",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sitzung_von_Wiki_Loves_Broadcast_im_Kontor_Hamburg.jpg"
 },
 "выставка": {
  "t": "FUTURES exhibition sign.jpg",
  "a": "APK",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:FUTURES_exhibition_sign.jpg"
 },
 "газета": {
  "t": "An old man in newsagent's shop, Paris September 2011.jpg",
  "a": "Florian Plag from Bretten",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:An_old_man_in_newsagent%27s_shop,_Paris_September_2011.jpg"
 },
 "галстук": {
  "t": "Memphis tie 1A.JPG",
  "a": "Affärside",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Memphis_tie_1A.JPG"
 },
 "гора": {
  "t": "Khor Virap.jpg",
  "a": "Maks Karochkin",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Khor_Virap.jpg"
 },
 "город": {
  "t": "Turkish.town.cesme.jpg",
  "a": "OscarKosy",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Turkish.town.cesme.jpg"
 },
 "гражданин": {
  "t": "Peter Dutton at Australian Citizenship Ceremony, 2017.jpg",
  "a": "Commonwealth of Australia",
  "l": "CC BY 3.0 au",
  "u": "https://commons.wikimedia.org/wiki/File:Peter_Dutton_at_Australian_Citizenship_Ceremony,_2017.jpg"
 },
 "гриб": {
  "t": "Sparrige Schüppling (Pholiota squarrosa).jpg",
  "a": "Holger Krisp",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sparrige_Sch%C3%BCppling_(Pholiota_squarrosa).jpg"
 },
 "дача": {
  "t": "Dacha - panoramio (1).jpg",
  "a": "Figure",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Dacha_-_panoramio_(1).jpg"
 },
 "дверь": {
  "t": "Bronze door, Basilica di San Giovanni, 2013.jpg",
  "a": "Szilas",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bronze_door,_Basilica_di_San_Giovanni,_2013.jpg"
 },
 "дворец": {
  "t": "Palacio Real de Madrid Julio 2016 (cropped).jpg",
  "a": "Tim Adams",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Palacio_Real_de_Madrid_Julio_2016_(cropped).jpg"
 },
 "дед": {
  "t": "Grandfather rus.jpg",
  "a": "Bogdanov-62",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Grandfather_rus.jpg"
 },
 "декабрь": {
  "t": "Fanny udde December 2021 01.jpg",
  "a": "Arild Vågen",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fanny_udde_December_2021_01.jpg"
 },
 "деревня": {
  "t": "DSC00029 Java Little Sundanais Traditional Village Kampung Naga (6219569245).jpg",
  "a": "DANIEL JULIE from Paris, France",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:DSC00029_Java_Little_Sundanais_Traditional_Village_Kampung_Naga_(6219569245).jpg"
 },
 "дерево": {
  "t": "Sequoiadendron giganteum at Kenilworth Castle.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Jdfo",
  "l": "CC BY 1.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sequoiadendron_giganteum_at_Kenilworth_Castle.jpg"
 },
 "деталь": {
  "t": "Детали 1.jpg",
  "a": "Schekinov Alexey Victorovich",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%B5%D1%82%D0%B0%D0%BB%D0%B8_1.jpg"
 },
 "диплом": {
  "t": "SheepskinDiploma.jpg",
  "a": "Millermz at English Wikipedia",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:SheepskinDiploma.jpg"
 },
 "дом": {
  "t": "Katsura Imperial Villa in Spring.jpg",
  "a": "John Chang",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Katsura_Imperial_Villa_in_Spring.jpg"
 },
 "дорога": {
  "t": "Дорога в холмах.jpg",
  "a": "Pat_World",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%B2_%D1%85%D0%BE%D0%BB%D0%BC%D0%B0%D1%85.jpg"
 },
 "друг": {
  "t": "Childhood friends at a carnival.jpg",
  "a": "Squelle",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Childhood_friends_at_a_carnival.jpg"
 },
 "душ": {
  "t": "Showerhead.JPG",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Showerhead.JPG"
 },
 "женщина": {
  "t": "Woman at Lover's Bridge Tanjung Sepat (cropped).jpg",
  "a": "John Ragai",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Woman_at_Lover%27s_Bridge_Tanjung_Sepat_(cropped).jpg"
 },
 "журнал": {
  "t": "German Printmagazines.jpg",
  "a": "Rüdiger Müller",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:German_Printmagazines.jpg"
 },
 "завод": {
  "t": "Cromford Mill 2008.jpg",
  "a": "craig carter from DERBYSHIRE, UK",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Cromford_Mill_2008.jpg"
 },
 "звезда": {
  "t": "Звёздное небо в Альпах.jpg",
  "a": "Loris Sponda",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%97%D0%B2%D1%91%D0%B7%D0%B4%D0%BD%D0%BE%D0%B5_%D0%BD%D0%B5%D0%B1%D0%BE_%D0%B2_%D0%90%D0%BB%D1%8C%D0%BF%D0%B0%D1%85.jpg"
 },
 "здоровье": {
  "t": "Pilates 01.jpg",
  "a": "J. Vílchez",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Pilates_01.jpg"
 },
 "зелёный": {
  "t": "Champ de blé Côte-d'Or Bourgogne avril 2014.jpg",
  "a": "Myrabella",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Champ_de_bl%C3%A9_C%C3%B4te-d%27Or_Bourgogne_avril_2014.jpg"
 },
 "знание": {
  "t": "Latin dictionary.jpg",
  "a": "Dr. Marcus Gossler",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Latin_dictionary.jpg"
 },
 "игрушка": {
  "t": "Slinky rainbow.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Enoc",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Slinky_rainbow.jpg"
 },
 "искусство": {
  "t": "Art-portrait-collage 2.jpg",
  "a": "User:Husky and h3m3ls, Mischa de Muynck and Niels",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Art-portrait-collage_2.jpg"
 },
 "календарь": {
  "t": "Kalender Indonesia.jpg",
  "a": "Rantemario",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kalender_Indonesia.jpg"
 },
 "камень": {
  "t": "Two-parts stone nikogda takih ne videl vot.JPG",
  "a": "Sergei Frolov, http://sfrolov.livejournal.com",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Two-parts_stone_nikogda_takih_ne_videl_vot.JPG"
 },
 "канал": {
  "t": "Alter Strom.jpg",
  "a": "Martin Künzel, Berlin – Edited by Fir0002",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Alter_Strom.jpg"
 },
 "капитан": {
  "t": "Captain on ship.jpg",
  "a": "Hillebrand Steve, U.S. Fish and Wildlife Service",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Captain_on_ship.jpg"
 },
 "карандаш": {
  "t": "Colouring pencils.jpg",
  "a": "MichaelMaggs",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Colouring_pencils.jpg"
 },
 "карман": {
  "t": "Black Jeans with Zipper Pocket Detailing (15470033547).jpg",
  "a": "Jamie",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Black_Jeans_with_Zipper_Pocket_Detailing_(15470033547).jpg"
 },
 "картошка": {
  "t": "Patates.jpg",
  "a": "Scott Bauer, USDA ARS",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Patates.jpg"
 },
 "квартира": {
  "t": "Housing and Development Board flats near Woodlands Avenue 7, Singapore.jpg",
  "a": "Slivester (Slivester Nuenenorl).",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Housing_and_Development_Board_flats_near_Woodlands_Avenue_7,_Singapore.jpg"
 },
 "китай": {
  "t": "Pudong Shanghai November 2017 panorama.jpg",
  "a": "King of Hearts",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Pudong_Shanghai_November_2017_panorama.jpg"
 },
 "класс": {
  "t": "Room-education-classroom-children-library-students-1237486.jpg",
  "a": "https://pxhere.com/es/photo/1237486",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Room-education-classroom-children-library-students-1237486.jpg"
 },
 "клетка": {
  "t": "A caged Alexandrine parrot at a household in West Bengal, India photographed on November 29, 2024.jpg",
  "a": "Billjones94",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:A_caged_Alexandrine_parrot_at_a_household_in_West_Bengal,_India_photographed_on_November_29,_2024.jpg"
 },
 "клуб": {
  "t": "Savile Club New Bar 2.JPG",
  "a": "Creator:Savile Club",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Savile_Club_New_Bar_2.JPG"
 },
 "книга": {
  "t": "Gutenberg Bible, Lenox Copy, New York Public Library, 2009. Pic 01.jpg",
  "a": "NYC Wanderer (Kevin Eng)",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Gutenberg_Bible,_Lenox_Copy,_New_York_Public_Library,_2009._Pic_01.jpg"
 },
 "кожа": {
  "t": "Elephant skin (3689577529).jpg",
  "a": "Greg Willis from Denver, CO, usa",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Elephant_skin_(3689577529).jpg"
 },
 "коза": {
  "t": "Hausziege 04.jpg",
  "a": "Kuebi = Armin Kübelbeck",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hausziege_04.jpg"
 },
 "колбаса": {
  "t": "Kielbasa7.jpg",
  "a": "Mariuszjbie",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kielbasa7.jpg"
 },
 "команда": {
  "t": "Rugby union scrummage.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Rugby_union_scrummage.jpg"
 },
 "комната": {
  "t": "D.A. Sturdza House, Bucharest (Romania) 9.jpg",
  "a": "Neoclassicism Enthusiast",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:D.A._Sturdza_House,_Bucharest_(Romania)_9.jpg"
 },
 "компьютер": {
  "t": "2014 Modding komputera 01.jpg",
  "a": "Halicki",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2014_Modding_komputera_01.jpg"
 },
 "концерт": {
  "t": "Playtime Festival 2024.jpg",
  "a": "Chongkian",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Playtime_Festival_2024.jpg"
 },
 "конь": {
  "t": "Equus species.jpg",
  "a": "LittleJerry; JPG by uploader",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Equus_species.jpg"
 },
 "корова": {
  "t": "Cow female black white.jpg",
  "a": "Keith Weller/USDA",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Cow_female_black_white.jpg"
 },
 "кот": {
  "t": "Siam lilacpoint.jpg",
  "a": "Karin Langner-Bahmann, upload von Martin Bahmann",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Siam_lilacpoint.jpg"
 },
 "кофе": {
  "t": "A small cup of coffee.JPG",
  "a": "Julius Schorzman",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:A_small_cup_of_coffee.JPG"
 },
 "кошелёк": {
  "t": "WalletMpegMan.jpg",
  "a": "Изначально этот файл был загружен участником TheArmadillo из английский Википеди",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:WalletMpegMan.jpg"
 },
 "крыша": {
  "t": "Tak - Ystad-2022.jpg",
  "a": "Foto: Jonn Leffmann",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Tak_-_Ystad-2022.jpg"
 },
 "культура": {
  "t": "9 Bisonte Magdaleniense polícromo.jpg",
  "a": "Museo de Altamira y D. Rodríguez",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg"
 },
 "курица": {
  "t": "Male and female chicken sitting together.jpg",
  "a": "Andrei Niemimäki из Турку, Финляндия",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Male_and_female_chicken_sitting_together.jpg"
 },
 "куртка": {
  "t": "Jack Wolfskin, OutDoor 2018, Friedrichshafen (1X7A0421).jpg",
  "a": "Matti Blume",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Jack_Wolfskin,_OutDoor_2018,_Friedrichshafen_(1X7A0421).jpg"
 },
 "кухня": {
  "t": "Alno Kuechenzeile 1980er Jahre.jpg",
  "a": "Mabit1",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Alno_Kuechenzeile_1980er_Jahre.jpg"
 },
 "лекарство": {
  "t": "Medikamente.jpg",
  "a": "Würfel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Medikamente.jpg"
 },
 "лекция": {
  "t": "ADFA Lecture Theatres.jpg",
  "a": "Kurt Barnett",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:ADFA_Lecture_Theatres.jpg"
 },
 "лес": {
  "t": "Lagodekhi National Park. Forest.jpg",
  "a": "Aleksey Muhranoff",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lagodekhi_National_Park._Forest.jpg"
 },
 "лето": {
  "t": "Field Hamois Belgium Luc Viatour.jpg",
  "a": "Luc Viatour",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Field_Hamois_Belgium_Luc_Viatour.jpg"
 },
 "литература": {
  "t": "Bibliothèque de l'Assemblée Nationale (Lunon).jpg",
  "a": "Baptiste ROUSSEL",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Biblioth%C3%A8que_de_l%27Assembl%C3%A9e_Nationale_(Lunon).jpg"
 },
 "лицо": {
  "t": "Human faces.jpg",
  "a": "Autisticeditor 20",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Human_faces.jpg"
 },
 "ложка": {
  "t": "Esslöffel und Teelöffel.JPG",
  "a": "Lesekreis",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Essl%C3%B6ffel_und_Teel%C3%B6ffel.JPG"
 },
 "любовь": {
  "t": "Sri Lankan woman and child.jpg",
  "a": "Steve Evans from India and USA",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sri_Lankan_woman_and_child.jpg"
 },
 "медицина": {
  "t": "Changing lives for girls and women every week (12330467294).jpg",
  "a": "Jessica Lea of DFID - UK Department for International Development",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Changing_lives_for_girls_and_women_every_week_(12330467294).jpg"
 },
 "метро": {
  "t": "Northbound Link train at Othello Station (31003193486).jpg",
  "a": "SounderBruce from Seattle, United States",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Northbound_Link_train_at_Othello_Station_(31003193486).jpg"
 },
 "мешок": {
  "t": "Hemp-sack, Asabukuro, Japan.jpg",
  "a": "katorisi",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Hemp-sack,_Asabukuro,_Japan.jpg"
 },
 "минута": {
  "t": "La minute (315630347).jpg",
  "a": "Fanch from Paris, France",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:La_minute_(315630347).jpg"
 },
 "мода": {
  "t": "Siegel & Stockman. The Brandery Winter Edition 2010.jpg",
  "a": "thebrandery",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Siegel_%26_Stockman._The_Brandery_Winter_Edition_2010.jpg"
 },
 "море": {
  "t": "POL 2007 08 04 Jaroslawiec zachodniopomorskie 02.JPG",
  "a": "Alina Zienowicz Ala z",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:POL_2007_08_04_Jaroslawiec_zachodniopomorskie_02.JPG"
 },
 "мужчина": {
  "t": "Представители мужского пола.jpg",
  "a": "Ekaterina Stakgrunvald",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9F%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D0%B8_%D0%BC%D1%83%D0%B6%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%BF%D0%BE%D0%BB%D0%B0.jpg"
 },
 "музыка": {
  "t": "Trompette - corps.JPG",
  "a": "Eusebius",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Trompette_-_corps.JPG"
 },
 "музыкант": {
  "t": "Musician Playing Ravanhatta at Mehrangarh, Rajasthan, India.jpg",
  "a": "Harshil Mehta",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Musician_Playing_Ravanhatta_at_Mehrangarh,_Rajasthan,_India.jpg"
 },
 "мышь": {
  "t": "Apodemus sylvaticus bosmuis.jpg",
  "a": "Rasbak",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Apodemus_sylvaticus_bosmuis.jpg"
 },
 "мясо": {
  "t": "Pan frying sausages.jpg",
  "a": "Rene Ehrhardt",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Pan_frying_sausages.jpg"
 },
 "надежда": {
  "t": "Hopeful.jpg",
  "a": "Ahill34",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hopeful.jpg"
 },
 "наркотик": {
  "t": "Bayer Heroin bottle.jpg",
  "a": "Mpv_51 at English Wikipedia",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bayer_Heroin_bottle.jpg"
 },
 "насекомое": {
  "t": "Insecta Diversity.jpg",
  "a": "See his respective owners",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Insecta_Diversity.jpg"
 },
 "ночь": {
  "t": "Парк ночью в Денизли.jpg",
  "a": "Amin Diary",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B0%D1%80%D0%BA_%D0%BD%D0%BE%D1%87%D1%8C%D1%8E_%D0%B2_%D0%94%D0%B5%D0%BD%D0%B8%D0%B7%D0%BB%D0%B8.jpg"
 },
 "обед": {
  "t": "Filet de bœuf.jpg",
  "a": "Ɱ",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Filet_de_b%C5%93uf.jpg"
 },
 "обувь": {
  "t": "King Street Sneak.JPG",
  "a": "Samuelchoong",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:King_Street_Sneak.JPG"
 },
 "общество": {
  "t": "Lao Mangkong family eats together (square).JPG",
  "a": "BigBrotherMouse",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lao_Mangkong_family_eats_together_(square).JPG"
 },
 "окно": {
  "t": "Վերին կամարազարդ.JPG",
  "a": "XenonX88",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D5%8E%D5%A5%D6%80%D5%AB%D5%B6_%D5%AF%D5%A1%D5%B4%D5%A1%D6%80%D5%A1%D5%A6%D5%A1%D6%80%D5%A4.JPG"
 },
 "отель": {
  "t": "Livorno - Hotel Palazzo - 2025-09-29 20-09-38 001.jpg",
  "a": "Terragio67",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Livorno_-_Hotel_Palazzo_-_2025-09-29_20-09-38_001.jpg"
 },
 "офис": {
  "t": "Deutsche-Bank-Frankfurt-am-Main.jpg",
  "a": "Raimond Spekking",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Deutsche-Bank-Frankfurt-am-Main.jpg"
 },
 "офицер": {
  "t": "Royal Military Academy Sandhurst inspection of new Colours, June 2005.jpg",
  "a": "Charles J Sharp",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Royal_Military_Academy_Sandhurst_inspection_of_new_Colours,_June_2005.jpg"
 },
 "очередь": {
  "t": "Tai Po Voting queue-20200712.jpg",
  "a": "Studio Incendo",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Tai_Po_Voting_queue-20200712.jpg"
 },
 "пальто": {
  "t": "Covert Coat.jpg",
  "a": "Toxophilus",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Covert_Coat.jpg"
 },
 "папа": {
  "t": "Father's love (cropped).jpg",
  "a": "Hripsime Poghosyan",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Father%27s_love_(cropped).jpg"
 },
 "пасха": {
  "t": "Paskha2.jpg",
  "a": "Mitrius",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Paskha2.jpg"
 },
 "пистолет": {
  "t": "Pistolet makarova pm travmatik com by-sa.jpg",
  "a": "Stanislav S. Yanchenko",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Pistolet_makarova_pm_travmatik_com_by-sa.jpg"
 },
 "пицца": {
  "t": "Eq it-na pizza-margherita sep2005 sml.jpg",
  "a": "Valerio Capello из английский Википедия",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Eq_it-na_pizza-margherita_sep2005_sml.jpg"
 },
 "повреждение": {
  "t": "Lokomotiva 162 011-1 po nehodě.jpg",
  "a": "Michal Rattman",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lokomotiva_162_011-1_po_nehod%C4%9B.jpg"
 },
 "погода": {
  "t": "Stormclouds.jpg",
  "a": "Lipton sale из английский Википедия",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Stormclouds.jpg"
 },
 "подарок": {
  "t": "Gifts xmas.jpg",
  "a": "Kelvin Kay, en:user:kkmd",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Gifts_xmas.jpg"
 },
 "поезд": {
  "t": "PRR 33164.jpg",
  "a": "Niagara",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:PRR_33164.jpg"
 },
 "полиция": {
  "t": "HH Polizeihauptmeister MZ.jpg",
  "a": "Daniel Schwen",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:HH_Polizeihauptmeister_MZ.jpg"
 },
 "полковник": {
  "t": "VladikavkazMP-2017-11.jpg",
  "a": "Екатерина Смола",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:VladikavkazMP-2017-11.jpg"
 },
 "почта": {
  "t": "HK Postman Collect Letters.JPG",
  "a": "Chong Fat",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:HK_Postman_Collect_Letters.JPG"
 },
 "пробка": {
  "t": "1-Arraiolos-0050.jpg",
  "a": "User:Sallyofmayflower",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:1-Arraiolos-0050.jpg"
 },
 "профессор": {
  "t": "Professor and architecture students.jpg",
  "a": "Sverre Flack",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Professor_and_architecture_students.jpg"
 },
 "птица": {
  "t": "Kleiber Flug.jpg",
  "a": "C. Robiller / naturlichter.de (Hyla meridionalis)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kleiber_Flug.jpg"
 },
 "пуля": {
  "t": "GP11 coupe.JPG",
  "a": "Bouterolle",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:GP11_coupe.JPG"
 },
 "разговор": {
  "t": "वार्तालाप.jpg",
  "a": "Surenders25",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%E0%A4%B5%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%BE%E0%A4%B2%E0%A4%BE%E0%A4%AA.jpg"
 },
 "ребята": {
  "t": "Smiling little boy of Laos.jpg",
  "a": "Basile Morin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Smiling_little_boy_of_Laos.jpg"
 },
 "река": {
  "t": "River RP.jpg",
  "a": "Jlwad",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:River_RP.jpg"
 },
 "реклама": {
  "t": "1 times square night 2013.jpg",
  "a": "chensiyuan",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:1_times_square_night_2013.jpg"
 },
 "ресторан": {
  "t": "AntoinesDiningRoom8Oct07A.jpg",
  "a": "Infrogmation of New Orleans",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:AntoinesDiningRoom8Oct07A.jpg"
 },
 "рот": {
  "t": "Lion Showing off His Mouth (21454262492).jpg",
  "a": "Eric Kilby from Somerville, MA, USA",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lion_Showing_off_His_Mouth_(21454262492).jpg"
 },
 "рубашка": {
  "t": "Blue Business Shirt.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Blue_Business_Shirt.jpg"
 },
 "рука": {
  "t": "Две острые палочки, сложным образом зажатые в руке человека.JPG",
  "a": "Weldis",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%B2%D0%B5_%D0%BE%D1%81%D1%82%D1%80%D1%8B%D0%B5_%D0%BF%D0%B0%D0%BB%D0%BE%D1%87%D0%BA%D0%B8,_%D1%81%D0%BB%D0%BE%D0%B6%D0%BD%D1%8B%D0%BC_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%BC_%D0%B7%D0%B0%D0%B6%D0%B0%D1%82%D1%8B%D0%B5_%D0%B2_%D1%80%D1%83%D0%BA%D0%B5_%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA%D0%B0.JPG"
 },
 "ручка": {
  "t": "Qalam2.jpg",
  "a": "No machine-readable author provided. Baba66 assumed (based on copyright claims).",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Qalam2.jpg"
 },
 "сад": {
  "t": "Brooklyn Botanic Garden New York May 2015 010.jpg",
  "a": "King of Hearts",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Brooklyn_Botanic_Garden_New_York_May_2015_010.jpg"
 },
 "салат": {
  "t": "Kaspressknödel mit Salat.jpg",
  "a": "Kritzolina",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kaspresskn%C3%B6del_mit_Salat.jpg"
 },
 "самолёт": {
  "t": "Ильюшин Ил-96 74393202018, Москва - Внуково RP20591.jpg",
  "a": "Павел Аджигильдяев",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%98%D0%BB%D1%8C%D1%8E%D1%88%D0%B8%D0%BD_%D0%98%D0%BB-96_74393202018,_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0_-_%D0%92%D0%BD%D1%83%D0%BA%D0%BE%D0%B2%D0%BE_RP20591.jpg"
 },
 "свадьба": {
  "t": "Hindu wedding rituals b (cropped).jpg",
  "a": "Will",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hindu_wedding_rituals_b_(cropped).jpg"
 },
 "свет": {
  "t": "Prism flat rainbow (cropped).jpg",
  "a": "User:Kelvinsong",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Prism_flat_rainbow_(cropped).jpg"
 },
 "свинья": {
  "t": "Поросята (гибридные).jpg",
  "a": "Собственная работа",
  "l": "CC BY 3.0",
  "u": "https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:%D0%9F%D0%BE%D1%80%D0%BE%D1%81%D1%8F%D1%82%D0%B0_(%D0%B3%D0%B8%D0%B1%D1%80%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5).jpg"
 },
 "свитер": {
  "t": "Jersei-coll-alt.jpg",
  "a": "Joan Rocaguinard",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Jersei-coll-alt.jpg"
 },
 "сентябрь": {
  "t": "September.jpg",
  "a": "Струнин В.С",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:September.jpg"
 },
 "сестра": {
  "t": "Two sisters in Bihar, India.jpg",
  "a": "Saddam19",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Two_sisters_in_Bihar,_India.jpg"
 },
 "скидка": {
  "t": "Sales promotion 2015 0001.JPG",
  "a": "Henning Schlottmann (User:H-stt)",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sales_promotion_2015_0001.JPG"
 },
 "слон": {
  "t": "Elephant Diversity.jpg",
  "a": "Yathin S Krishnappa (File:Elephas maximus (Bandipur).jpg)\nThomas Breuer (File:Lo",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Elephant_Diversity.jpg"
 },
 "смех": {
  "t": "Girl eating paint.jpg",
  "a": "Schekinov Alexey Victorovich",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Girl_eating_paint.jpg"
 },
 "снег": {
  "t": "Fresh snow.JPG",
  "a": "Wuhazet - Henryk Żychowski",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fresh_snow.JPG"
 },
 "собака": {
  "t": "Huskiesatrest.jpg",
  "a": "M. Rehemtulla",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Huskiesatrest.jpg"
 },
 "солдат": {
  "t": "Chinese soldier on Tienanmen Square.jpg",
  "a": "Luo Shaoyang from Beijing, China",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Chinese_soldier_on_Tienanmen_Square.jpg"
 },
 "солнце": {
  "t": "The Sun in white light.jpg",
  "a": "Matúš Motlo",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:The_Sun_in_white_light.jpg"
 },
 "соль": {
  "t": "TableSaltRussia.jpg",
  "a": "Leonid Dzhepko / Л.П. Джепко",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:TableSaltRussia.jpg"
 },
 "спорт": {
  "t": "20180922 UCI Road World Championships Innsbruck Team AG2R La Mondiale 850 7022.jpg",
  "a": "Granada",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:20180922_UCI_Road_World_Championships_Innsbruck_Team_AG2R_La_Mondiale_850_7022.jpg"
 },
 "спортсмен": {
  "t": "Osaka07 D7M Bryan Clay running.jpg",
  "a": "Eckhard Pecher (Arcimboldo)",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Osaka07_D7M_Bryan_Clay_running.jpg"
 },
 "стол": {
  "t": "2008-04-13 Expandable table expanding.jpg",
  "a": "Ildar Sagdejev (Specious)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2008-04-13_Expandable_table_expanding.jpg"
 },
 "столица": {
  "t": "Skyscrapers of Shinjuku 2009 January.jpg",
  "a": "Morio",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Skyscrapers_of_Shinjuku_2009_January.jpg"
 },
 "студия": {
  "t": "CCN-de-Rennes-et-de-Bretagne-studio-Francis-Mbida.jpg",
  "a": "Lucas Charbonnier",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:CCN-de-Rennes-et-de-Bretagne-studio-Francis-Mbida.jpg"
 },
 "суд": {
  "t": "Supreme Court of the United Kingdom, Court 1 Interior, London, UK - Diliff.jpg",
  "a": "Diliff",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Supreme_Court_of_the_United_Kingdom,_Court_1_Interior,_London,_UK_-_Diliff.jpg"
 },
 "суп": {
  "t": "Shchi.jpg",
  "a": "Victoria Vasilieva",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Shchi.jpg"
 },
 "такси": {
  "t": "TAXI.jpg",
  "a": "Petar Milošević",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:TAXI.jpg"
 },
 "тарелка": {
  "t": "Бухара, Кукельдаш, тарелка (2).jpg",
  "a": "Nikolai Bulykin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%91%D1%83%D1%85%D0%B0%D1%80%D0%B0,_%D0%9A%D1%83%D0%BA%D0%B5%D0%BB%D1%8C%D0%B4%D0%B0%D1%88,_%D1%82%D0%B0%D1%80%D0%B5%D0%BB%D0%BA%D0%B0_(2).jpg"
 },
 "театр": {
  "t": "Panorámica interior del Teatro Colón.jpg",
  "a": "Martin Bordagaray",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Panor%C3%A1mica_interior_del_Teatro_Col%C3%B3n.jpg"
 },
 "телевизор": {
  "t": "Neptun M547 BT.JPG",
  "a": "Tyktyk",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Neptun_M547_BT.JPG"
 },
 "телефон": {
  "t": "Советский телефон ТА-68.JPG",
  "a": "Andshel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%BE%D0%B2%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9_%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD_%D0%A2%D0%90-68.JPG"
 },
 "теннис": {
  "t": "Court 18 long view.JPG",
  "a": "Clavecin",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Court_18_long_view.JPG"
 },
 "тетрадь": {
  "t": "Notebooks.jpg",
  "a": "L.Marie",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Notebooks.jpg"
 },
 "товар": {
  "t": "Mediq Sverige Kungsbacka warehouse.jpg",
  "a": "Gwan Kho",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mediq_Sverige_Kungsbacka_warehouse.jpg"
 },
 "тюрьма": {
  "t": "Justizvollzugsanstalt Memmingen-2.jpg",
  "a": "Tobias \"ToMar\" Maier",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Justizvollzugsanstalt_Memmingen-2.jpg"
 },
 "уж": {
  "t": "2017.07.17.-15-Tiefer See oder Grubensee-Storkow (Mark)--Ringelnatter.jpg",
  "a": "Andreas Eichler",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2017.07.17.-15-Tiefer_See_oder_Grubensee-Storkow_(Mark)--Ringelnatter.jpg"
 },
 "улица": {
  "t": "Реконструкция Пятницкой улицы (июль 2014) (07).jpeg",
  "a": "stroi.mos.ru",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A0%D0%B5%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%9F%D1%8F%D1%82%D0%BD%D0%B8%D1%86%D0%BA%D0%BE%D0%B9_%D1%83%D0%BB%D0%B8%D1%86%D1%8B_(%D0%B8%D1%8E%D0%BB%D1%8C_2014)_(07).jpeg"
 },
 "университет": {
  "t": "University of Salamanca.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:University_of_Salamanca.jpg"
 },
 "упражнение": {
  "t": "Sea surviving training.jpg",
  "a": "Deep silence (Mikaël Restoux)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sea_surviving_training.jpg"
 },
 "урок": {
  "t": "Урок химии.jpg",
  "a": "Tsaryov357",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A3%D1%80%D0%BE%D0%BA_%D1%85%D0%B8%D0%BC%D0%B8%D0%B8.jpg"
 },
 "учёба": {
  "t": "Reading old Norse.jpg",
  "a": "Pål Berge",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Reading_old_Norse.jpg"
 },
 "учёный": {
  "t": "InvestigadoresUR.JPG",
  "a": "Urcomunicacion",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:InvestigadoresUR.JPG"
 },
 "фотография": {
  "t": "Mamiya RB67 - dos 120.jpg",
  "a": "Eusebius",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mamiya_RB67_-_dos_120.jpg"
 },
 "футбол": {
  "t": "Michael Zullo Utrecht.JPG",
  "a": "Ed Lane",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Michael_Zullo_Utrecht.JPG"
 },
 "холод": {
  "t": "Antarctic iceberg, 2001 -2.jpg",
  "a": "Georges Nijs from Diepenbeek, Belgium",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Antarctic_iceberg,_2001_-2.jpg"
 },
 "храм": {
  "t": "Philae temple at night.jpg",
  "a": "Moh hakem",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Philae_temple_at_night.jpg"
 },
 "чай": {
  "t": "Longjing-steeping-tallglass.jpg",
  "a": "Kaminix",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Longjing-steeping-tallglass.jpg"
 },
 "чайник": {
  "t": "Bernadotte Wasserkessel.jpg",
  "a": "Holger Ellgaard",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Bernadotte_Wasserkessel.jpg"
 },
 "чёрный": {
  "t": "Gato negro.JPG",
  "a": "Chosovi",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Gato_negro.JPG"
 },
 "школа": {
  "t": "Молодецьке (Маньківський р-н). Школа.jpg",
  "a": "Nikride",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B5%D1%86%D1%8C%D0%BA%D0%B5_(%D0%9C%D0%B0%D0%BD%D1%8C%D0%BA%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D1%80-%D0%BD)._%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0.jpg"
 },
 "экзамен": {
  "t": "Students taking computerized exam.jpg",
  "a": "Michael Surran",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Students_taking_computerized_exam.jpg"
 },
 "экскурсия": {
  "t": "WikiExpedition to the plant Rostselmash - September 2022 - Rostov-on-Don 197.jpg",
  "a": "Natalia Senatorova",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:WikiExpedition_to_the_plant_Rostselmash_-_September_2022_-_Rostov-on-Don_197.jpg"
 },
 "ягода": {
  "t": "Berberis thunbergii berries.jpg",
  "a": "Petritap",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Berberis_thunbergii_berries.jpg"
 },
 "яйцо": {
  "t": "Tortoise-Hatchling.jpg",
  "a": "Mayer Richard",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Tortoise-Hatchling.jpg"
 }
};
