/* Generated by tools/build_images.py — do not edit. Photographs from
   Wikipedia's articles and Wikimedia Commons, free to reuse with credit
   (CC0, public domain, CC BY, CC BY-SA), for the words the units teach,
   keyed on the bare word. CREDITS carries each file's title, author,
   licence and page, shown on the word's entry. */

export const IMAGES = {
  "Москва": require("../assets/img/0808.jpg"),
  "автобус": require("../assets/img/0813.jpg"),
  "автомобиль": require("../assets/img/0815.jpg"),
  "автоответчик": require("../assets/img/0817.jpg"),
  "актриса": require("../assets/img/0823.jpg"),
  "аптека": require("../assets/img/0828.jpg"),
  "армия": require("../assets/img/0832.jpg"),
  "аэропорт": require("../assets/img/0837.jpg"),
  "балет": require("../assets/img/0842.jpg"),
  "банк": require("../assets/img/0844.jpg"),
  "баскетбол": require("../assets/img/0845.jpg"),
  "бассейн": require("../assets/img/0846.jpg"),
  "батарея": require("../assets/img/0847.jpg"),
  "берег": require("../assets/img/0853.jpg"),
  "беседа": require("../assets/img/0854.jpg"),
  "библиотека": require("../assets/img/0857.jpg"),
  "библия": require("../assets/img/0858.jpg"),
  "билет": require("../assets/img/0860.jpg"),
  "бог": require("../assets/img/0865.jpg"),
  "богатство": require("../assets/img/0866.jpg"),
  "больница": require("../assets/img/0873.jpg"),
  "больной": require("../assets/img/0874.jpg"),
  "бомба": require("../assets/img/0877.jpg"),
  "борода": require("../assets/img/0878.jpg"),
  "борьба": require("../assets/img/0880.jpg"),
  "брат": require("../assets/img/0883.jpg"),
  "бутылка": require("../assets/img/0892.jpg"),
  "вагон": require("../assets/img/0898.jpg"),
  "велосипед": require("../assets/img/0904.jpg"),
  "весна": require("../assets/img/0907.jpg"),
  "ветер": require("../assets/img/0909.jpg"),
  "ветеран": require("../assets/img/0910.jpg"),
  "вечер": require("../assets/img/0911.jpg"),
  "виза": require("../assets/img/0918.jpg"),
  "вино": require("../assets/img/0920.jpg"),
  "вирус": require("../assets/img/0923.jpg"),
  "витрина": require("../assets/img/0925.jpg"),
  "водитель": require("../assets/img/0933.jpg"),
  "военный": require("../assets/img/0935.jpg"),
  "волейбол": require("../assets/img/0943.jpg"),
  "волк": require("../assets/img/0944.jpg"),
  "волос": require("../assets/img/0947.jpg"),
  "встреча": require("../assets/img/0960.jpg"),
  "выпить": require("../assets/img/0973.jpg"),
  "выставка": require("../assets/img/0975.jpg"),
  "газета": require("../assets/img/0979.jpg"),
  "галерея": require("../assets/img/0980.jpg"),
  "галстук": require("../assets/img/0981.jpg"),
  "гитара": require("../assets/img/0985.jpg"),
  "гнездо": require("../assets/img/0988.jpg"),
  "гора": require("../assets/img/0994.jpg"),
  "город": require("../assets/img/0999.jpg"),
  "городок": require("../assets/img/1000.jpg"),
  "госдума": require("../assets/img/1003.jpg"),
  "господь": require("../assets/img/1004.jpg"),
  "гостиница": require("../assets/img/1006.jpg"),
  "гражданин": require("../assets/img/1013.jpg"),
  "гром": require("../assets/img/1016.jpg"),
  "дверь": require("../assets/img/1029.jpg"),
  "двигатель": require("../assets/img/1030.jpg"),
  "двор": require("../assets/img/1031.jpg"),
  "декабрь": require("../assets/img/1037.jpg"),
  "деревня": require("../assets/img/1047.jpg"),
  "дерево": require("../assets/img/1048.jpg"),
  "деятельность": require("../assets/img/1052.jpg"),
  "директор": require("../assets/img/1055.jpg"),
  "дождь": require("../assets/img/1062.jpg"),
  "дом": require("../assets/img/1069.jpg"),
  "дорога": require("../assets/img/1071.jpg"),
  "друг": require("../assets/img/1079.jpg"),
  "желудок": require("../assets/img/1094.jpg"),
  "женщина": require("../assets/img/1096.jpg"),
  "журнал": require("../assets/img/1102.jpg"),
  "журналист": require("../assets/img/1103.jpg"),
  "завод": require("../assets/img/1108.jpg"),
  "заказчик": require("../assets/img/1118.jpg"),
  "звезда": require("../assets/img/1131.jpg"),
  "здоровье": require("../assets/img/1137.jpg"),
  "здравоохранение": require("../assets/img/1138.jpg"),
  "знание": require("../assets/img/1141.jpg"),
  "игрок": require("../assets/img/1147.jpg"),
  "игрушка": require("../assets/img/1148.jpg"),
  "источник": require("../assets/img/1172.jpg"),
  "камень": require("../assets/img/1180.jpg"),
  "канал": require("../assets/img/1182.jpg"),
  "капитан": require("../assets/img/1184.jpg"),
  "карман": require("../assets/img/1185.jpg"),
  "квартира": require("../assets/img/1196.jpg"),
  "кино": require("../assets/img/1197.jpg"),
  "кинотеатр": require("../assets/img/1198.jpg"),
  "класс": require("../assets/img/1199.jpg"),
  "клетка": require("../assets/img/1200.jpg"),
  "клиника": require("../assets/img/1202.jpg"),
  "клуб": require("../assets/img/1203.jpg"),
  "кожа": require("../assets/img/1209.jpg"),
  "коза": require("../assets/img/1210.jpg"),
  "кольцо": require("../assets/img/1214.jpg"),
  "команда": require("../assets/img/1215.jpg"),
  "комната": require("../assets/img/1220.jpg"),
  "компьютер": require("../assets/img/1223.jpg"),
  "концерт": require("../assets/img/1228.jpg"),
  "конь": require("../assets/img/1229.jpg"),
  "корабль": require("../assets/img/1230.jpg"),
  "корова": require("../assets/img/1232.jpg"),
  "кот": require("../assets/img/1238.jpg"),
  "кофе": require("../assets/img/1240.jpg"),
  "красота": require("../assets/img/1245.jpg"),
  "кредит": require("../assets/img/1246.jpg"),
  "крепость": require("../assets/img/1248.jpg"),
  "кресло": require("../assets/img/1249.jpg"),
  "крик": require("../assets/img/1251.jpg"),
  "культура": require("../assets/img/1257.jpg"),
  "курица": require("../assets/img/1259.jpg"),
  "куртка": require("../assets/img/1262.jpg"),
  "кухня": require("../assets/img/1263.jpg"),
  "лаборатория": require("../assets/img/1264.jpg"),
  "лапа": require("../assets/img/1266.jpg"),
  "лекарство": require("../assets/img/1269.jpg"),
  "лекция": require("../assets/img/1270.jpg"),
  "лес": require("../assets/img/1271.jpg"),
  "лето": require("../assets/img/1276.jpg"),
  "лист": require("../assets/img/1279.jpg"),
  "литература": require("../assets/img/1280.jpg"),
  "лицо": require("../assets/img/1281.jpg"),
  "лодка": require("../assets/img/1283.jpg"),
  "лошадь": require("../assets/img/1286.jpg"),
  "любовь": require("../assets/img/1291.jpg"),
  "медведь": require("../assets/img/1309.jpg"),
  "медицина": require("../assets/img/1310.jpg"),
  "менеджер": require("../assets/img/1312.jpg"),
  "метро": require("../assets/img/1315.jpg"),
  "минута": require("../assets/img/1321.jpg"),
  "митинг": require("../assets/img/1324.jpg"),
  "мода": require("../assets/img/1327.jpg"),
  "молния": require("../assets/img/1332.jpg"),
  "море": require("../assets/img/1340.jpg"),
  "мост": require("../assets/img/1343.jpg"),
  "мотоцикл": require("../assets/img/1344.jpg"),
  "мужчина": require("../assets/img/1348.jpg"),
  "музей": require("../assets/img/1349.jpg"),
  "музыка": require("../assets/img/1350.jpg"),
  "музыкант": require("../assets/img/1351.jpg"),
  "мысль": require("../assets/img/1352.jpg"),
  "мышка": require("../assets/img/1354.jpg"),
  "мышь": require("../assets/img/1356.jpg"),
  "мяч": require("../assets/img/1359.jpg"),
  "надежда": require("../assets/img/1362.jpg"),
  "напиток": require("../assets/img/1376.jpg"),
  "наркотик": require("../assets/img/1378.jpg"),
  "насекомое": require("../assets/img/1380.jpg"),
  "ножка": require("../assets/img/1411.jpg"),
  "ноутбук": require("../assets/img/1416.jpg"),
  "ночь": require("../assets/img/1418.jpg"),
  "обед": require("../assets/img/1423.jpg"),
  "облако": require("../assets/img/1427.jpg"),
  "обувь": require("../assets/img/1437.jpg"),
  "общество": require("../assets/img/1440.jpg"),
  "озеро": require("../assets/img/1451.jpg"),
  "окно": require("../assets/img/1452.jpg"),
  "олимпиада": require("../assets/img/1454.jpg"),
  "отец": require("../assets/img/1466.jpg"),
  "офис": require("../assets/img/1477.jpg"),
  "офицер": require("../assets/img/1478.jpg"),
  "палец": require("../assets/img/1485.jpg"),
  "пальто": require("../assets/img/1486.jpg"),
  "памятник": require("../assets/img/1487.jpg"),
  "парк": require("../assets/img/1491.jpg"),
  "паспорт": require("../assets/img/1493.jpg"),
  "пассажир": require("../assets/img/1494.jpg"),
  "пасха": require("../assets/img/1495.jpg"),
  "певица": require("../assets/img/1497.jpg"),
  "переулок": require("../assets/img/1507.jpg"),
  "пиво": require("../assets/img/1513.jpg"),
  "пистолет": require("../assets/img/1517.jpg"),
  "плавание": require("../assets/img/1520.jpg"),
  "планета": require("../assets/img/1523.jpg"),
  "площадь": require("../assets/img/1530.jpg"),
  "пляж": require("../assets/img/1532.jpg"),
  "повреждение": require("../assets/img/1535.jpg"),
  "погода": require("../assets/img/1538.jpg"),
  "поезд": require("../assets/img/1548.jpg"),
  "пол": require("../assets/img/1556.jpg"),
  "поле": require("../assets/img/1558.jpg"),
  "политика": require("../assets/img/1560.jpg"),
  "полиция": require("../assets/img/1563.jpg"),
  "полковник": require("../assets/img/1566.jpg"),
  "посольство": require("../assets/img/1583.jpg"),
  "почта": require("../assets/img/1587.jpg"),
  "председатель": require("../assets/img/1600.jpg"),
  "провод": require("../assets/img/1621.jpg"),
  "профессор": require("../assets/img/1637.jpg"),
  "птица": require("../assets/img/1641.jpg"),
  "пуля": require("../assets/img/1643.jpg"),
  "пьеса": require("../assets/img/1645.jpg"),
  "радиоприёмник": require("../assets/img/1650.jpg"),
  "река": require("../assets/img/1672.jpg"),
  "реклама": require("../assets/img/1673.jpg"),
  "ресторан": require("../assets/img/1678.jpg"),
  "родитель": require("../assets/img/1685.jpg"),
  "рот": require("../assets/img/1691.jpg"),
  "рубашка": require("../assets/img/1692.jpg"),
  "рука": require("../assets/img/1695.jpg"),
  "рыба": require("../assets/img/1698.jpg"),
  "рынок": require("../assets/img/1699.jpg"),
  "салат": require("../assets/img/1703.jpg"),
  "самолёт": require("../assets/img/1705.jpg"),
  "свадьба": require("../assets/img/1710.jpg"),
  "свинья": require("../assets/img/1714.jpg"),
  "сентябрь": require("../assets/img/1730.jpg"),
  "сеть": require("../assets/img/1735.jpg"),
  "снег": require("../assets/img/1753.jpg"),
  "собака": require("../assets/img/1755.jpg"),
  "собор": require("../assets/img/1756.jpg"),
  "солдат": require("../assets/img/1759.jpg"),
  "солнце": require("../assets/img/1761.jpg"),
  "сон": require("../assets/img/1764.jpg"),
  "спорт": require("../assets/img/1777.jpg"),
  "спортзал": require("../assets/img/1778.jpg"),
  "стадион": require("../assets/img/1785.jpg"),
  "стекло": require("../assets/img/1794.jpg"),
  "стена": require("../assets/img/1796.jpg"),
  "стол": require("../assets/img/1800.jpg"),
  "строительство": require("../assets/img/1811.jpg"),
  "суд": require("../assets/img/1815.jpg"),
  "сцена": require("../assets/img/1823.jpg"),
  "таблетка": require("../assets/img/1832.jpg"),
  "такси": require("../assets/img/1834.jpg"),
  "тарелка": require("../assets/img/1835.jpg"),
  "театр": require("../assets/img/1838.jpg"),
  "телевизор": require("../assets/img/1840.jpg"),
  "телефон": require("../assets/img/1841.jpg"),
  "теннис": require("../assets/img/1846.jpg"),
  "технология": require("../assets/img/1850.jpg"),
  "товар": require("../assets/img/1852.jpg"),
  "торговля": require("../assets/img/1855.jpg"),
  "торт": require("../assets/img/1856.jpg"),
  "трава": require("../assets/img/1858.jpg"),
  "тренер": require("../assets/img/1862.jpg"),
  "туман": require("../assets/img/1867.jpg"),
  "турист": require("../assets/img/1868.jpg"),
  "тюрьма": require("../assets/img/1873.jpg"),
  "улица": require("../assets/img/1892.jpg"),
  "университет": require("../assets/img/1895.jpg"),
  "упражнение": require("../assets/img/1898.jpg"),
  "урок": require("../assets/img/1899.jpg"),
  "учёный": require("../assets/img/1917.jpg"),
  "фотоаппарат": require("../assets/img/1930.jpg"),
  "фотография": require("../assets/img/1931.jpg"),
  "химия": require("../assets/img/1937.jpg"),
  "холод": require("../assets/img/1940.jpg"),
  "хор": require("../assets/img/1942.jpg"),
  "храм": require("../assets/img/1945.jpg"),
  "христианский": require("../assets/img/1946.jpg"),
  "чай": require("../assets/img/1953.jpg"),
  "шахматы": require("../assets/img/1969.jpg"),
  "школа": require("../assets/img/1973.jpg"),
  "шоссе": require("../assets/img/1976.jpg"),
  "эволюция": require("../assets/img/1980.jpg"),
  "электричество": require("../assets/img/1985.jpg"),
};

export const FILES = {
 "Москва": "0808.jpg",
 "автобус": "0813.jpg",
 "автомобиль": "0815.jpg",
 "автоответчик": "0817.jpg",
 "актриса": "0823.jpg",
 "аптека": "0828.jpg",
 "армия": "0832.jpg",
 "аэропорт": "0837.jpg",
 "балет": "0842.jpg",
 "банк": "0844.jpg",
 "баскетбол": "0845.jpg",
 "бассейн": "0846.jpg",
 "батарея": "0847.jpg",
 "берег": "0853.jpg",
 "беседа": "0854.jpg",
 "библиотека": "0857.jpg",
 "библия": "0858.jpg",
 "билет": "0860.jpg",
 "бог": "0865.jpg",
 "богатство": "0866.jpg",
 "больница": "0873.jpg",
 "больной": "0874.jpg",
 "бомба": "0877.jpg",
 "борода": "0878.jpg",
 "борьба": "0880.jpg",
 "брат": "0883.jpg",
 "бутылка": "0892.jpg",
 "вагон": "0898.jpg",
 "велосипед": "0904.jpg",
 "весна": "0907.jpg",
 "ветер": "0909.jpg",
 "ветеран": "0910.jpg",
 "вечер": "0911.jpg",
 "виза": "0918.jpg",
 "вино": "0920.jpg",
 "вирус": "0923.jpg",
 "витрина": "0925.jpg",
 "водитель": "0933.jpg",
 "военный": "0935.jpg",
 "волейбол": "0943.jpg",
 "волк": "0944.jpg",
 "волос": "0947.jpg",
 "встреча": "0960.jpg",
 "выпить": "0973.jpg",
 "выставка": "0975.jpg",
 "газета": "0979.jpg",
 "галерея": "0980.jpg",
 "галстук": "0981.jpg",
 "гитара": "0985.jpg",
 "гнездо": "0988.jpg",
 "гора": "0994.jpg",
 "город": "0999.jpg",
 "городок": "1000.jpg",
 "госдума": "1003.jpg",
 "господь": "1004.jpg",
 "гостиница": "1006.jpg",
 "гражданин": "1013.jpg",
 "гром": "1016.jpg",
 "дверь": "1029.jpg",
 "двигатель": "1030.jpg",
 "двор": "1031.jpg",
 "декабрь": "1037.jpg",
 "деревня": "1047.jpg",
 "дерево": "1048.jpg",
 "деятельность": "1052.jpg",
 "директор": "1055.jpg",
 "дождь": "1062.jpg",
 "дом": "1069.jpg",
 "дорога": "1071.jpg",
 "друг": "1079.jpg",
 "желудок": "1094.jpg",
 "женщина": "1096.jpg",
 "журнал": "1102.jpg",
 "журналист": "1103.jpg",
 "завод": "1108.jpg",
 "заказчик": "1118.jpg",
 "звезда": "1131.jpg",
 "здоровье": "1137.jpg",
 "здравоохранение": "1138.jpg",
 "знание": "1141.jpg",
 "игрок": "1147.jpg",
 "игрушка": "1148.jpg",
 "источник": "1172.jpg",
 "камень": "1180.jpg",
 "канал": "1182.jpg",
 "капитан": "1184.jpg",
 "карман": "1185.jpg",
 "квартира": "1196.jpg",
 "кино": "1197.jpg",
 "кинотеатр": "1198.jpg",
 "класс": "1199.jpg",
 "клетка": "1200.jpg",
 "клиника": "1202.jpg",
 "клуб": "1203.jpg",
 "кожа": "1209.jpg",
 "коза": "1210.jpg",
 "кольцо": "1214.jpg",
 "команда": "1215.jpg",
 "комната": "1220.jpg",
 "компьютер": "1223.jpg",
 "концерт": "1228.jpg",
 "конь": "1229.jpg",
 "корабль": "1230.jpg",
 "корова": "1232.jpg",
 "кот": "1238.jpg",
 "кофе": "1240.jpg",
 "красота": "1245.jpg",
 "кредит": "1246.jpg",
 "крепость": "1248.jpg",
 "кресло": "1249.jpg",
 "крик": "1251.jpg",
 "культура": "1257.jpg",
 "курица": "1259.jpg",
 "куртка": "1262.jpg",
 "кухня": "1263.jpg",
 "лаборатория": "1264.jpg",
 "лапа": "1266.jpg",
 "лекарство": "1269.jpg",
 "лекция": "1270.jpg",
 "лес": "1271.jpg",
 "лето": "1276.jpg",
 "лист": "1279.jpg",
 "литература": "1280.jpg",
 "лицо": "1281.jpg",
 "лодка": "1283.jpg",
 "лошадь": "1286.jpg",
 "любовь": "1291.jpg",
 "медведь": "1309.jpg",
 "медицина": "1310.jpg",
 "менеджер": "1312.jpg",
 "метро": "1315.jpg",
 "минута": "1321.jpg",
 "митинг": "1324.jpg",
 "мода": "1327.jpg",
 "молния": "1332.jpg",
 "море": "1340.jpg",
 "мост": "1343.jpg",
 "мотоцикл": "1344.jpg",
 "мужчина": "1348.jpg",
 "музей": "1349.jpg",
 "музыка": "1350.jpg",
 "музыкант": "1351.jpg",
 "мысль": "1352.jpg",
 "мышка": "1354.jpg",
 "мышь": "1356.jpg",
 "мяч": "1359.jpg",
 "надежда": "1362.jpg",
 "напиток": "1376.jpg",
 "наркотик": "1378.jpg",
 "насекомое": "1380.jpg",
 "ножка": "1411.jpg",
 "ноутбук": "1416.jpg",
 "ночь": "1418.jpg",
 "обед": "1423.jpg",
 "облако": "1427.jpg",
 "обувь": "1437.jpg",
 "общество": "1440.jpg",
 "озеро": "1451.jpg",
 "окно": "1452.jpg",
 "олимпиада": "1454.jpg",
 "отец": "1466.jpg",
 "офис": "1477.jpg",
 "офицер": "1478.jpg",
 "палец": "1485.jpg",
 "пальто": "1486.jpg",
 "памятник": "1487.jpg",
 "парк": "1491.jpg",
 "паспорт": "1493.jpg",
 "пассажир": "1494.jpg",
 "пасха": "1495.jpg",
 "певица": "1497.jpg",
 "переулок": "1507.jpg",
 "пиво": "1513.jpg",
 "пистолет": "1517.jpg",
 "плавание": "1520.jpg",
 "планета": "1523.jpg",
 "площадь": "1530.jpg",
 "пляж": "1532.jpg",
 "повреждение": "1535.jpg",
 "погода": "1538.jpg",
 "поезд": "1548.jpg",
 "пол": "1556.jpg",
 "поле": "1558.jpg",
 "политика": "1560.jpg",
 "полиция": "1563.jpg",
 "полковник": "1566.jpg",
 "посольство": "1583.jpg",
 "почта": "1587.jpg",
 "председатель": "1600.jpg",
 "провод": "1621.jpg",
 "профессор": "1637.jpg",
 "птица": "1641.jpg",
 "пуля": "1643.jpg",
 "пьеса": "1645.jpg",
 "радиоприёмник": "1650.jpg",
 "река": "1672.jpg",
 "реклама": "1673.jpg",
 "ресторан": "1678.jpg",
 "родитель": "1685.jpg",
 "рот": "1691.jpg",
 "рубашка": "1692.jpg",
 "рука": "1695.jpg",
 "рыба": "1698.jpg",
 "рынок": "1699.jpg",
 "салат": "1703.jpg",
 "самолёт": "1705.jpg",
 "свадьба": "1710.jpg",
 "свинья": "1714.jpg",
 "сентябрь": "1730.jpg",
 "сеть": "1735.jpg",
 "снег": "1753.jpg",
 "собака": "1755.jpg",
 "собор": "1756.jpg",
 "солдат": "1759.jpg",
 "солнце": "1761.jpg",
 "сон": "1764.jpg",
 "спорт": "1777.jpg",
 "спортзал": "1778.jpg",
 "стадион": "1785.jpg",
 "стекло": "1794.jpg",
 "стена": "1796.jpg",
 "стол": "1800.jpg",
 "строительство": "1811.jpg",
 "суд": "1815.jpg",
 "сцена": "1823.jpg",
 "таблетка": "1832.jpg",
 "такси": "1834.jpg",
 "тарелка": "1835.jpg",
 "театр": "1838.jpg",
 "телевизор": "1840.jpg",
 "телефон": "1841.jpg",
 "теннис": "1846.jpg",
 "технология": "1850.jpg",
 "товар": "1852.jpg",
 "торговля": "1855.jpg",
 "торт": "1856.jpg",
 "трава": "1858.jpg",
 "тренер": "1862.jpg",
 "туман": "1867.jpg",
 "турист": "1868.jpg",
 "тюрьма": "1873.jpg",
 "улица": "1892.jpg",
 "университет": "1895.jpg",
 "упражнение": "1898.jpg",
 "урок": "1899.jpg",
 "учёный": "1917.jpg",
 "фотоаппарат": "1930.jpg",
 "фотография": "1931.jpg",
 "химия": "1937.jpg",
 "холод": "1940.jpg",
 "хор": "1942.jpg",
 "храм": "1945.jpg",
 "христианский": "1946.jpg",
 "чай": "1953.jpg",
 "шахматы": "1969.jpg",
 "школа": "1973.jpg",
 "шоссе": "1976.jpg",
 "эволюция": "1980.jpg",
 "электричество": "1985.jpg"
};

export const CREDITS = {
 "Москва": {
  "t": "Moscow City landscape july 2008.jpg",
  "a": "Dmitry A. Mottl",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Moscow_City_landscape_july_2008.jpg"
 },
 "автобус": {
  "t": "MAZ-103 in Minsk 01.jpg",
  "a": "Redline",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:MAZ-103_in_Minsk_01.jpg"
 },
 "автомобиль": {
  "t": "2005 Toyota Corolla 1.4 T3.jpg",
  "a": "Jayme Kimball",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2005_Toyota_Corolla_1.4_T3.jpg"
 },
 "автоответчик": {
  "t": "Panasonic-Anrufbeantworter.jpg",
  "a": "Norbert Schnitzler",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Panasonic-Anrufbeantworter.jpg"
 },
 "актриса": {
  "t": "TheActorsWorkshop1.jpg",
  "a": "Psycho Motel",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:TheActorsWorkshop1.jpg"
 },
 "аптека": {
  "t": "Pharmacie, Paris 2010.jpg",
  "a": "Daniel Stockman",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Pharmacie,_Paris_2010.jpg"
 },
 "армия": {
  "t": "Combined Arms Training.jpg",
  "a": "Sgt. Anthony Jones",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Combined_Arms_Training.jpg"
 },
 "аэропорт": {
  "t": "Labuan Malaysia Airport-07.jpg",
  "a": "CEphoto, Uwe Aranas",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Labuan_Malaysia_Airport-07.jpg"
 },
 "балет": {
  "t": "Grace in winter, contemporary ballet.jpg",
  "a": "jeff from denver, US",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Grace_in_winter,_contemporary_ballet.jpg"
 },
 "банк": {
  "t": "Barclays Bank, West Kirby.jpg",
  "a": "Rodhullandemu",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Barclays_Bank,_West_Kirby.jpg"
 },
 "баскетбол": {
  "t": "2023-08-09 Deutschland gegen Kanada (Basketball-Länderspiel) by Sandro Halank–118.jpg",
  "a": "Sandro Halank, Wikimedia Commons",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2023-08-09_Deutschland_gegen_Kanada_(Basketball-L%C3%A4nderspiel)_by_Sandro_Halank%E2%80%93118.jpg"
 },
 "бассейн": {
  "t": "Lille piscine max dormoy.jpg",
  "a": "Velvet",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lille_piscine_max_dormoy.jpg"
 },
 "батарея": {
  "t": "Battery checker.jpg",
  "a": "Jason7825",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Battery_checker.jpg"
 },
 "берег": {
  "t": "Spring Lake, New Jersey Beach at Sunrise.jpg",
  "a": "Nick Harris",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Spring_Lake,_New_Jersey_Beach_at_Sunrise.jpg"
 },
 "беседа": {
  "t": "वार्तालाप.jpg",
  "a": "Surenders25",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%E0%A4%B5%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%BE%E0%A4%B2%E0%A4%BE%E0%A4%AA.jpg"
 },
 "библиотека": {
  "t": "SanDiegoCityCollegeLearningResource - bookshelf.jpg",
  "a": "Joe Crawford from Moorpark, California, USA",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:SanDiegoCityCollegeLearningResource_-_bookshelf.jpg"
 },
 "библия": {
  "t": "Gutenberg Bible, Lenox Copy, New York Public Library, 2009. Pic 01.jpg",
  "a": "NYC Wanderer (Kevin Eng)",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Gutenberg_Bible,_Lenox_Copy,_New_York_Public_Library,_2009._Pic_01.jpg"
 },
 "билет": {
  "t": "Ticket (unseparated) Kurkino-Berchtesgaden.JPG",
  "a": "Andreas -horn- Hornig",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Ticket_(unseparated)_Kurkino-Berchtesgaden.JPG"
 },
 "бог": {
  "t": "Istanbul, Hagia Sophia, Allah.jpg",
  "a": "When reusing, please credit me as\n\n\nauthor: Adam Kliczek, http://memoriesstay.co",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Istanbul,_Hagia_Sophia,_Allah.jpg"
 },
 "богатство": {
  "t": "Gold bullion bars.jpg",
  "a": "Stevebidmead",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Gold_bullion_bars.jpg"
 },
 "больница": {
  "t": "Лечебно-диагностический комплекс ИКБ № 1 (Москва) 20.jpg",
  "a": "М. Мишина. Пресс-служба Мэра и Правительства Москвы",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B5%D1%87%D0%B5%D0%B1%D0%BD%D0%BE-%D0%B4%D0%B8%D0%B0%D0%B3%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81_%D0%98%D0%9A%D0%91_%E2%84%96_1_(%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0)_20.jpg"
 },
 "больной": {
  "t": "Hallways filled with patients.jpg",
  "a": "meg and rahul",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hallways_filled_with_patients.jpg"
 },
 "бомба": {
  "t": "MOAB bomb.jpg",
  "a": "U.S. Department of Defense photograph",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:MOAB_bomb.jpg"
 },
 "борода": {
  "t": "Photography-wallpaper-facial-hair-man-beard-chin-moustache-human-elder-portrait-1453095.jpg",
  "a": "@nazanin",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Photography-wallpaper-facial-hair-man-beard-chin-moustache-human-elder-portrait-1453095.jpg"
 },
 "борьба": {
  "t": "0432-DremielLiftsRulon.jpg",
  "a": "Tim Hipps",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:0432-DremielLiftsRulon.jpg"
 },
 "брат": {
  "t": "Two brothers together in Bihar, India.jpg",
  "a": "Saddam19",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Two_brothers_together_in_Bihar,_India.jpg"
 },
 "бутылка": {
  "t": "DrPepper 0.5l PET.jpg",
  "a": "Afrank99",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:DrPepper_0.5l_PET.jpg"
 },
 "вагон": {
  "t": "D-DB 50 80 36-75 071-1 DABpza 758.5 Doerverden 01.07.2013.jpg",
  "a": "Christian Dittmer",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:D-DB_50_80_36-75_071-1_DABpza_758.5_Doerverden_01.07.2013.jpg"
 },
 "велосипед": {
  "t": "JugendstilBikes Miyata760SR06.jpg",
  "a": "JugendstilBikes",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:JugendstilBikes_Miyata760SR06.jpg"
 },
 "весна": {
  "t": "Arboretum Robert Lenoir - Jardin des méllifères.jpg",
  "a": "JackyM59",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Arboretum_Robert_Lenoir_-_Jardin_des_m%C3%A9llif%C3%A8res.jpg"
 },
 "ветер": {
  "t": "2017-08-26-Windraeder Fehmarn-4301.jpg",
  "a": "Superbass",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2017-08-26-Windraeder_Fehmarn-4301.jpg"
 },
 "ветеран": {
  "t": "Sydney 2015 Anzac Day march (17119683648).jpg",
  "a": "Yupeng Wu from sydney, Australia",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sydney_2015_Anzac_Day_march_(17119683648).jpg"
 },
 "вечер": {
  "t": "Evening in Parambikkulam, Kerala, India.jpg",
  "a": "Augustus Binu/ www.dreamsparrow.net/ facebook",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Evening_in_Parambikkulam,_Kerala,_India.jpg"
 },
 "виза": {
  "t": "Visa usa.jpg",
  "a": "Usuarioparaguayo",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Visa_usa.jpg"
 },
 "вино": {
  "t": "Idaho Wine .jpg",
  "a": "Fhynek00",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Idaho_Wine_.jpg"
 },
 "вирус": {
  "t": "Rotavirus Reconstruction.jpg",
  "a": "",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Rotavirus_Reconstruction.jpg"
 },
 "витрина": {
  "t": "Витрина фотостудии.jpg",
  "a": "Phillip Chee",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%B8%D1%82%D1%80%D0%B8%D0%BD%D0%B0_%D1%84%D0%BE%D1%82%D0%BE%D1%81%D1%82%D1%83%D0%B4%D0%B8%D0%B8.jpg"
 },
 "водитель": {
  "t": "Convertible Mercedes Car Driving On A Highway.jpg",
  "a": "DWS MontagZen",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Convertible_Mercedes_Car_Driving_On_A_Highway.jpg"
 },
 "военный": {
  "t": "4thTankDivisionOpenDay17p2-06.jpg",
  "a": "Vitaly V. Kuzmin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:4thTankDivisionOpenDay17p2-06.jpg"
 },
 "волейбол": {
  "t": "Volleyball game.jpg",
  "a": "U.S Navy photo by Photographer's Mate 2nd Class Terry Spain",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Volleyball_game.jpg"
 },
 "волк": {
  "t": "Eurasian wolf 2.jpg",
  "a": "User:Mas3cf",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Eurasian_wolf_2.jpg"
 },
 "волос": {
  "t": "Blond hair going gray 01.jpg",
  "a": "Kritzolina",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Blond_hair_going_gray_01.jpg"
 },
 "встреча": {
  "t": "Sitzung von Wiki Loves Broadcast im Kontor Hamburg.jpg",
  "a": "Wikiolo",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sitzung_von_Wiki_Loves_Broadcast_im_Kontor_Hamburg.jpg"
 },
 "выпить": {
  "t": "Alcoholism 01.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Lite",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Alcoholism_01.jpg"
 },
 "выставка": {
  "t": "FUTURES exhibition sign.jpg",
  "a": "APK",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:FUTURES_exhibition_sign.jpg"
 },
 "газета": {
  "t": "An old man in newsagent's shop, Paris September 2011.jpg",
  "a": "Florian Plag from Bretten",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:An_old_man_in_newsagent%27s_shop,_Paris_September_2011.jpg"
 },
 "галерея": {
  "t": "Uffizi Hallway.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Uffizi_Hallway.jpg"
 },
 "галстук": {
  "t": "Memphis tie 1A.JPG",
  "a": "Affärside",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Memphis_tie_1A.JPG"
 },
 "гитара": {
  "t": "My Mates 3 (2082240480).jpg",
  "a": "Steve Garry from Manchester, United Kingdom",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:My_Mates_3_(2082240480).jpg"
 },
 "гнездо": {
  "t": "Yelagiri bird's nest.jpg",
  "a": "https://www.flickr.com/photos/mckaysavage/ mckaysavage",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Yelagiri_bird%27s_nest.jpg"
 },
 "гора": {
  "t": "Khor Virap.jpg",
  "a": "Maks Karochkin",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Khor_Virap.jpg"
 },
 "город": {
  "t": "Turkish.town.cesme.jpg",
  "a": "OscarKosy",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Turkish.town.cesme.jpg"
 },
 "городок": {
  "t": "Piran old town.jpg",
  "a": "Isiwal",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Piran_old_town.jpg"
 },
 "госдума": {
  "t": "Рассмотрение проекта бюджета на 2023-2025 годы в Государственной думе.jpg",
  "a": "ЛДПР — Liberal Democratic Party of Russia (photo by Alexander Sivov)",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A0%D0%B0%D1%81%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0_%D0%B1%D1%8E%D0%B4%D0%B6%D0%B5%D1%82%D0%B0_%D0%BD%D0%B0_2023-2025_%D0%B3%D0%BE%D0%B4%D1%8B_%D0%B2_%D0%93%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B4%D1%83%D0%BC%D0%B5.jpg"
 },
 "господь": {
  "t": "Saviour, Nikolo-Tikhonov Monastery (The Saviour Not Made by Hands).jpg",
  "a": "Nikolay Omonov",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Saviour,_Nikolo-Tikhonov_Monastery_(The_Saviour_Not_Made_by_Hands).jpg"
 },
 "гостиница": {
  "t": "Livorno - Hotel Palazzo - 2025-09-29 20-09-38 001.jpg",
  "a": "Terragio67",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Livorno_-_Hotel_Palazzo_-_2025-09-29_20-09-38_001.jpg"
 },
 "гражданин": {
  "t": "Peter Dutton at Australian Citizenship Ceremony, 2017.jpg",
  "a": "Commonwealth of Australia",
  "l": "CC BY 3.0 au",
  "u": "https://commons.wikimedia.org/wiki/File:Peter_Dutton_at_Australian_Citizenship_Ceremony,_2017.jpg"
 },
 "гром": {
  "t": "Wall cloud with lightning - NOAA - rotated.jpg",
  "a": "Rotating by Holek (обсуждение · вклад), picture came from U.S. National Oceanic ",
  "l": "CC BY-SA 2.5 pl",
  "u": "https://commons.wikimedia.org/wiki/File:Wall_cloud_with_lightning_-_NOAA_-_rotated.jpg"
 },
 "дверь": {
  "t": "Bronze door, Basilica di San Giovanni, 2013.jpg",
  "a": "Szilas",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bronze_door,_Basilica_di_San_Giovanni,_2013.jpg"
 },
 "двигатель": {
  "t": "2007-06-15 34 Moto Guzzi PE, Fg.-Nr. SP7032.jpg",
  "a": "Lothar Spurzem",
  "l": "CC BY-SA 2.0 de",
  "u": "https://commons.wikimedia.org/wiki/File:2007-06-15_34_Moto_Guzzi_PE,_Fg.-Nr._SP7032.jpg"
 },
 "двор": {
  "t": "Typical suburban backyard.jpg",
  "a": "Veracious Rey at en.wikipedia",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Typical_suburban_backyard.jpg"
 },
 "декабрь": {
  "t": "Fanny udde December 2021 01.jpg",
  "a": "Arild Vågen",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fanny_udde_December_2021_01.jpg"
 },
 "деревня": {
  "t": "DSC00029 Java Little Sundanais Traditional Village Kampung Naga (6219569245).jpg",
  "a": "DANIEL JULIE from Paris, France",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:DSC00029_Java_Little_Sundanais_Traditional_Village_Kampung_Naga_(6219569245).jpg"
 },
 "дерево": {
  "t": "Sequoiadendron giganteum at Kenilworth Castle.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Jdfo",
  "l": "CC BY 1.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sequoiadendron_giganteum_at_Kenilworth_Castle.jpg"
 },
 "деятельность": {
  "t": "Labour SAM 3921.jpg",
  "a": "Андрей Перцев 1967",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Labour_SAM_3921.jpg"
 },
 "директор": {
  "t": "Intel Board of Directors.jpg",
  "a": "Intel Free Press",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Intel_Board_of_Directors.jpg"
 },
 "дождь": {
  "t": "Heavy Rain.jpg",
  "a": "Pridatko Oleksandr",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Heavy_Rain.jpg"
 },
 "дом": {
  "t": "Katsura Imperial Villa in Spring.jpg",
  "a": "John Chang",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Katsura_Imperial_Villa_in_Spring.jpg"
 },
 "дорога": {
  "t": "Дорога в холмах.jpg",
  "a": "Pat_World",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B0_%D0%B2_%D1%85%D0%BE%D0%BB%D0%BC%D0%B0%D1%85.jpg"
 },
 "друг": {
  "t": "Childhood friends at a carnival.jpg",
  "a": "Squelle",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Childhood_friends_at_a_carnival.jpg"
 },
 "желудок": {
  "t": "Location of the stomach.jpg",
  "a": "Vslv",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Location_of_the_stomach.jpg"
 },
 "женщина": {
  "t": "Woman at Lover's Bridge Tanjung Sepat (cropped).jpg",
  "a": "John Ragai",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Woman_at_Lover%27s_Bridge_Tanjung_Sepat_(cropped).jpg"
 },
 "журнал": {
  "t": "German Printmagazines.jpg",
  "a": "Rüdiger Müller",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:German_Printmagazines.jpg"
 },
 "журналист": {
  "t": "Phoenix Heinz Abel 1.jpg",
  "a": "André Zahn",
  "l": "CC BY-SA 2.0 de",
  "u": "https://commons.wikimedia.org/wiki/File:Phoenix_Heinz_Abel_1.jpg"
 },
 "завод": {
  "t": "Cromford Mill 2008.jpg",
  "a": "craig carter from DERBYSHIRE, UK",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Cromford_Mill_2008.jpg"
 },
 "заказчик": {
  "t": "Market Scene with Vendor and Customers - Zacatlan - Puebla - Mexico (52208328324).jpg",
  "a": "Adam Jones from Kelowna, BC, Canada",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Market_Scene_with_Vendor_and_Customers_-_Zacatlan_-_Puebla_-_Mexico_(52208328324).jpg"
 },
 "звезда": {
  "t": "Звёздное небо в Альпах.jpg",
  "a": "Loris Sponda",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%97%D0%B2%D1%91%D0%B7%D0%B4%D0%BD%D0%BE%D0%B5_%D0%BD%D0%B5%D0%B1%D0%BE_%D0%B2_%D0%90%D0%BB%D1%8C%D0%BF%D0%B0%D1%85.jpg"
 },
 "здоровье": {
  "t": "Pilates 01.jpg",
  "a": "J. Vílchez",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Pilates_01.jpg"
 },
 "здравоохранение": {
  "t": "Consultation des femmes et des bébés.jpg",
  "a": "Daisy MSL",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Consultation_des_femmes_et_des_b%C3%A9b%C3%A9s.jpg"
 },
 "знание": {
  "t": "Latin dictionary.jpg",
  "a": "Dr. Marcus Gossler",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Latin_dictionary.jpg"
 },
 "игрок": {
  "t": "Michael Zullo Utrecht.JPG",
  "a": "Ed Lane",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Michael_Zullo_Utrecht.JPG"
 },
 "игрушка": {
  "t": "Slinky rainbow.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Enoc",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Slinky_rainbow.jpg"
 },
 "источник": {
  "t": "Big Spring Missouri 1-02Aug08.jpg",
  "a": "Kbh3rd",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Big_Spring_Missouri_1-02Aug08.jpg"
 },
 "камень": {
  "t": "Two-parts stone nikogda takih ne videl vot.JPG",
  "a": "Sergei Frolov, http://sfrolov.livejournal.com",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Two-parts_stone_nikogda_takih_ne_videl_vot.JPG"
 },
 "канал": {
  "t": "Alter Strom.jpg",
  "a": "Martin Künzel, Berlin – Edited by Fir0002",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Alter_Strom.jpg"
 },
 "капитан": {
  "t": "Captain on ship.jpg",
  "a": "Hillebrand Steve, U.S. Fish and Wildlife Service",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Captain_on_ship.jpg"
 },
 "карман": {
  "t": "Black Jeans with Zipper Pocket Detailing (15470033547).jpg",
  "a": "Jamie",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Black_Jeans_with_Zipper_Pocket_Detailing_(15470033547).jpg"
 },
 "квартира": {
  "t": "Housing and Development Board flats near Woodlands Avenue 7, Singapore.jpg",
  "a": "Slivester (Slivester Nuenenorl).",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Housing_and_Development_Board_flats_near_Woodlands_Avenue_7,_Singapore.jpg"
 },
 "кино": {
  "t": "Arri Alexa camera.jpg",
  "a": "Sean P. Anderson from Dallas, TX, USA",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Arri_Alexa_camera.jpg"
 },
 "кинотеатр": {
  "t": "Sala de cine.jpg",
  "a": "Jorge Simonet",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sala_de_cine.jpg"
 },
 "класс": {
  "t": "Room-education-classroom-children-library-students-1237486.jpg",
  "a": "https://pxhere.com/es/photo/1237486",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Room-education-classroom-children-library-students-1237486.jpg"
 },
 "клетка": {
  "t": "A caged Alexandrine parrot at a household in West Bengal, India photographed on November 29, 2024.jpg",
  "a": "Billjones94",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:A_caged_Alexandrine_parrot_at_a_household_in_West_Bengal,_India_photographed_on_November_29,_2024.jpg"
 },
 "клиника": {
  "t": "Legionowo, Poliklinika Wojskowa - fotopolska.eu (343207).jpg",
  "a": "Wiesław Z.",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Legionowo,_Poliklinika_Wojskowa_-_fotopolska.eu_(343207).jpg"
 },
 "клуб": {
  "t": "Savile Club New Bar 2.JPG",
  "a": "Creator:Savile Club",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Savile_Club_New_Bar_2.JPG"
 },
 "кожа": {
  "t": "Elephant skin (3689577529).jpg",
  "a": "Greg Willis from Denver, CO, usa",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Elephant_skin_(3689577529).jpg"
 },
 "коза": {
  "t": "Hausziege 04.jpg",
  "a": "Kuebi = Armin Kübelbeck",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hausziege_04.jpg"
 },
 "кольцо": {
  "t": "Ring Ruby.jpg",
  "a": "ネックレス (A necklace)",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Ring_Ruby.jpg"
 },
 "команда": {
  "t": "Rugby union scrummage.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Rugby_union_scrummage.jpg"
 },
 "комната": {
  "t": "D.A. Sturdza House, Bucharest (Romania) 9.jpg",
  "a": "Neoclassicism Enthusiast",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:D.A._Sturdza_House,_Bucharest_(Romania)_9.jpg"
 },
 "компьютер": {
  "t": "2014 Modding komputera 01.jpg",
  "a": "Halicki",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2014_Modding_komputera_01.jpg"
 },
 "концерт": {
  "t": "Playtime Festival 2024.jpg",
  "a": "Chongkian",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Playtime_Festival_2024.jpg"
 },
 "конь": {
  "t": "Equus species.jpg",
  "a": "LittleJerry; JPG by uploader",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Equus_species.jpg"
 },
 "корабль": {
  "t": "HMS warriorjune20092.jpg",
  "a": "geni",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:HMS_warriorjune20092.jpg"
 },
 "корова": {
  "t": "Cow female black white.jpg",
  "a": "Keith Weller/USDA",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Cow_female_black_white.jpg"
 },
 "кот": {
  "t": "Siam lilacpoint.jpg",
  "a": "Karin Langner-Bahmann, upload von Martin Bahmann",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Siam_lilacpoint.jpg"
 },
 "кофе": {
  "t": "A small cup of coffee.JPG",
  "a": "Julius Schorzman",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:A_small_cup_of_coffee.JPG"
 },
 "красота": {
  "t": "Фуксия цветок красота.jpg",
  "a": "Daniel Colquitt",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A4%D1%83%D0%BA%D1%81%D0%B8%D1%8F_%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%BA_%D0%BA%D1%80%D0%B0%D1%81%D0%BE%D1%82%D0%B0.jpg"
 },
 "кредит": {
  "t": "Credit-cards.jpg",
  "a": "Lotus Head from Johannesburg, Gauteng, South Africa",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Credit-cards.jpg"
 },
 "крепость": {
  "t": "France Alsace Bas-Rhin Fort de Mutzig 16.JPG",
  "a": "Calips",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:France_Alsace_Bas-Rhin_Fort_de_Mutzig_16.JPG"
 },
 "кресло": {
  "t": "Grand Taile.jpg",
  "a": "\"UweBesendoerfer/MichaelPopp/kultsessel\"",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Grand_Taile.jpg"
 },
 "крик": {
  "t": "Baby yelling.jpg",
  "a": "Dave Buchwald",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Baby_yelling.jpg"
 },
 "культура": {
  "t": "9 Bisonte Magdaleniense polícromo.jpg",
  "a": "Museo de Altamira y D. Rodríguez",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:9_Bisonte_Magdaleniense_pol%C3%ADcromo.jpg"
 },
 "курица": {
  "t": "Male and female chicken sitting together.jpg",
  "a": "Andrei Niemimäki из Турку, Финляндия",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Male_and_female_chicken_sitting_together.jpg"
 },
 "куртка": {
  "t": "Jack Wolfskin, OutDoor 2018, Friedrichshafen (1X7A0421).jpg",
  "a": "Matti Blume",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Jack_Wolfskin,_OutDoor_2018,_Friedrichshafen_(1X7A0421).jpg"
 },
 "кухня": {
  "t": "Alno Kuechenzeile 1980er Jahre.jpg",
  "a": "Mabit1",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Alno_Kuechenzeile_1980er_Jahre.jpg"
 },
 "лаборатория": {
  "t": "At Manchester 2023 2023 006.jpg",
  "a": "Photograph by Mike Peel (www.mikepeel.net).",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:At_Manchester_2023_2023_006.jpg"
 },
 "лапа": {
  "t": "DogDewClawTika1 wb.jpg",
  "a": "en:User:Elf",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:DogDewClawTika1_wb.jpg"
 },
 "лекарство": {
  "t": "Medikamente.jpg",
  "a": "Würfel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Medikamente.jpg"
 },
 "лекция": {
  "t": "ADFA Lecture Theatres.jpg",
  "a": "Kurt Barnett",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:ADFA_Lecture_Theatres.jpg"
 },
 "лес": {
  "t": "Lagodekhi National Park. Forest.jpg",
  "a": "Aleksey Muhranoff",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lagodekhi_National_Park._Forest.jpg"
 },
 "лето": {
  "t": "Field Hamois Belgium Luc Viatour.jpg",
  "a": "Luc Viatour",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Field_Hamois_Belgium_Luc_Viatour.jpg"
 },
 "лист": {
  "t": "Leaf 1 web.jpg",
  "a": "Jon Sullivan",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Leaf_1_web.jpg"
 },
 "литература": {
  "t": "Bibliothèque de l'Assemblée Nationale (Lunon).jpg",
  "a": "Baptiste ROUSSEL",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Biblioth%C3%A8que_de_l%27Assembl%C3%A9e_Nationale_(Lunon).jpg"
 },
 "лицо": {
  "t": "Human faces.jpg",
  "a": "Autisticeditor 20",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Human_faces.jpg"
 },
 "лодка": {
  "t": "Motorboat at Kankaria lake.JPG",
  "a": "Kondicherry",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Motorboat_at_Kankaria_lake.JPG"
 },
 "лошадь": {
  "t": "Pernod Al Ariba 0046b.jpg",
  "a": "Thomas Reich",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Pernod_Al_Ariba_0046b.jpg"
 },
 "любовь": {
  "t": "Sri Lankan woman and child.jpg",
  "a": "Steve Evans from India and USA",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sri_Lankan_woman_and_child.jpg"
 },
 "медведь": {
  "t": "Ursidae-01.jpg",
  "a": "MathKnight",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Ursidae-01.jpg"
 },
 "медицина": {
  "t": "Changing lives for girls and women every week (12330467294).jpg",
  "a": "Jessica Lea of DFID - UK Department for International Development",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Changing_lives_for_girls_and_women_every_week_(12330467294).jpg"
 },
 "менеджер": {
  "t": "Female sales manager Sri Lanka.JPG",
  "a": "Peter van der Sluijs",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Female_sales_manager_Sri_Lanka.JPG"
 },
 "метро": {
  "t": "Northbound Link train at Othello Station (31003193486).jpg",
  "a": "SounderBruce from Seattle, United States",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Northbound_Link_train_at_Othello_Station_(31003193486).jpg"
 },
 "минута": {
  "t": "La minute (315630347).jpg",
  "a": "Fanch from Paris, France",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:La_minute_(315630347).jpg"
 },
 "митинг": {
  "t": "Anti-government protest in Sri Lanka 2022.jpg",
  "a": "AntanO",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Anti-government_protest_in_Sri_Lanka_2022.jpg"
 },
 "мода": {
  "t": "Siegel & Stockman. The Brandery Winter Edition 2010.jpg",
  "a": "thebrandery",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Siegel_%26_Stockman._The_Brandery_Winter_Edition_2010.jpg"
 },
 "молния": {
  "t": "Lightning3.jpg",
  "a": "U.S. Air Force photo by Edward Aspera Jr.",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Lightning3.jpg"
 },
 "море": {
  "t": "POL 2007 08 04 Jaroslawiec zachodniopomorskie 02.JPG",
  "a": "Alina Zienowicz Ala z",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:POL_2007_08_04_Jaroslawiec_zachodniopomorskie_02.JPG"
 },
 "мост": {
  "t": "Mainz-Theodor-Heuss-Bruecke-2005-05-16a.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mainz-Theodor-Heuss-Bruecke-2005-05-16a.jpg"
 },
 "мотоцикл": {
  "t": "2018 FIM Ice Speedway Gladiators World Championship - GP 7 Niedermaier-5563.jpg",
  "a": "Isiwal",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2018_FIM_Ice_Speedway_Gladiators_World_Championship_-_GP_7_Niedermaier-5563.jpg"
 },
 "мужчина": {
  "t": "Представители мужского пола.jpg",
  "a": "Ekaterina Stakgrunvald",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9F%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D0%B8_%D0%BC%D1%83%D0%B6%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%BF%D0%BE%D0%BB%D0%B0.jpg"
 },
 "музей": {
  "t": "Museo Chileno de Arte Precolombino - 2020 - 10.jpg",
  "a": "LuisCG11",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Museo_Chileno_de_Arte_Precolombino_-_2020_-_10.jpg"
 },
 "музыка": {
  "t": "Trompette - corps.JPG",
  "a": "Eusebius",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Trompette_-_corps.JPG"
 },
 "музыкант": {
  "t": "Musician Playing Ravanhatta at Mehrangarh, Rajasthan, India.jpg",
  "a": "Harshil Mehta",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Musician_Playing_Ravanhatta_at_Mehrangarh,_Rajasthan,_India.jpg"
 },
 "мысль": {
  "t": "Rodin Mislityel.jpg",
  "a": "Завсегдатай",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Rodin_Mislityel.jpg"
 },
 "мышка": {
  "t": "Fancy mice.jpg",
  "a": "User Polarqueen on en.wikipedia",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fancy_mice.jpg"
 },
 "мышь": {
  "t": "Apodemus sylvaticus bosmuis.jpg",
  "a": "Rasbak",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Apodemus_sylvaticus_bosmuis.jpg"
 },
 "мяч": {
  "t": "Handball the ball.jpg",
  "a": "Armin Kuebelbeck",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Handball_the_ball.jpg"
 },
 "надежда": {
  "t": "Hopeful.jpg",
  "a": "Ahill34",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hopeful.jpg"
 },
 "напиток": {
  "t": "15-09-26-RalfR-WLC-0025.jpg",
  "a": "Ralf Roletschek",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0025.jpg"
 },
 "наркотик": {
  "t": "Bayer Heroin bottle.jpg",
  "a": "Mpv_51 at English Wikipedia",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bayer_Heroin_bottle.jpg"
 },
 "насекомое": {
  "t": "Insecta Diversity.jpg",
  "a": "See his respective owners",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Insecta_Diversity.jpg"
 },
 "ножка": {
  "t": "Amanita velosa.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Amanita_velosa.jpg"
 },
 "ноутбук": {
  "t": "2008 MacBook Aluminium.jpg",
  "a": "JaayJay",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2008_MacBook_Aluminium.jpg"
 },
 "ночь": {
  "t": "Парк ночью в Денизли.jpg",
  "a": "Amin Diary",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B0%D1%80%D0%BA_%D0%BD%D0%BE%D1%87%D1%8C%D1%8E_%D0%B2_%D0%94%D0%B5%D0%BD%D0%B8%D0%B7%D0%BB%D0%B8.jpg"
 },
 "обед": {
  "t": "Filet de bœuf.jpg",
  "a": "Ɱ",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Filet_de_b%C5%93uf.jpg"
 },
 "облако": {
  "t": "Clouds, cloudscape over Lombok Strait, Bali Sea, Gili Islands, West Nusa Tenggara, Indonesia.jpg",
  "a": "Vyacheslav Argenberg",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Clouds,_cloudscape_over_Lombok_Strait,_Bali_Sea,_Gili_Islands,_West_Nusa_Tenggara,_Indonesia.jpg"
 },
 "обувь": {
  "t": "King Street Sneak.JPG",
  "a": "Samuelchoong",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:King_Street_Sneak.JPG"
 },
 "общество": {
  "t": "Lao Mangkong family eats together (square).JPG",
  "a": "BigBrotherMouse",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lao_Mangkong_family_eats_together_(square).JPG"
 },
 "озеро": {
  "t": "Bariloche- Argentina2.jpg",
  "a": "Chipppy",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Bariloche-_Argentina2.jpg"
 },
 "окно": {
  "t": "Վերին կամարազարդ.JPG",
  "a": "XenonX88",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D5%8E%D5%A5%D6%80%D5%AB%D5%B6_%D5%AF%D5%A1%D5%B4%D5%A1%D6%80%D5%A1%D5%A6%D5%A1%D6%80%D5%A4.JPG"
 },
 "олимпиада": {
  "t": "Olympiastadion, Múnich, Alemania 2012-04-28, DD 06.JPG",
  "a": "Diego Delso",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Olympiastadion,_M%C3%BAnich,_Alemania_2012-04-28,_DD_06.JPG"
 },
 "отец": {
  "t": "Father's love (cropped).jpg",
  "a": "Hripsime Poghosyan",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Father%27s_love_(cropped).jpg"
 },
 "офис": {
  "t": "Deutsche-Bank-Frankfurt-am-Main.jpg",
  "a": "Raimond Spekking",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Deutsche-Bank-Frankfurt-am-Main.jpg"
 },
 "офицер": {
  "t": "Royal Military Academy Sandhurst inspection of new Colours, June 2005.jpg",
  "a": "Charles J Sharp",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Royal_Military_Academy_Sandhurst_inspection_of_new_Colours,_June_2005.jpg"
 },
 "палец": {
  "t": "Thumbs up.jpg",
  "a": "Сведения об авторе отсутствуют или не читаются программно. Предположительно Dben",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Thumbs_up.jpg"
 },
 "пальто": {
  "t": "Covert Coat.jpg",
  "a": "Toxophilus",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Covert_Coat.jpg"
 },
 "памятник": {
  "t": "Monumento ao Cristo Redentor.jpg",
  "a": "Halley Pacheco de Oliveira",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Monumento_ao_Cristo_Redentor.jpg"
 },
 "парк": {
  "t": "Halleyparknovember b (cropped).jpg",
  "a": "File:Halleyparknovember.jpg: Celco85\nderivative work: Georgfotoart",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Halleyparknovember_b_(cropped).jpg"
 },
 "паспорт": {
  "t": "Passports-assorted.jpg",
  "a": "Normadic at English Wikipedia, User:Quistnix, बिजय पोख्रेल, and the PRC Governme",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Passports-assorted.jpg"
 },
 "пассажир": {
  "t": "Passengers on a Boat.JPG",
  "a": "TriviaKing (talk)DWS",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Passengers_on_a_Boat.JPG"
 },
 "пасха": {
  "t": "Paskha2.jpg",
  "a": "Mitrius",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Paskha2.jpg"
 },
 "певица": {
  "t": "2018-11-02 Konzert -The Hellfreaks- in -Ilvers Musikbar- in Erfurt IMG 3414 LR10 by Stepro.jpg",
  "a": "Steffen Prößdorf",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:2018-11-02_Konzert_-The_Hellfreaks-_in_-Ilvers_Musikbar-_in_Erfurt_IMG_3414_LR10_by_Stepro.jpg"
 },
 "переулок": {
  "t": "Bobrov.JPG",
  "a": "Andres rus",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Bobrov.JPG"
 },
 "пиво": {
  "t": "Weizenbier.jpg",
  "a": "Trexer",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Weizenbier.jpg"
 },
 "пистолет": {
  "t": "Pistolet makarova pm travmatik com by-sa.jpg",
  "a": "Stanislav S. Yanchenko",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Pistolet_makarova_pm_travmatik_com_by-sa.jpg"
 },
 "плавание": {
  "t": "EK Zwemmen 2006 100m vlinder vrouwen.jpg",
  "a": "Изначально этот файл был загружен участником McSmit из нидерландский Википедия",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:EK_Zwemmen_2006_100m_vlinder_vrouwen.jpg"
 },
 "планета": {
  "t": "Mercury in color - Prockter07-edit1.jpg",
  "a": "National Aeronautics and Space Administration/Johns Hopkins University Applied P",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Mercury_in_color_-_Prockter07-edit1.jpg"
 },
 "площадь": {
  "t": "Piazza della Signoria.jpg",
  "a": "Samuli Lintula",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Piazza_della_Signoria.jpg"
 },
 "пляж": {
  "t": "Beach at Fort Lauderdale.jpg",
  "a": "Daniel Dudek",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Beach_at_Fort_Lauderdale.jpg"
 },
 "повреждение": {
  "t": "Lokomotiva 162 011-1 po nehodě.jpg",
  "a": "Michal Rattman",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lokomotiva_162_011-1_po_nehod%C4%9B.jpg"
 },
 "погода": {
  "t": "Stormclouds.jpg",
  "a": "Lipton sale из английский Википедия",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Stormclouds.jpg"
 },
 "поезд": {
  "t": "PRR 33164.jpg",
  "a": "Niagara",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:PRR_33164.jpg"
 },
 "пол": {
  "t": "Parquet flooring in Musée des arts décoratifs de Strasbourg.jpg",
  "a": "Amada44",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Parquet_flooring_in_Mus%C3%A9e_des_arts_d%C3%A9coratifs_de_Strasbourg.jpg"
 },
 "поле": {
  "t": "Iglesia de Nuestra Señora de La Blanca, Cardejón, España, 2012-09-01, DD 02.JPG",
  "a": "Diego Delso",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Iglesia_de_Nuestra_Se%C3%B1ora_de_La_Blanca,_Cardej%C3%B3n,_Espa%C3%B1a,_2012-09-01,_DD_02.JPG"
 },
 "политика": {
  "t": "Mavzolej kremlin.jpg",
  "a": "ангкок",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mavzolej_kremlin.jpg"
 },
 "полиция": {
  "t": "HH Polizeihauptmeister MZ.jpg",
  "a": "Daniel Schwen",
  "l": "CC BY-SA 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:HH_Polizeihauptmeister_MZ.jpg"
 },
 "полковник": {
  "t": "VladikavkazMP-2017-11.jpg",
  "a": "Екатерина Смола",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:VladikavkazMP-2017-11.jpg"
 },
 "посольство": {
  "t": "Посольство Греции в Москве, январь 2007.jpg",
  "a": "Dzerod из русский Википедия",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BE%D1%81%D0%BE%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE_%D0%93%D1%80%D0%B5%D1%86%D0%B8%D0%B8_%D0%B2_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B5,_%D1%8F%D0%BD%D0%B2%D0%B0%D1%80%D1%8C_2007.jpg"
 },
 "почта": {
  "t": "HK Postman Collect Letters.JPG",
  "a": "Chong Fat",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:HK_Postman_Collect_Letters.JPG"
 },
 "председатель": {
  "t": "Agustin Vásquez Gómez, chairperson of OPCW's Fourth Review Conference, 2018.jpg",
  "a": "OPCW",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Agustin_V%C3%A1squez_G%C3%B3mez,_chairperson_of_OPCW%27s_Fourth_Review_Conference,_2018.jpg"
 },
 "провод": {
  "t": "Шкаф 093136.jpg",
  "a": "Mixabest",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A8%D0%BA%D0%B0%D1%84_093136.jpg"
 },
 "профессор": {
  "t": "Professor and architecture students.jpg",
  "a": "Sverre Flack",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Professor_and_architecture_students.jpg"
 },
 "птица": {
  "t": "Kleiber Flug.jpg",
  "a": "C. Robiller / naturlichter.de (Hyla meridionalis)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kleiber_Flug.jpg"
 },
 "пуля": {
  "t": "GP11 coupe.JPG",
  "a": "Bouterolle",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:GP11_coupe.JPG"
 },
 "пьеса": {
  "t": "Macbeth (32280144787).jpg",
  "a": "Uark Theatre",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Macbeth_(32280144787).jpg"
 },
 "радиоприёмник": {
  "t": "Icom IC-R7000 radio receiver.jpg",
  "a": "Mspecht",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Icom_IC-R7000_radio_receiver.jpg"
 },
 "река": {
  "t": "River RP.jpg",
  "a": "Jlwad",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:River_RP.jpg"
 },
 "реклама": {
  "t": "1 times square night 2013.jpg",
  "a": "chensiyuan",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:1_times_square_night_2013.jpg"
 },
 "ресторан": {
  "t": "AntoinesDiningRoom8Oct07A.jpg",
  "a": "Infrogmation of New Orleans",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:AntoinesDiningRoom8Oct07A.jpg"
 },
 "родитель": {
  "t": "Parents and their baby.jpg",
  "a": "sheldonl",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Parents_and_their_baby.jpg"
 },
 "рот": {
  "t": "Lion Showing off His Mouth (21454262492).jpg",
  "a": "Eric Kilby from Somerville, MA, USA",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Lion_Showing_off_His_Mouth_(21454262492).jpg"
 },
 "рубашка": {
  "t": "Blue Business Shirt.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Blue_Business_Shirt.jpg"
 },
 "рука": {
  "t": "Две острые палочки, сложным образом зажатые в руке человека.JPG",
  "a": "Weldis",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%94%D0%B2%D0%B5_%D0%BE%D1%81%D1%82%D1%80%D1%8B%D0%B5_%D0%BF%D0%B0%D0%BB%D0%BE%D1%87%D0%BA%D0%B8,_%D1%81%D0%BB%D0%BE%D0%B6%D0%BD%D1%8B%D0%BC_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%BC_%D0%B7%D0%B0%D0%B6%D0%B0%D1%82%D1%8B%D0%B5_%D0%B2_%D1%80%D1%83%D0%BA%D0%B5_%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA%D0%B0.JPG"
 },
 "рыба": {
  "t": "Balantiocheilos melanopterus - Karlsruhe Zoo 02 (cropped).jpg",
  "a": "H. Zell",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Balantiocheilos_melanopterus_-_Karlsruhe_Zoo_02_(cropped).jpg"
 },
 "рынок": {
  "t": "Saúde Street Market 3.jpg",
  "a": "Wilfredor",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sa%C3%BAde_Street_Market_3.jpg"
 },
 "салат": {
  "t": "Kaspressknödel mit Salat.jpg",
  "a": "Kritzolina",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Kaspresskn%C3%B6del_mit_Salat.jpg"
 },
 "самолёт": {
  "t": "Ильюшин Ил-96 74393202018, Москва - Внуково RP20591.jpg",
  "a": "Павел Аджигильдяев",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%98%D0%BB%D1%8C%D1%8E%D1%88%D0%B8%D0%BD_%D0%98%D0%BB-96_74393202018,_%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0_-_%D0%92%D0%BD%D1%83%D0%BA%D0%BE%D0%B2%D0%BE_RP20591.jpg"
 },
 "свадьба": {
  "t": "Hindu wedding rituals b (cropped).jpg",
  "a": "Will",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Hindu_wedding_rituals_b_(cropped).jpg"
 },
 "свинья": {
  "t": "Поросята (гибридные).jpg",
  "a": "Собственная работа",
  "l": "CC BY 3.0",
  "u": "https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:%D0%9F%D0%BE%D1%80%D0%BE%D1%81%D1%8F%D1%82%D0%B0_(%D0%B3%D0%B8%D0%B1%D1%80%D0%B8%D0%B4%D0%BD%D1%8B%D0%B5).jpg"
 },
 "сентябрь": {
  "t": "September.jpg",
  "a": "Струнин В.С",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:September.jpg"
 },
 "сеть": {
  "t": "A fishing net in Brandon Creek - geograph.org.uk - 921094.jpg",
  "a": "Peter Church",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:A_fishing_net_in_Brandon_Creek_-_geograph.org.uk_-_921094.jpg"
 },
 "снег": {
  "t": "Fresh snow.JPG",
  "a": "Wuhazet - Henryk Żychowski",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fresh_snow.JPG"
 },
 "собака": {
  "t": "Huskiesatrest.jpg",
  "a": "M. Rehemtulla",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Huskiesatrest.jpg"
 },
 "собор": {
  "t": "Catedral de Cádiz, España, 2015-12-08, DD 69-71 HDR.JPG",
  "a": "Diego Delso",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Catedral_de_C%C3%A1diz,_Espa%C3%B1a,_2015-12-08,_DD_69-71_HDR.JPG"
 },
 "солдат": {
  "t": "Chinese soldier on Tienanmen Square.jpg",
  "a": "Luo Shaoyang from Beijing, China",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Chinese_soldier_on_Tienanmen_Square.jpg"
 },
 "солнце": {
  "t": "The Sun in white light.jpg",
  "a": "Matúš Motlo",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:The_Sun_in_white_light.jpg"
 },
 "сон": {
  "t": "Спящий кот.jpg",
  "a": "Sosisda33",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%BF%D1%8F%D1%89%D0%B8%D0%B9_%D0%BA%D0%BE%D1%82.jpg"
 },
 "спорт": {
  "t": "20180922 UCI Road World Championships Innsbruck Team AG2R La Mondiale 850 7022.jpg",
  "a": "Granada",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:20180922_UCI_Road_World_Championships_Innsbruck_Team_AG2R_La_Mondiale_850_7022.jpg"
 },
 "спортзал": {
  "t": "Amsterdam - Gymnasium - 0591.jpg",
  "a": "Jorge Royan",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Amsterdam_-_Gymnasium_-_0591.jpg"
 },
 "стадион": {
  "t": "Narendra Modi Stadium view from the gallery.jpg",
  "a": "A Cricket Premi",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Narendra_Modi_Stadium_view_from_the_gallery.jpg"
 },
 "стекло": {
  "t": "Drinkware.jpg",
  "a": "rawpixel.com",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Drinkware.jpg"
 },
 "стена": {
  "t": "BlackstoneWall.jpg",
  "a": "Common-Pics",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:BlackstoneWall.jpg"
 },
 "стол": {
  "t": "2008-04-13 Expandable table expanding.jpg",
  "a": "Ildar Sagdejev (Specious)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2008-04-13_Expandable_table_expanding.jpg"
 },
 "строительство": {
  "t": "Construction site in Cologne, Germany (2017).jpg",
  "a": "Whiteghost.ink",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Construction_site_in_Cologne,_Germany_(2017).jpg"
 },
 "суд": {
  "t": "Supreme Court of the United Kingdom, Court 1 Interior, London, UK - Diliff.jpg",
  "a": "Diliff",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Supreme_Court_of_the_United_Kingdom,_Court_1_Interior,_London,_UK_-_Diliff.jpg"
 },
 "сцена": {
  "t": "SFOperaHouse2 (8189967420).jpg",
  "a": "Ed and Eddie from Palo Alto, USA",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:SFOperaHouse2_(8189967420).jpg"
 },
 "таблетка": {
  "t": "FlattenedRoundPills.jpg",
  "a": "David Richfield",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:FlattenedRoundPills.jpg"
 },
 "такси": {
  "t": "TAXI.jpg",
  "a": "Petar Milošević",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:TAXI.jpg"
 },
 "тарелка": {
  "t": "Бухара, Кукельдаш, тарелка (2).jpg",
  "a": "Nikolai Bulykin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%91%D1%83%D1%85%D0%B0%D1%80%D0%B0,_%D0%9A%D1%83%D0%BA%D0%B5%D0%BB%D1%8C%D0%B4%D0%B0%D1%88,_%D1%82%D0%B0%D1%80%D0%B5%D0%BB%D0%BA%D0%B0_(2).jpg"
 },
 "театр": {
  "t": "Panorámica interior del Teatro Colón.jpg",
  "a": "Martin Bordagaray",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Panor%C3%A1mica_interior_del_Teatro_Col%C3%B3n.jpg"
 },
 "телевизор": {
  "t": "Neptun M547 BT.JPG",
  "a": "Tyktyk",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Neptun_M547_BT.JPG"
 },
 "телефон": {
  "t": "Советский телефон ТА-68.JPG",
  "a": "Andshel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%BE%D0%B2%D0%B5%D1%82%D1%81%D0%BA%D0%B8%D0%B9_%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD_%D0%A2%D0%90-68.JPG"
 },
 "теннис": {
  "t": "Court 18 long view.JPG",
  "a": "Clavecin",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Court_18_long_view.JPG"
 },
 "технология": {
  "t": "Dampfturbine Montage01.jpg",
  "a": "Siemens Pressebild",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Dampfturbine_Montage01.jpg"
 },
 "товар": {
  "t": "Mediq Sverige Kungsbacka warehouse.jpg",
  "a": "Gwan Kho",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mediq_Sverige_Kungsbacka_warehouse.jpg"
 },
 "торговля": {
  "t": "Самарканд, торговля на автовокзале (1).jpg",
  "a": "Nikolai Bulykin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B0%D0%BC%D0%B0%D1%80%D0%BA%D0%B0%D0%BD%D0%B4,_%D1%82%D0%BE%D1%80%D0%B3%D0%BE%D0%B2%D0%BB%D1%8F_%D0%BD%D0%B0_%D0%B0%D0%B2%D1%82%D0%BE%D0%B2%D0%BE%D0%BA%D0%B7%D0%B0%D0%BB%D0%B5_(1).jpg"
 },
 "торт": {
  "t": "Delicious Birthday Cake (14346969741).jpg",
  "a": "Jonathan Rolande from Worthing, England",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Delicious_Birthday_Cake_(14346969741).jpg"
 },
 "трава": {
  "t": "Steppe flora, Wild flowers, Rostov-on-Don, Russia.jpg",
  "a": "Vyacheslav Argenberg",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Steppe_flora,_Wild_flowers,_Rostov-on-Don,_Russia.jpg"
 },
 "тренер": {
  "t": "Torre and coaches.jpg",
  "a": "keithallison",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Torre_and_coaches.jpg"
 },
 "туман": {
  "t": "Fog in Moscow Oblast.jpg",
  "a": "Россин Денис Владимирович",
  "l": "CC BY 2.5",
  "u": "https://commons.wikimedia.org/wiki/File:Fog_in_Moscow_Oblast.jpg"
 },
 "турист": {
  "t": "Au dessus du ciel (Piton de la Fournaise, Ile de la Réunion).jpg",
  "a": "indeepdark",
  "l": "CC BY-SA 1.0",
  "u": "https://commons.wikimedia.org/wiki/File:Au_dessus_du_ciel_(Piton_de_la_Fournaise,_Ile_de_la_R%C3%A9union).jpg"
 },
 "тюрьма": {
  "t": "Justizvollzugsanstalt Memmingen-2.jpg",
  "a": "Tobias \"ToMar\" Maier",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Justizvollzugsanstalt_Memmingen-2.jpg"
 },
 "улица": {
  "t": "Реконструкция Пятницкой улицы (июль 2014) (07).jpeg",
  "a": "stroi.mos.ru",
  "l": "CC BY 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A0%D0%B5%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%9F%D1%8F%D1%82%D0%BD%D0%B8%D1%86%D0%BA%D0%BE%D0%B9_%D1%83%D0%BB%D0%B8%D1%86%D1%8B_(%D0%B8%D1%8E%D0%BB%D1%8C_2014)_(07).jpeg"
 },
 "университет": {
  "t": "University of Salamanca.jpg",
  "a": "",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:University_of_Salamanca.jpg"
 },
 "упражнение": {
  "t": "Sea surviving training.jpg",
  "a": "Deep silence (Mikaël Restoux)",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Sea_surviving_training.jpg"
 },
 "урок": {
  "t": "Урок химии.jpg",
  "a": "Tsaryov357",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%A3%D1%80%D0%BE%D0%BA_%D1%85%D0%B8%D0%BC%D0%B8%D0%B8.jpg"
 },
 "учёный": {
  "t": "InvestigadoresUR.JPG",
  "a": "Urcomunicacion",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:InvestigadoresUR.JPG"
 },
 "фотоаппарат": {
  "t": "0198 Mamiya Universal 75mm f5.6 lens with finder (5246290647).jpg",
  "a": "Zebrio from Tokyo, Japan",
  "l": "CC BY-SA 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:0198_Mamiya_Universal_75mm_f5.6_lens_with_finder_(5246290647).jpg"
 },
 "фотография": {
  "t": "Mamiya RB67 - dos 120.jpg",
  "a": "Eusebius",
  "l": "CC BY 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Mamiya_RB67_-_dos_120.jpg"
 },
 "химия": {
  "t": "Chemicals in flasks.jpg",
  "a": "Joe Sullivan",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Chemicals_in_flasks.jpg"
 },
 "холод": {
  "t": "Antarctic iceberg, 2001 -2.jpg",
  "a": "Georges Nijs from Diepenbeek, Belgium",
  "l": "CC BY 2.0",
  "u": "https://commons.wikimedia.org/wiki/File:Antarctic_iceberg,_2001_-2.jpg"
 },
 "хор": {
  "t": "Gregoriaans koor2.jpg",
  "a": "Raf Verniest",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Gregoriaans_koor2.jpg"
 },
 "храм": {
  "t": "Philae temple at night.jpg",
  "a": "Moh hakem",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Philae_temple_at_night.jpg"
 },
 "христианский": {
  "t": "Church of the Holy Sepulchre by Gerd Eichmann (cropped).jpg",
  "a": "Gerd Eichmann",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:Church_of_the_Holy_Sepulchre_by_Gerd_Eichmann_(cropped).jpg"
 },
 "чай": {
  "t": "Longjing-steeping-tallglass.jpg",
  "a": "Kaminix",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Longjing-steeping-tallglass.jpg"
 },
 "шахматы": {
  "t": "Бухара, Кукельдаш, шахматы.jpg",
  "a": "Nikolai Bulykin",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%91%D1%83%D1%85%D0%B0%D1%80%D0%B0,_%D0%9A%D1%83%D0%BA%D0%B5%D0%BB%D1%8C%D0%B4%D0%B0%D1%88,_%D1%88%D0%B0%D1%85%D0%BC%D0%B0%D1%82%D1%8B.jpg"
 },
 "школа": {
  "t": "Молодецьке (Маньківський р-н). Школа.jpg",
  "a": "Nikride",
  "l": "CC BY-SA 4.0",
  "u": "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D0%BB%D0%BE%D0%B4%D0%B5%D1%86%D1%8C%D0%BA%D0%B5_(%D0%9C%D0%B0%D0%BD%D1%8C%D0%BA%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D1%80-%D0%BD)._%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0.jpg"
 },
 "шоссе": {
  "t": "Gotthard alte Strasse.jpg",
  "a": "upload by Adrian Michael",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Gotthard_alte_Strasse.jpg"
 },
 "эволюция": {
  "t": "Fishapod evolution.jpg",
  "a": "Maija Karala",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:Fishapod_evolution.jpg"
 },
 "электричество": {
  "t": "2015 Freileitungen bei Marxheim.jpg",
  "a": "Kreuzschnabel",
  "l": "CC BY-SA 3.0",
  "u": "https://commons.wikimedia.org/wiki/File:2015_Freileitungen_bei_Marxheim.jpg"
 }
};
