/* Generated by tools/build_images.py — do not edit. Public-domain and CC0
   photographs from Wikimedia Commons for the words the units teach, keyed
   on the bare word. CREDITS carries each file's title, author and licence. */

export const IMAGES = {
  "автомат": require("../assets/img/0004.jpg"),
  "ад": require("../assets/img/0008.jpg"),
  "ангел": require("../assets/img/0013.jpg"),
  "арест": require("../assets/img/0018.jpg"),
  "армия": require("../assets/img/0019.jpg"),
  "бабушка": require("../assets/img/0026.jpg"),
  "бал": require("../assets/img/0028.jpg"),
  "балет": require("../assets/img/0029.jpg"),
  "банк": require("../assets/img/0031.jpg"),
  "берег": require("../assets/img/0038.jpg"),
  "близнец": require("../assets/img/0046.jpg"),
  "бог": require("../assets/img/0048.jpg"),
  "болезнь": require("../assets/img/0050.jpg"),
  "брат": require("../assets/img/0057.jpg"),
  "бригада": require("../assets/img/0058.jpg"),
  "вакцина": require("../assets/img/0067.jpg"),
  "внук": require("../assets/img/0085.jpg"),
  "внучка": require("../assets/img/0086.jpg"),
  "войско": require("../assets/img/0091.jpg"),
  "вор": require("../assets/img/0098.jpg"),
  "воспитание": require("../assets/img/0101.jpg"),
  "враг": require("../assets/img/0102.jpg"),
  "газ": require("../assets/img/0111.jpg"),
  "газета": require("../assets/img/0112.jpg"),
  "грех": require("../assets/img/0133.jpg"),
  "дед": require("../assets/img/0147.jpg"),
  "дедушка": require("../assets/img/0148.jpg"),
  "дождь": require("../assets/img/0163.jpg"),
  "доктор": require("../assets/img/0166.jpg"),
  "душа": require("../assets/img/0177.jpg"),
  "дядя": require("../assets/img/0178.jpg"),
  "еда": require("../assets/img/0180.jpg"),
  "живопись": require("../assets/img/0185.jpg"),
  "заболевание": require("../assets/img/0191.jpg"),
  "забор": require("../assets/img/0192.jpg"),
  "изобретение": require("../assets/img/0217.jpg"),
  "икона": require("../assets/img/0219.jpg"),
  "инженер": require("../assets/img/0220.jpg"),
  "казнь": require("../assets/img/0231.jpg"),
  "капитан": require("../assets/img/0235.jpg"),
  "карта": require("../assets/img/0237.jpg"),
  "кнопка": require("../assets/img/0256.jpg"),
  "ковёр": require("../assets/img/0257.jpg"),
  "крыло": require("../assets/img/0295.jpg"),
  "лекарство": require("../assets/img/0303.jpg"),
  "лес": require("../assets/img/0305.jpg"),
  "математика": require("../assets/img/0328.jpg"),
  "мебель": require("../assets/img/0332.jpg"),
  "медицина": require("../assets/img/0334.jpg"),
  "медсестра": require("../assets/img/0335.jpg"),
  "муж": require("../assets/img/0358.jpg"),
  "мужчина": require("../assets/img/0359.jpg"),
  "музыка": require("../assets/img/0361.jpg"),
  "музыкант": require("../assets/img/0362.jpg"),
  "мяч": require("../assets/img/0369.jpg"),
  "мёд": require("../assets/img/0370.jpg"),
  "наказание": require("../assets/img/0374.jpg"),
  "наркомания": require("../assets/img/0378.jpg"),
  "наркотик": require("../assets/img/0379.jpg"),
  "невеста": require("../assets/img/0389.jpg"),
  "новость": require("../assets/img/0393.jpg"),
  "носок": require("../assets/img/0399.jpg"),
  "облако": require("../assets/img/0404.jpg"),
  "образование": require("../assets/img/0406.jpg"),
  "обстановка": require("../assets/img/0407.jpg"),
  "одежда": require("../assets/img/0413.jpg"),
  "остров": require("../assets/img/0420.jpg"),
  "офицер": require("../assets/img/0429.jpg"),
  "официант": require("../assets/img/0430.jpg"),
  "пасха": require("../assets/img/0444.jpg"),
  "певец": require("../assets/img/0446.jpg"),
  "певица": require("../assets/img/0447.jpg"),
  "песня": require("../assets/img/0452.jpg"),
  "писатель": require("../assets/img/0457.jpg"),
  "пистолет": require("../assets/img/0458.jpg"),
  "платье": require("../assets/img/0464.jpg"),
  "победа": require("../assets/img/0468.jpg"),
  "подруга": require("../assets/img/0473.jpg"),
  "показание": require("../assets/img/0476.jpg"),
  "преступление": require("../assets/img/0506.jpg"),
  "преступник": require("../assets/img/0507.jpg"),
  "противник": require("../assets/img/0521.jpg"),
  "профессор": require("../assets/img/0522.jpg"),
  "пуговица": require("../assets/img/0524.jpg"),
  "распятие": require("../assets/img/0537.jpg"),
  "родитель": require("../assets/img/0554.jpg"),
  "роман": require("../assets/img/0556.jpg"),
  "рубль": require("../assets/img/0559.jpg"),
  "самоубийство": require("../assets/img/0569.jpg"),
  "сахар": require("../assets/img/0571.jpg"),
  "сестра": require("../assets/img/0582.jpg"),
  "сигнал": require("../assets/img/0584.jpg"),
  "собор": require("../assets/img/0594.jpg"),
  "сок": require("../assets/img/0596.jpg"),
  "солдат": require("../assets/img/0597.jpg"),
  "сон": require("../assets/img/0600.jpg"),
  "спина": require("../assets/img/0605.jpg"),
  "спинка": require("../assets/img/0606.jpg"),
  "спорт": require("../assets/img/0608.jpg"),
  "справедливость": require("../assets/img/0611.jpg"),
  "стул": require("../assets/img/0633.jpg"),
  "судья": require("../assets/img/0637.jpg"),
  "супруг": require("../assets/img/0639.jpg"),
  "супруга": require("../assets/img/0640.jpg"),
  "театр": require("../assets/img/0650.jpg"),
  "телевидение": require("../assets/img/0651.jpg"),
  "техник": require("../assets/img/0660.jpg"),
  "товарищ": require("../assets/img/0664.jpg"),
  "труп": require("../assets/img/0672.jpg"),
  "тюрьма": require("../assets/img/0679.jpg"),
  "тёща": require("../assets/img/0682.jpg"),
  "убийство": require("../assets/img/0684.jpg"),
  "урок": require("../assets/img/0692.jpg"),
  "ус": require("../assets/img/0693.jpg"),
  "фамилия": require("../assets/img/0702.jpg"),
  "шкаф": require("../assets/img/0741.jpg"),
  "яйцо": require("../assets/img/0764.jpg"),
};

export const CREDITS = {
 "автомат": {
  "t": "Control room pt tupper.jpg",
  "a": "Achim Hering",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Control_room_pt_tupper.jpg"
 },
 "ад": {
  "t": "Fra Angelico 010.jpg",
  "a": "Fra Angelico",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Fra_Angelico_010.jpg"
 },
 "ангел": {
  "t": "Angel of the Annunciation MET DP167921.jpg",
  "a": "",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Angel_of_the_Annunciation_MET_DP167921.jpg"
 },
 "арест": {
  "t": "ICE.XCheckII.3cops1arrest.jpg",
  "a": "U.S. Immigration and Customs Enforcement (Department of Homeland Security)",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:ICE.XCheckII.3cops1arrest.jpg"
 },
 "армия": {
  "t": "250th United States Army Birthday Parade in Washington, D.C. on June 14, 2025 - 262.jpg",
  "a": "usarmyband",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:250th_United_States_Army_Birthday_Parade_in_Washington,_D.C._on_June_14,_2025_-_262.jpg"
 },
 "бабушка": {
  "t": "The Favorite by Georgios Iakovidis.jpg",
  "a": "Georgios Jakobides",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Favorite_by_Georgios_Iakovidis.jpg"
 },
 "бал": {
  "t": "Many balls.jpg",
  "a": "Conrad 7",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Many_balls.jpg"
 },
 "балет": {
  "t": "Edgar Degas - La Classe de danse.jpg",
  "a": "Edgar Degas",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Edgar_Degas_-_La_Classe_de_danse.jpg"
 },
 "банк": {
  "t": "London.bankofengland.arp.jpg",
  "a": "Adrian Pingstone",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:London.bankofengland.arp.jpg"
 },
 "берег": {
  "t": "London.bankofengland.arp.jpg",
  "a": "Adrian Pingstone",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:London.bankofengland.arp.jpg"
 },
 "близнец": {
  "t": "Mauch Twins.jpg",
  "a": "William A. Macis",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Mauch_Twins.jpg"
 },
 "бог": {
  "t": "Michelangelo, Creation of Adam 04.jpg",
  "a": "Michelangelo",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Michelangelo,_Creation_of_Adam_04.jpg"
 },
 "болезнь": {
  "t": "Michael Ancher, Den syge pige, 1882, KMS4002, Statens Museum for Kunst.jpg",
  "a": "Michael Ancher",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Michael_Ancher,_Den_syge_pige,_1882,_KMS4002,_Statens_Museum_for_Kunst.jpg"
 },
 "брат": {
  "t": "Jackson 5 1969.jpg",
  "a": "Bernie Ilson, Inc., public relations, New York.",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Jackson_5_1969.jpg"
 },
 "бригада": {
  "t": "Latvian platoon at Camp Lejeune.jpg",
  "a": "SGT THOPGMAS W. AMMONS, USA",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Latvian_platoon_at_Camp_Lejeune.jpg"
 },
 "вакцина": {
  "t": "Smallpox vaccine.jpg",
  "a": "Photo Credit: James Gathany\nContent Providers(s): CDC",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Smallpox_vaccine.jpg"
 },
 "внук": {
  "t": "Sauk Indian family by Frank Rinehart 1899.jpg",
  "a": "Frank Rinehart",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Sauk_Indian_family_by_Frank_Rinehart_1899.jpg"
 },
 "внучка": {
  "t": "Sauk Indian family by Frank Rinehart 1899.jpg",
  "a": "Frank Rinehart",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Sauk_Indian_family_by_Frank_Rinehart_1899.jpg"
 },
 "войско": {
  "t": "250th United States Army Birthday Parade in Washington, D.C. on June 14, 2025 - 262.jpg",
  "a": "usarmyband",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:250th_United_States_Army_Birthday_Parade_in_Washington,_D.C._on_June_14,_2025_-_262.jpg"
 },
 "вор": {
  "t": "Paul-Charles Chocarne-Moreau The Cunning Thief.jpg",
  "a": "Paul Chocarne-Moreau",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Paul-Charles_Chocarne-Moreau_The_Cunning_Thief.jpg"
 },
 "воспитание": {
  "t": "Schoolgirls in Bamozai.JPG",
  "a": "Capt. John Severns, U.S. Air Force",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Schoolgirls_in_Bamozai.JPG"
 },
 "враг": {
  "t": "Yevgeny Onegin by Repin.jpg",
  "a": "Ilya Repin",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Yevgeny_Onegin_by_Repin.jpg"
 },
 "газ": {
  "t": "Purplesmoke.jpg",
  "a": "Macluskie",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Purplesmoke.jpg"
 },
 "газета": {
  "t": "NYTimes-Page1-11-11-1918.jpg",
  "a": "Charles Ransom Miller",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:NYTimes-Page1-11-11-1918.jpg"
 },
 "грех": {
  "t": "Jan Brueghel de Oude en Peter Paul Rubens - Het aards paradijs met de zondeval van Adam en Eva.jpg",
  "a": "Peter Paul Rubens / Jan Brueghel the Elder",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Jan_Brueghel_de_Oude_en_Peter_Paul_Rubens_-_Het_aards_paradijs_met_de_zondeval_van_Adam_en_Eva.jpg"
 },
 "дед": {
  "t": "The Favorite by Georgios Iakovidis.jpg",
  "a": "Georgios Jakobides",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Favorite_by_Georgios_Iakovidis.jpg"
 },
 "дедушка": {
  "t": "The Favorite by Georgios Iakovidis.jpg",
  "a": "Georgios Jakobides",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Favorite_by_Georgios_Iakovidis.jpg"
 },
 "дождь": {
  "t": "Hard rain on a roof.jpg",
  "a": "W.carter",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Hard_rain_on_a_roof.jpg"
 },
 "доктор": {
  "t": "Columbia University PhD.jpg",
  "a": "Jjazz76",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Columbia_University_PhD.jpg"
 },
 "душа": {
  "t": "Schiavonetti Soul leaving body 1808.jpg",
  "a": "Luigi Schiavonetti (†1810)",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Schiavonetti_Soul_leaving_body_1808.jpg"
 },
 "дядя": {
  "t": "Uncle and nephew both members of Congress. Uncle and nephew combination in Congress, Rep. Charles A. Eaton of New Jersey, (right) and his nephew Rep. William R. Eaton of Colorado, are both LCCN2016889271 (cropped).jpg",
  "a": "Harris &amp; Ewing, photographer",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Uncle_and_nephew_both_members_of_Congress._Uncle_and_nephew_combination_in_Congress,_Rep._Charles_A._Eaton_of_New_Jersey,_(right)_and_his_nephew_Rep._William_R._Eaton_of_Colorado,_are_both_LCCN2016889271_(cropped).jpg"
 },
 "еда": {
  "t": "Good Food Display - NCI Visuals Online.jpg",
  "a": "Unknown authorUnknown author",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Good_Food_Display_-_NCI_Visuals_Online.jpg"
 },
 "живопись": {
  "t": "Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg",
  "a": "Leonardo da Vinci",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg"
 },
 "заболевание": {
  "t": "Michael Ancher, Den syge pige, 1882, KMS4002, Statens Museum for Kunst.jpg",
  "a": "Michael Ancher",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Michael_Ancher,_Den_syge_pige,_1882,_KMS4002,_Statens_Museum_for_Kunst.jpg"
 },
 "забор": {
  "t": "Westtown.jpg",
  "a": "",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Westtown.jpg"
 },
 "изобретение": {
  "t": "Science and Invention Nov 1928 Cover 2.jpg",
  "a": "Experimenter Publishing",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Science_and_Invention_Nov_1928_Cover_2.jpg"
 },
 "икона": {
  "t": "The Ladder of Divine Ascent Monastery of St Catherine Sinai 12th century.jpg",
  "a": "Pvasiliadis",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Ladder_of_Divine_Ascent_Monastery_of_St_Catherine_Sinai_12th_century.jpg"
 },
 "инженер": {
  "t": "Kitty Joyner - Electrical Engineer - GPN-2000-001933.jpg",
  "a": "NACA",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Kitty_Joyner_-_Electrical_Engineer_-_GPN-2000-001933.jpg"
 },
 "казнь": {
  "t": "Execution of Louis XVI.jpg",
  "a": "Isidore Stanislas Helman / After Charles Monnet",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Execution_of_Louis_XVI.jpg"
 },
 "капитан": {
  "t": "Captain on ship.jpg",
  "a": "Hillebrand Steve, U.S. Fish and Wildlife Service",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Captain_on_ship.jpg"
 },
 "карта": {
  "t": "World Map 1689.JPG",
  "a": "Gerard van Schagen",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:World_Map_1689.JPG"
 },
 "кнопка": {
  "t": "Reserveknapper til Hans' uniform.jpg",
  "a": "Europeana staff photographer",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Reserveknapper_til_Hans%27_uniform.jpg"
 },
 "ковёр": {
  "t": "Wollteppich 1.jpg",
  "a": "Ryj",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Wollteppich_1.jpg"
 },
 "крыло": {
  "t": "Wing.two.arp.600pix.jpg",
  "a": "",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Wing.two.arp.600pix.jpg"
 },
 "лекарство": {
  "t": "The Doctor Luke Fildes crop.jpg",
  "a": "Luke Fildes",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Doctor_Luke_Fildes_crop.jpg"
 },
 "лес": {
  "t": "16 wood samples.jpg",
  "a": "Anonimski",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:16_wood_samples.jpg"
 },
 "математика": {
  "t": "Woman teaching geometry.jpg",
  "a": "Attributed to Meliacin Master",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Woman_teaching_geometry.jpg"
 },
 "мебель": {
  "t": "8th Century BCE Assyrian Plaque from Fort Shalmaneser. in Nimrud.jpg",
  "a": "Artist Unknown",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:8th_Century_BCE_Assyrian_Plaque_from_Fort_Shalmaneser._in_Nimrud.jpg"
 },
 "медицина": {
  "t": "The Doctor Luke Fildes crop.jpg",
  "a": "Luke Fildes",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Doctor_Luke_Fildes_crop.jpg"
 },
 "медсестра": {
  "t": "Nurse checks blood pressure.jpg",
  "a": "Linda Bartlett (Photographer)",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Nurse_checks_blood_pressure.jpg"
 },
 "муж": {
  "t": "Lotto, Lorenzo - Husband and Wife.jpg",
  "a": "Lorenzo Lotto",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Lotto,_Lorenzo_-_Husband_and_Wife.jpg"
 },
 "мужчина": {
  "t": "Outdoors-man-portrait (cropped).jpg",
  "a": "Abhi Puthenpurackal",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Outdoors-man-portrait_(cropped).jpg"
 },
 "музыка": {
  "t": "The Sounds of Earth - GPN-2000-001976.jpg",
  "a": "NASA",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:The_Sounds_of_Earth_-_GPN-2000-001976.jpg"
 },
 "музыкант": {
  "t": "Joan Baez and Bob Dylan.jpg",
  "a": "Rowland Scherman, National Archives and Records Administration",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Joan_Baez_and_Bob_Dylan.jpg"
 },
 "мяч": {
  "t": "Many balls.jpg",
  "a": "Conrad 7",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Many_balls.jpg"
 },
 "мёд": {
  "t": "Runny hunny.jpg",
  "a": "Scott Bauer, USDA ARS",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Runny_hunny.jpg"
 },
 "наказание": {
  "t": "Pentonvilleiso19.jpg",
  "a": "Joshua Jebb",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Pentonvilleiso19.jpg"
 },
 "наркомания": {
  "t": "Syringe-1884784 1920.jpg",
  "a": "Pixabay",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Syringe-1884784_1920.jpg"
 },
 "наркотик": {
  "t": "Bayer Heroin bottle.jpg",
  "a": "Mpv_51 at English Wikipedia",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bayer_Heroin_bottle.jpg"
 },
 "невеста": {
  "t": "Wed-dress-001.jpg",
  "a": "Charles W. Lindner, active 1890-1894 in Chicago",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Wed-dress-001.jpg"
 },
 "новость": {
  "t": "NYTimes-Page1-11-11-1918.jpg",
  "a": "Charles Ransom Miller",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:NYTimes-Page1-11-11-1918.jpg"
 },
 "носок": {
  "t": "HandKnittedWhiteLaceSock.jpg",
  "a": "Loggie-log",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:HandKnittedWhiteLaceSock.jpg"
 },
 "облако": {
  "t": "ISS-40 Thunderheads near Borneo.jpg",
  "a": "NASA/Expedition 40 crew member",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:ISS-40_Thunderheads_near_Borneo.jpg"
 },
 "образование": {
  "t": "Schoolgirls in Bamozai.JPG",
  "a": "Capt. John Severns, U.S. Air Force",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Schoolgirls_in_Bamozai.JPG"
 },
 "обстановка": {
  "t": "8th Century BCE Assyrian Plaque from Fort Shalmaneser. in Nimrud.jpg",
  "a": "Artist Unknown",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:8th_Century_BCE_Assyrian_Plaque_from_Fort_Shalmaneser._in_Nimrud.jpg"
 },
 "одежда": {
  "t": "Clothes.jpg",
  "a": "Unknown authorUnknown author",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Clothes.jpg"
 },
 "остров": {
  "t": "Hawaje-NoRedLine.jpg",
  "a": "Jacques Descloitres",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Hawaje-NoRedLine.jpg"
 },
 "офицер": {
  "t": "Sabhara officer.jpg",
  "a": "Kepolisian Negara Republik Indonesia",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Sabhara_officer.jpg"
 },
 "официант": {
  "t": "Annie O'Black 1973.jpg",
  "a": "Lars Jacob",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Annie_O%27Black_1973.jpg"
 },
 "пасха": {
  "t": "Chora Anastasis2.jpg",
  "a": "AnonymousUnknown author",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Chora_Anastasis2.jpg"
 },
 "певец": {
  "t": "Ah cricket 20122 (7364759010).jpg",
  "a": "Owen Lucas from Bath, UK",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Ah_cricket_20122_(7364759010).jpg"
 },
 "певица": {
  "t": "Ah cricket 20122 (7364759010).jpg",
  "a": "Owen Lucas from Bath, UK",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Ah_cricket_20122_(7364759010).jpg"
 },
 "песня": {
  "t": "Billie Holiday, Downbeat, New York, N.Y., ca. Feb. 1947 (William P. Gottlieb 04251).jpg",
  "a": "William P. Gottlieb",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Billie_Holiday,_Downbeat,_New_York,_N.Y.,_ca._Feb._1947_(William_P._Gottlieb_04251).jpg"
 },
 "писатель": {
  "t": "Francisco de Goya y Lucientes - Gaspar Melchor de Jovellanos.jpg",
  "a": "Unknown authorUnknown author",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Francisco_de_Goya_y_Lucientes_-_Gaspar_Melchor_de_Jovellanos.jpg"
 },
 "пистолет": {
  "t": "Pistol used by \"Squeaky\" Fromme.JPG",
  "a": "",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Pistol_used_by_%22Squeaky%22_Fromme.JPG"
 },
 "платье": {
  "t": "Afternoon ensemble MET 63.212a-b CP4.jpg",
  "a": "",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Afternoon_ensemble_MET_63.212a-b_CP4.jpg"
 },
 "победа": {
  "t": "La Liberté guidant le peuple - Eugène Delacroix - Musée du Louvre Peintures RF 129 - après restauration 2024.jpg",
  "a": "Eugène Delacroix",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg"
 },
 "подруга": {
  "t": "Best friends (1934), by Romualdo Locatelli.jpg",
  "a": "Romualdo Locatelli",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Best_friends_(1934),_by_Romualdo_Locatelli.jpg"
 },
 "показание": {
  "t": "Testimony in court.jpg",
  "a": "Environmental Protection Agency. 12/2/1970",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Testimony_in_court.jpg"
 },
 "преступление": {
  "t": "Jakub Schikaneder - Murder in the House.JPG",
  "a": "Jakub Schikaneder",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Jakub_Schikaneder_-_Murder_in_the_House.JPG"
 },
 "преступник": {
  "t": "Jakub Schikaneder - Murder in the House.JPG",
  "a": "Jakub Schikaneder",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Jakub_Schikaneder_-_Murder_in_the_House.JPG"
 },
 "противник": {
  "t": "Yevgeny Onegin by Repin.jpg",
  "a": "Ilya Repin",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Yevgeny_Onegin_by_Repin.jpg"
 },
 "профессор": {
  "t": "Einstein 1921 by F Schmutzer - restoration.jpg",
  "a": "Ferdinand Schmutzer / Adam Cuerden",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Einstein_1921_by_F_Schmutzer_-_restoration.jpg"
 },
 "пуговица": {
  "t": "Reserveknapper til Hans' uniform.jpg",
  "a": "Europeana staff photographer",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Reserveknapper_til_Hans%27_uniform.jpg"
 },
 "распятие": {
  "t": "Crucifixion Strasbourg Unterlinden Inv88RP536.jpg",
  "a": "A Strasburgian painter Possibly Hermann Schadeberg",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Crucifixion_Strasbourg_Unterlinden_Inv88RP536.jpg"
 },
 "родитель": {
  "t": "Parents and their baby.jpg",
  "a": "sheldonl",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Parents_and_their_baby.jpg"
 },
 "роман": {
  "t": "Madame de Pompadour.jpg",
  "a": "François Boucher",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Madame_de_Pompadour.jpg"
 },
 "рубль": {
  "t": "5000 rubles obverse 2023.jpg",
  "a": "w:ru:Банк России",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:5000_rubles_obverse_2023.jpg"
 },
 "самоубийство": {
  "t": "Édouard Manet - Le Suicidé (ca. 1877).jpg",
  "a": "Édouard Manet",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:%C3%89douard_Manet_-_Le_Suicid%C3%A9_(ca._1877).jpg"
 },
 "сахар": {
  "t": "Sucre blanc cassonade complet rapadura.jpg",
  "a": "Romain Behar",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Sucre_blanc_cassonade_complet_rapadura.jpg"
 },
 "сестра": {
  "t": "Little Julia tending the baby at home.jpg",
  "a": "Lewis Hine, 1874-1940, photographer.",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Little_Julia_tending_the_baby_at_home.jpg"
 },
 "сигнал": {
  "t": "William Powell Frith The signal 1858.jpg",
  "a": "William Powell Frith",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:William_Powell_Frith_The_signal_1858.jpg"
 },
 "собор": {
  "t": "Catedral da Sé em São Paulo.jpg",
  "a": "Wilfredor",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Catedral_da_S%C3%A9_em_S%C3%A3o_Paulo.jpg"
 },
 "сок": {
  "t": "Orange juice 1.jpg",
  "a": "Agricultural Research Service",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Orange_juice_1.jpg"
 },
 "солдат": {
  "t": "2ID Recon Baghdad.jpg",
  "a": "Petty Officer 1st Class Marton Anton Edgil.",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:2ID_Recon_Baghdad.jpg"
 },
 "сон": {
  "t": "A dream (BM 1868,0808.9057).jpg",
  "a": "Print made by: Robert Seymour (?)\n\nPublished by: Thomas McLean\nPrinted by: Josep",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:A_dream_(BM_1868,0808.9057).jpg"
 },
 "спина": {
  "t": "Posterior view of human female and male backs (cropped).jpg",
  "a": "Taken at City Studios in Stockholm (www.stockholmsfotografen.se), September 29, ",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Posterior_view_of_human_female_and_male_backs_(cropped).jpg"
 },
 "спинка": {
  "t": "Posterior view of human female and male backs (cropped).jpg",
  "a": "Taken at City Studios in Stockholm (www.stockholmsfotografen.se), September 29, ",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Posterior_view_of_human_female_and_male_backs_(cropped).jpg"
 },
 "спорт": {
  "t": "Youth-soccer-indiana.jpg",
  "a": "Tysto",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Youth-soccer-indiana.jpg"
 },
 "справедливость": {
  "t": "Justice Statue Iran.jpg",
  "a": "Ing.Arch.Stanislav Sůva - Sculptor: Lajoš Biró",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Justice_Statue_Iran.jpg"
 },
 "стул": {
  "t": "Set of fourteen side chairs MET DP110780.jpg",
  "a": "Thomas Chippendale",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:Set_of_fourteen_side_chairs_MET_DP110780.jpg"
 },
 "судья": {
  "t": "ICJ-CJI hearing 1.jpg",
  "a": "Jeroen Bouman",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:ICJ-CJI_hearing_1.jpg"
 },
 "супруг": {
  "t": "Lotto, Lorenzo - Husband and Wife.jpg",
  "a": "Lorenzo Lotto",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Lotto,_Lorenzo_-_Husband_and_Wife.jpg"
 },
 "супруга": {
  "t": "Kustodiev Merchants Wife.jpg",
  "a": "Boris Kustodiev",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Kustodiev_Merchants_Wife.jpg"
 },
 "театр": {
  "t": "Bernhardt Hamlet2.jpg",
  "a": "Lafayette Photo, London",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Bernhardt_Hamlet2.jpg"
 },
 "телевидение": {
  "t": "Cptvdisplay.jpg",
  "a": "Wags05 at English Wikipedia",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Cptvdisplay.jpg"
 },
 "техник": {
  "t": "Technician checks circuit card.jpg",
  "a": "Bill Branson (Photographer)",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Technician_checks_circuit_card.jpg"
 },
 "товарищ": {
  "t": "Harrison Fisher WWI American Red Cross poster.jpg",
  "a": "Harrison Fisher",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Harrison_Fisher_WWI_American_Red_Cross_poster.jpg"
 },
 "труп": {
  "t": "Disderi 2.jpg",
  "a": "Eugène Disdéri",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Disderi_2.jpg"
 },
 "тюрьма": {
  "t": "Pentonvilleiso19.jpg",
  "a": "Joshua Jebb",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Pentonvilleiso19.jpg"
 },
 "тёща": {
  "t": "Guerre contre le Paraguay - L'Emperur de Brésil et seus deux gendres, le Duc de Saxe-Cobourg-Gotha et le Comte D'Eu, au camp D'Alegrete (D'après un dessin de M. Maximo Alvès).jpg",
  "a": "Ange Louis Janet",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Guerre_contre_le_Paraguay_-_L%27Emperur_de_Br%C3%A9sil_et_seus_deux_gendres,_le_Duc_de_Saxe-Cobourg-Gotha_et_le_Comte_D%27Eu,_au_camp_D%27Alegrete_(D%27apr%C3%A8s_un_dessin_de_M._Maximo_Alv%C3%A8s).jpg"
 },
 "убийство": {
  "t": "Peter Paul Rubens - Cain slaying Abel (Courtauld Institute).jpg",
  "a": "Peter Paul Rubens",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Peter_Paul_Rubens_-_Cain_slaying_Abel_(Courtauld_Institute).jpg"
 },
 "урок": {
  "t": "William-Adolphe Bouguereau (1825-1905) - The Difficult Lesson (1884).jpg",
  "a": "William-Adolphe Bouguereau",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:William-Adolphe_Bouguereau_(1825-1905)_-_The_Difficult_Lesson_(1884).jpg"
 },
 "ус": {
  "t": "Gaishi Nagaoka.jpg",
  "a": "Unknown authorUnknown author",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Gaishi_Nagaoka.jpg"
 },
 "фамилия": {
  "t": "FML Names-3.jpg",
  "a": "PikachuMai",
  "l": "CC0",
  "u": "https://commons.wikimedia.org/wiki/File:FML_Names-3.jpg"
 },
 "шкаф": {
  "t": "Serwantka.JPG",
  "a": "No machine-readable author provided. Julo assumed (based on copyright claims).",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Serwantka.JPG"
 },
 "яйцо": {
  "t": "Adolphe Millot oeufs-fixed.jpg",
  "a": "Adolphe Millot",
  "l": "Public domain",
  "u": "https://commons.wikimedia.org/wiki/File:Adolphe_Millot_oeufs-fixed.jpg"
 }
};
