/* GENERATED by tools/build_notices.mjs — do not edit.
 *
 * The licences of everything the app ships, read off what is installed in
 * node_modules rather than written down by hand (which is how such a list
 * comes to be wrong with nothing failing). Re-run the tool after npm install.
 *
 * 28 runtime dependencies, 2 distinct licences.
 */

export const NOTICES = [
  {
    "l": "MIT",
    "packages": [
      "@react-native-async-storage/async-storage",
      "@react-navigation/bottom-tabs",
      "@react-navigation/native",
      "@react-navigation/native-stack",
      "expo",
      "expo-asset",
      "expo-audio",
      "expo-constants",
      "expo-document-picker",
      "expo-file-system",
      "expo-font",
      "expo-haptics",
      "expo-sharing",
      "expo-speech",
      "expo-speech-recognition",
      "expo-sqlite",
      "expo-status-bar",
      "expo-system-ui",
      "fflate",
      "fzstd",
      "react",
      "react-native",
      "react-native-safe-area-context",
      "react-native-screens",
      "react-native-svg",
      "react-native-webview",
      "ts-fsrs"
    ]
  },
  {
    "l": "MIT AND OFL-1.1",
    "packages": [
      "@expo-google-fonts/nunito"
    ]
  }
];

export const NOTICE_COUNT = 28;
