/* Generated by tools/build_cast_art.mjs --ship. Do not edit. One picture a
   unit: the cast doing the unit's subject (docs/cast.md). */
export const SCENE_ART = {
  "sport": require("../assets/episodes/sport.jpg"),
};
