/* GENERATED by tools/build_word_assets.mjs — do not edit.
 *
 * The curriculum words his Anki collection has no recording for, bought from
 * Chirp3-HD and bundled (ROADMAP 13.32). 61 clips, keyed by the
 * **folded** word, which is the key `say()` already derives (rule 20.2 — the
 * manifest folds ё to е and a lemma's bare form does not, which is how the
 * first count of these came out at 75 instead of 61).
 *
 * Required statically because Metro resolves assets at build time; that is
 * also why this file is generated rather than a directory read.
 */

export const WORD_CLIPS = {
  "атом": require("../assets/words/atom.mp3"),
  "бросить": require("../assets/words/brosit.mp3"),
  "броситься": require("../assets/words/brositsya.mp3"),
  "вакцина": require("../assets/words/vakcina.mp3"),
  "вернуться": require("../assets/words/vernutsya.mp3"),
  "вскинуть": require("../assets/words/vskinut.mp3"),
  "вспомнить": require("../assets/words/vspomnit.mp3"),
  "выехать": require("../assets/words/vyehat.mp3"),
  "вызвать": require("../assets/words/vyzvat.mp3"),
  "выиграть": require("../assets/words/vyigrat.mp3"),
  "выйти": require("../assets/words/vyjti.mp3"),
  "выпить": require("../assets/words/vypit.mp3"),
  "дать": require("../assets/words/dat.mp3"),
  "договориться": require("../assets/words/dogovoritsya.mp3"),
  "забыть": require("../assets/words/zabyt.mp3"),
  "завоевать": require("../assets/words/zavoevat.mp3"),
  "заговорить": require("../assets/words/zagovorit.mp3"),
  "заказать": require("../assets/words/zakazat.mp3"),
  "запомнить": require("../assets/words/zapomnit.mp3"),
  "измерить": require("../assets/words/izmerit.mp3"),
  "клиника": require("../assets/words/klinika.mp3"),
  "красить": require("../assets/words/krasit.mp3"),
  "медленно": require("../assets/words/medlenno.mp3"),
  "надеть": require("../assets/words/nadet.mp3"),
  "нажать": require("../assets/words/nazhat.mp3"),
  "назвать": require("../assets/words/nazvat.mp3"),
  "найти": require("../assets/words/najti.mp3"),
  "напасть": require("../assets/words/napast.mp3"),
  "напевать": require("../assets/words/napevat.mp3"),
  "начаться": require("../assets/words/nachatsya.mp3"),
  "об": require("../assets/words/ob.mp3"),
  "объяснить": require("../assets/words/obyasnit.mp3"),
  "остаться": require("../assets/words/ostatsya.mp3"),
  "ответить": require("../assets/words/otvetit.mp3"),
  "отправиться": require("../assets/words/otpravitsya.mp3"),
  "победить": require("../assets/words/pobedit.mp3"),
  "повторить": require("../assets/words/povtorit.mp3"),
  "полк": require("../assets/words/polk.mp3"),
  "получить": require("../assets/words/poluchit.mp3"),
  "помочь": require("../assets/words/pomoch.mp3"),
  "понять": require("../assets/words/ponyat.mp3"),
  "попросить": require("../assets/words/poprosit.mp3"),
  "править": require("../assets/words/pravit.mp3"),
  "прибыть": require("../assets/words/pribyt.mp3"),
  "приехать": require("../assets/words/priehat.mp3"),
  "прийти": require("../assets/words/prijti.mp3"),
  "приказать": require("../assets/words/prikazat.mp3"),
  "произойти": require("../assets/words/proizojti.mp3"),
  "пройти": require("../assets/words/projti.mp3"),
  "ранение": require("../assets/words/ranenie.mp3"),
  "рассказать": require("../assets/words/rasskazat.mp3"),
  "снять": require("../assets/words/snyat.mp3"),
  "сообщить": require("../assets/words/soobshchit.mp3"),
  "спросить": require("../assets/words/sprosit.mp3"),
  "стать": require("../assets/words/stat.mp3"),
  "теннис": require("../assets/words/tennis.mp3"),
  "убить": require("../assets/words/ubit.mp3"),
  "удивиться": require("../assets/words/udivitsya.mp3"),
  "уйти": require("../assets/words/ujti.mp3"),
  "уснуть": require("../assets/words/usnut.mp3"),
  "успеть": require("../assets/words/uspet.mp3"),
};

export const wordClip = (folded) => WORD_CLIPS[folded] || null;
