"""Ship the harvested photographs with the native app.

Reads data/raw/images/ (tools/harvest_images.py) and writes:

  native/assets/img/<n>.jpg     the thumbnails, numbered — a Cyrillic file name
                                is a bundler's problem, and the number is only
                                looked up through the map below
  native/src/images.js          IMAGES: bare word -> require(...), generated, so
                                Metro sees every asset statically; and CREDITS,
                                title, author and licence per word, for the
                                word's entry

Only words the curriculum carries are shipped (the payload decides); a photo
whose word has left the units is dropped from the app, not from the cache.

    python tools/build_images.py
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw" / "images"
OUT = ROOT / "native" / "assets" / "img"
JS = ROOT / "native" / "src" / "images.js"
ABSTRACT_UNITS = {"time", "emotion", "speech", "politics", "business"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--payload", type=Path, default=ROOT / "native" / "assets" / "data.json")
    args = ap.parse_args()

    manifest = json.loads((RAW / "manifest.json").read_text(encoding="utf-8"))
    payload = json.loads(args.payload.read_text(encoding="utf-8"))
    # Only units whose words are things: a search for "investment" or "society"
    # returns something, and that something is the kind of picture that makes an
    # app look generated. The spine's nouns (время, год, человек) are left out
    # for the same reason.
    taught = {payload["lemmas"][i]["b"] for u in payload["units"]
              if u["kind"] != "spine" and u["id"] not in ABSTRACT_UNITS for i in u["w"]}

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.jpg"):
        old.unlink()
    entries, credits, total = [], {}, 0
    for n, (bare, info) in enumerate(sorted(manifest.items())):
        src = RAW / f"{bare}.jpg"
        if not info or not src.exists() or bare not in taught:
            continue
        name = f"{n:04d}.jpg"
        shutil.copyfile(src, OUT / name)
        total += src.stat().st_size
        entries.append((bare, name))
        credits[bare] = {"t": info["title"].replace("File:", ""), "a": info.get("author") or "",
                         "l": info["licence"], "u": info.get("url") or ""}

    lines = ["/* Generated by tools/build_images.py — do not edit. Public-domain and CC0",
             "   photographs from Wikimedia Commons for the words the units teach, keyed",
             "   on the bare word. CREDITS carries each file's title, author and licence. */",
             "", "export const IMAGES = {"]
    for bare, name in entries:
        lines.append(f'  "{bare}": require("../assets/img/{name}"),')
    lines.append("};")
    lines.append("")
    lines.append("export const CREDITS = " + json.dumps(credits, ensure_ascii=False, indent=1) + ";")
    lines.append("")
    JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {JS}")
    print(f"  photos shipped : {len(entries)} of {sum(1 for v in manifest.values() if v)} harvested"
          f" ({len(taught)} words taught)")
    print(f"  bytes          : {total / 1_048_576:.1f} MB")


if __name__ == "__main__":
    main()
