/* The open-source notices, read off what is actually installed.
 *
 * Every dependency the app ships carries a licence, and most of them require
 * the licence and copyright to travel with the binary. That is a condition,
 * not a courtesy — the same standing as rule 20.10's attribution for the
 * dictionaries — and Play asks for it too.
 *
 * **Generated, never hand-written.** A list typed into a screen is a list that
 * is wrong the first time a dependency is added, removed or relicensed, and
 * nothing would fail. This reads `native/package.json`'s runtime dependencies,
 * follows each into `node_modules`, and takes the licence that package
 * declares about itself. A dependency that declares nothing is reported rather
 * than guessed at: inventing a licence for someone else's code is exactly the
 * failure this is meant to prevent.
 *
 * Writes `native/src/notices.js`. Re-run it after `npm install`.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const NATIVE = join(ROOT, "native");

const pkg = JSON.parse(readFileSync(join(NATIVE, "package.json"), "utf8"));
const names = Object.keys(pkg.dependencies || {}).sort();

/* The licence text a package ships, if it ships one. Only the common file
   names — this is for the notice, and a package that hides its licence
   somewhere unusual is flagged rather than trawled for. */
const LICENCE_FILES = ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE",
                       "LICENCE.md", "LICENCE.txt", "license", "license.md"];

function licenceOf(dir) {
  const p = join(dir, "package.json");
  if (!existsSync(p)) return { licence: null, why: "not installed" };
  let meta;
  try { meta = JSON.parse(readFileSync(p, "utf8")); }
  catch (e) { return { licence: null, why: "unreadable package.json" }; }
  /* `license` is a string on anything modern; the old array/object shapes still
     turn up in transitive trees and are read rather than skipped. */
  const l = meta.license || meta.licenses;
  const text = typeof l === "string" ? l
    : Array.isArray(l) ? l.map((x) => (typeof x === "string" ? x : x.type)).filter(Boolean).join(" OR ")
    : l && l.type ? l.type : null;
  const has = readdirSync(dir).some((f) => LICENCE_FILES.includes(f));
  return { licence: text, why: text ? null : "declares no licence", file: has };
}

const rows = [];
const problems = [];
for (const name of names) {
  const dir = join(NATIVE, "node_modules", ...name.split("/"));
  const { licence, why } = licenceOf(dir);
  if (!licence) problems.push(`${name}: ${why}`);
  rows.push({ n: name, v: (pkg.dependencies[name] || "").replace(/^[\^~]/, ""), l: licence || "see the package" });
}

/* Grouped by licence, because that is how a notices screen is read: one line
   per licence with the packages under it, not fifty near-identical rows. */
const byLicence = {};
for (const r of rows) (byLicence[r.l] = byLicence[r.l] || []).push(r.n);

const out = `/* GENERATED by tools/build_notices.mjs — do not edit.
 *
 * The licences of everything the app ships, read off what is installed in
 * node_modules rather than written down by hand (which is how such a list
 * comes to be wrong with nothing failing). Re-run the tool after npm install.
 *
 * ${rows.length} runtime dependencies, ${Object.keys(byLicence).length} distinct licences.
 */

export const NOTICES = ${JSON.stringify(
  Object.keys(byLicence).sort().map((l) => ({ l, packages: byLicence[l].sort() })), null, 2)};

export const NOTICE_COUNT = ${rows.length};
`;

writeFileSync(join(NATIVE, "src", "notices.js"), out);

console.log(`${rows.length} runtime dependencies`);
for (const l of Object.keys(byLicence).sort()) {
  console.log(`  ${l.padEnd(16)} ${byLicence[l].length}`);
}
if (problems.length) {
  console.log(`\n${problems.length} without a declared licence — read these before shipping:`);
  problems.forEach((p) => console.log("   " + p));
  process.exitCode = 1;
} else {
  console.log("\nevery dependency declares a licence");
}
