/* The bought word clips into the app (ROADMAP 13.32).
 *
 * `build_word_audio.mjs` buys them into `data/word_audio/` keyed by a content
 * hash, and those files are **committed**, because they cost money — the same
 * rule the scenario clips follow (§30l). This copies them under a readable
 * name into `native/assets/words/` and writes `native/src/wordaudio.js`, which
 * is a `require` per clip: Metro resolves assets at build time, so the list has
 * to exist in source rather than be read from a directory.
 *
 * Bundled rather than uploaded. The collection's 13,183 recordings stream from
 * the web host, and putting these there would mean a Netlify deploy, which
 * costs credits (§31). 332 KB rides along in the APK for nothing and works
 * with no network — which, for the words the aspect drill asks about, is the
 * better answer anyway.
 *
 *   node tools/build_word_assets.mjs
 *
 * Re-runnable; it writes the whole directory and the whole module each time
 * from what is in `data/word_audio/`, so a clip deleted by hand disappears
 * from the app too.
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, rmSync, copyFileSync }
  from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { fold } from "../core/util.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "data", "word_audio");
const MANIFEST = join(SRC, "manifest.json");
const OUT = join(ROOT, "native", "assets", "words");
const MODULE = join(ROOT, "native", "src", "wordaudio.js");

if (!existsSync(MANIFEST)) {
  console.error(`no ${MANIFEST}. Run tools/build_word_audio.mjs first.`);
  process.exit(2);
}
const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
const files = manifest.files || {};

/* A file name a person can read in a diff, from the word itself. Latin-safe
   because Metro and Gradle both handle asset names better that way, and two
   words never collide because the folded form is unique in the manifest. */
const TRANSLIT = {
  а: "a", б: "b", в: "v", г: "g", д: "d", е: "e", ж: "zh", з: "z", и: "i", й: "j",
  к: "k", л: "l", м: "m", н: "n", о: "o", п: "p", р: "r", с: "s", т: "t", у: "u",
  ф: "f", х: "h", ц: "c", ч: "ch", ш: "sh", щ: "shch", ъ: "", ы: "y", ь: "", э: "e",
  ю: "yu", я: "ya",
};
const slug = (w) => [...fold(w)].map((c) => (TRANSLIT[c] !== undefined ? TRANSLIT[c] : "")).join("")
  || "w";

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const rows = [];
const used = new Set();
let missing = 0;
for (const word of Object.keys(files).sort()) {
  const from = join(SRC, files[word] + ".mp3");
  if (!existsSync(from)) { missing++; continue; }
  let name = slug(word);
  // A transliteration can collide («есть»/«естъ» kinds of thing); the hash is
  // what makes it unique, so it breaks the tie rather than the word being lost.
  if (used.has(name)) name = `${name}-${files[word].slice(0, 6)}`;
  used.add(name);
  copyFileSync(from, join(OUT, name + ".mp3"));
  rows.push({ key: fold(word), name });
}

const body = rows.map((r) => `  ${JSON.stringify(r.key)}: require("../assets/words/${r.name}.mp3"),`)
  .join("\n");

writeFileSync(MODULE, `/* GENERATED by tools/build_word_assets.mjs — do not edit.
 *
 * The curriculum words his Anki collection has no recording for, bought from
 * Chirp3-HD and bundled (ROADMAP 13.32). ${rows.length} clips, keyed by the
 * **folded** word, which is the key \`say()\` already derives (rule 20.2 — the
 * manifest folds ё to е and a lemma's bare form does not, which is how the
 * first count of these came out at 75 instead of 61).
 *
 * Required statically because Metro resolves assets at build time; that is
 * also why this file is generated rather than a directory read.
 */

export const WORD_CLIPS = {
${body}
};

export const wordClip = (folded) => WORD_CLIPS[folded] || null;
`);

const bytes = readdirSync(OUT).reduce((n, f) => n + readFileSync(join(OUT, f)).length, 0);
console.log(`${rows.length} word clips → native/assets/words/ (${(bytes / 1024).toFixed(0)} KB)`);
if (missing) console.log(`  !! ${missing} named in the manifest but not on disk`);
console.log(`wrote ${MODULE}`);
