"""Ship the harvested photographs with the native app.

Reads data/raw/images/ (tools/harvest_images.py) and writes:

  native/assets/img/<n>.jpg     the thumbnails, numbered — a Cyrillic file name
                                is a bundler's problem, and the number is only
                                looked up through the map below
  native/src/images.js          IMAGES: bare word -> require(...), generated, so
                                Metro sees every asset statically; and CREDITS,
                                title, author, licence and page per word, for
                                the word's entry — the credit a CC BY licence
                                asks for

Only words the curriculum carries are shipped (the payload decides); a photo
whose word has left the units is dropped from the app, not from the cache.
Only the second harvest's records ship (manifest entries with v == 2): the
first harvest's plain Commons searches were half wrong subjects, and its
public-domain pool looked a century old.

    python tools/build_images.py
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw" / "images"
OUT = ROOT / "native" / "assets" / "img"
JS = ROOT / "native" / "src" / "images.js"
VERSION = 2


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--payload", type=Path, default=ROOT / "native" / "assets" / "data.json")
    args = ap.parse_args()

    manifest = json.loads((RAW / "manifest.json").read_text(encoding="utf-8"))
    payload = json.loads(args.payload.read_text(encoding="utf-8"))
    taught = {payload["lemmas"][i]["b"] for u in payload["units"] for i in u["w"]}

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.jpg"):
        old.unlink()
    entries, credits, total, stale = [], {}, 0, 0
    by_via = {}
    for n, (bare, info) in enumerate(sorted(manifest.items())):
        src = RAW / f"{bare}.jpg"
        if not info or bare.startswith("_") or not src.exists() or bare not in taught:
            continue
        if info.get("v") != VERSION:
            stale += 1
            continue
        name = f"{n:04d}.jpg"
        shutil.copyfile(src, OUT / name)
        total += src.stat().st_size
        entries.append((bare, name))
        by_via[info.get("via")] = by_via.get(info.get("via"), 0) + 1
        credits[bare] = {"t": info["title"].replace("File:", ""), "a": info.get("author") or "",
                         "l": info["licence"], "u": info.get("url") or ""}

    lines = ["/* Generated by tools/build_images.py — do not edit. Photographs from",
             "   Wikipedia's articles and Wikimedia Commons, free to reuse with credit",
             "   (CC0, public domain, CC BY, CC BY-SA), for the words the units teach,",
             "   keyed on the bare word. CREDITS carries each file's title, author,",
             "   licence and page, shown on the word's entry. */",
             "", "export const IMAGES = {"]
    for bare, name in entries:
        lines.append(f'  "{bare}": require("../assets/img/{name}"),')
    lines.append("};")
    lines.append("")
    lines.append("export const CREDITS = " + json.dumps(credits, ensure_ascii=False, indent=1) + ";")
    lines.append("")
    JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {JS}")
    print(f"  photos shipped : {len(entries)} of {len(taught)} words taught "
          f"({', '.join(f'{k} {v}' for k, v in sorted(by_via.items()))}; {stale} first-harvest records left out)")
    print(f"  bytes          : {total / 1_048_576:.1f} MB")


if __name__ == "__main__":
    main()
